services:
  backend:
    environment: &oidc-secret-file
      TEKDOCS_OIDC_CLIENT_SECRET: ""
      TEKDOCS_OIDC_CLIENT_SECRET_FILE: /run/secrets/oidc_client_secret
    secrets: &oidc-secret
      - oidc_client_secret
  worker:
    environment: *oidc-secret-file
    secrets: *oidc-secret
  scheduler:
    environment: *oidc-secret-file
    secrets: *oidc-secret

secrets:
  oidc_client_secret:
    file: ${TEKDOCS_SECRET_DIRECTORY:?Set TEKDOCS_SECRET_DIRECTORY}/oidc_client_secret
