services:
  migrate:
    restart: "no"
  backend:
    environment:
      DJANGO_SETTINGS_MODULE: tekdocs.settings.production
    restart: "no"
  worker:
    restart: "no"
  scheduler:
    restart: "no"
  mailpit:
    restart: "no"
  frontend:
    restart: "no"
