services:
  backend:
    environment: &smtp-secret-file
      EMAIL_HOST_PASSWORD: ""
      EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_host_password
    secrets: &smtp-secret
      - email_host_password
  worker:
    environment: *smtp-secret-file
    secrets: *smtp-secret
  scheduler:
    environment: *smtp-secret-file
    secrets: *smtp-secret

secrets:
  email_host_password:
    file: ${TEKDOCS_SECRET_DIRECTORY:?Set TEKDOCS_SECRET_DIRECTORY}/email_host_password
