# Generated by Django 5.2.17 on 2026-08-07 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=240)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.tenant')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_links', to='core.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='core.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_links', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'link_type'], name='core_entity_tenant__b81b7f_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'link_type'), name='unique_typed_entity_link'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='entity_link_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'entity_type'], name='core_entity_tenant__0f1c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'display_name'], name='core_entity_tenant__3896e9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'action', 'occurred_at'], name='core_audite_tenant__a71f8f_idx'),
        ),
    ]
