# Generated by Django 5.2.17 on 2026-08-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_installation_state(apps, schema_editor):
    installation_state = apps.get_model("core", "InstallationState")
    installation_state.objects.create(id=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('bootstrapped_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_installation', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_state', to='core.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='installation_state_singleton'), models.CheckConstraint(condition=models.Q(models.Q(('bootstrapped_at__isnull', True), ('owner__isnull', True), ('tenant__isnull', True)), models.Q(('bootstrapped_at__isnull', False), ('owner__isnull', False), ('tenant__isnull', False)), _connector='OR'), name='installation_state_complete_or_empty')],
            },
        ),
        migrations.RunPython(create_installation_state, migrations.RunPython.noop),
    ]
