# Generated by Django 5.2.17 on 2026-08-08 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_installationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization_record', to='core.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_entities', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'organization', 'entity_type'], name='core_entity_tenant__7b4634_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tenant', 'created_at'], name='core_organi_tenant__b19aea_idx'),
        ),
    ]
