# Generated by Django 5.2.17 on 2026-08-08 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scope_database_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='OrganizationClassification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('manufacturer', 'Manufacturer'), ('partner', 'Partner')], max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_classifications', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'kind', 'organization'], name='core_organi_tenant__db5f15_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='unique_organization_classification')],
            },
        ),
    ]
