# Generated by Django 5.2.17 on 2026-08-08 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_classification_scope_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='person_record', to='core.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssociation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('employee', 'Employee'), ('contact', 'Contact')], max_length=32)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('responsibility', models.CharField(blank=True, max_length=240)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('office', models.CharField(blank=True, max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_associations', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associations', to='core.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_associations', to='core.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tenant', 'created_at'], name='core_person_tenant__fe8a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='personassociation',
            index=models.Index(fields=['tenant', 'organization', 'archived_at'], name='core_person_tenant__86f12c_idx'),
        ),
        migrations.AddIndex(
            model_name='personassociation',
            index=models.Index(fields=['tenant', 'kind', 'organization'], name='core_person_tenant__03ec68_idx'),
        ),
        migrations.AddConstraint(
            model_name='personassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('person', 'organization'), name='unique_person_organization_association'),
        ),
        migrations.AddConstraint(
            model_name='personassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('person',), name='unique_person_msp_association'),
        ),
    ]
