# Generated by Django 5.2.17 on 2026-08-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_access_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='visibility',
            field=models.CharField(choices=[('msp_private', 'MSP private'), ('client_visible', 'Client visible')], default='msp_private', max_length=24),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['tenant', 'organization', 'visibility'], name='core_entity_tenant__4d4b64_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['msp_private', 'client_visible'])), name='entity_visibility_valid'),
        ),
    ]
