# Generated by Django 5.2.17 on 2026-08-09 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_activate_runtime_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('markdown', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='block_record', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document_record', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationListingReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_references', to='core.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_references', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_references', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPlacement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.block')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='core.document')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_placements', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_placements', to='core.tenant')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['tenant', 'organization', 'archived_at'], name='core_block_tenant__5e73aa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'organization', 'archived_at'], name='core_docume_tenant__ac7d66_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationlistingreference',
            index=models.Index(fields=['tenant', 'organization', 'archived_at'], name='core_docume_tenant__6ee5c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentationlistingreference',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('organization', 'document'), name='unique_active_documentation_listing_reference'),
        ),
        migrations.AddIndex(
            model_name='documentplacement',
            index=models.Index(fields=['tenant', 'organization', 'document', 'position'], name='core_docume_tenant__46e522_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentplacement',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_document_block_position'),
        ),
    ]
