# Generated by Django 5.2.17 on 2026-08-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_document_placement_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("policy", "Policy"),
                    ("procedure", "Procedure"),
                    ("guide", "Guide"),
                    ("reference", "Reference"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=500, upload_to=apps.core.models.document_attachment_upload_to)),
                ("original_filename", models.CharField(max_length=240)),
                ("media_type", models.CharField(max_length=120)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_attachment_record",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_attachments",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_attachments",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "organization", "category", "is_template", "archived_at"],
                name="core_doc_category_template_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(category__in=["general", "policy", "procedure", "guide", "reference"]),
                name="document_category_supported",
            ),
        ),
        migrations.AddIndex(
            model_name="documentattachment",
            index=models.Index(
                fields=["tenant", "organization", "document", "archived_at"],
                name="core_docatt_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentattachment",
            index=models.Index(fields=["document", "checksum"], name="core_docatt_checksum_idx"),
        ),
    ]
