# Generated by Django 5.2.17 on 2026-08-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_document_attachment_guards_and_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPublication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("policy", "Policy"),
                            ("procedure", "Procedure"),
                            ("guide", "Guide"),
                            ("reference", "Reference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("canonical_markdown", models.TextField(blank=True)),
                ("sanitized_html", models.TextField(blank=True)),
                ("manifest", models.JSONField()),
                ("content_digest", models.CharField(max_length=64)),
                ("signature", models.TextField()),
                ("signature_algorithm", models.CharField(default="Ed25519", max_length=20)),
                ("public_key", models.TextField()),
                ("key_fingerprint", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="core.document",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publication_record",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publications",
                        to="core.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publications",
                        to="core.tenant",
                    ),
                ),
            ],
            options={"ordering": ("-published_at", "id")},
        ),
        migrations.AddIndex(
            model_name="documentpublication",
            index=models.Index(
                fields=["tenant", "organization", "document", "published_at"],
                name="core_docpub_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpublication",
            index=models.Index(fields=["document", "content_digest"], name="core_docpub_digest_idx"),
        ),
    ]
