# Generated by Django 5.2.17 on 2026-08-09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [("core", "0029_document_publication_guards_and_rls")]

    operations = [
        migrations.AddField(
            model_name="documentpublication",
            name="audience",
            field=models.CharField(
                choices=[("msp_internal", "MSP internal"), ("client_visible", "Client visible")],
                default="msp_internal",
                max_length=24,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentpublication",
            name="reason",
            field=models.CharField(default="Initial publication", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentpublication",
            name="retention",
            field=models.CharField(
                choices=[("permanent", "Permanent"), ("review_on", "Review on date")],
                default="permanent",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentpublication",
            name="retention_review_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentpublication",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="core.documentpublication",
            ),
        ),
        migrations.CreateModel(
            name="DocumentPublicationArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("attachment", "Retained attachment")], max_length=20
                    ),
                ),
                ("file", models.FileField(max_length=500, upload_to=apps.core.models.publication_artifact_upload_to)),
                ("original_filename", models.CharField(max_length=240)),
                ("media_type", models.CharField(max_length=120)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publication_artifact",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publication_artifacts",
                        to="core.organization",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="core.documentpublication",
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_artifacts",
                        to="core.documentattachment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publication_artifacts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={"ordering": ("kind", "original_filename", "id")},
        ),
        migrations.AddConstraint(
            model_name="documentpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("audience__in", ["msp_internal", "client_visible"])),
                name="publication_audience_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention__in", ["permanent", "review_on"])),
                name="publication_retention_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublication",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("retention", "permanent"), ("retention_review_on__isnull", True))
                    | models.Q(("retention", "review_on"), ("retention_review_on__isnull", False))
                ),
                name="publication_retention_date_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("audience", "msp_internal")) | models.Q(("organization__isnull", False)),
                name="publication_client_audience_scoped",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublicationartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["pdf", "attachment"])), name="publication_artifact_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublicationartifact",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("kind", "pdf"), ("source_attachment__isnull", True))
                    | models.Q(("kind", "attachment"), ("source_attachment__isnull", False))
                ),
                name="publication_artifact_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublicationartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "pdf")),
                fields=("publication", "kind"),
                name="one_pdf_per_publication",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentpublicationartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_attachment__isnull", False)),
                fields=("publication", "source_attachment"),
                name="one_retained_source_attachment",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpublicationartifact",
            index=models.Index(
                fields=["tenant", "organization", "publication"], name="core_pubart_scope_idx"
            ),
        ),
    ]
