# Generated by Django 5.2.17 on 2026-08-10 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_publication_artifact_guards_and_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("onepassword", "1Password")], max_length=32)),
                ("reference_url", models.CharField(max_length=1000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_reference",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_references",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_references",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
                "indexes": [
                    models.Index(fields=["tenant", "organization", "archived_at"], name="core_credref_scope_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["onepassword"])),
                        name="credential_reference_provider_valid",
                    )
                ],
            },
        ),
    ]
