# Generated by Django 5.2.17 on 2026-08-10 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_credential_reference_guards_and_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogProduct",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("hardware", "Hardware"), ("software", "Software")], max_length=16)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="catalog_product", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_products",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="catalog_products", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_number", models.CharField(max_length=160)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="catalog_model", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_models",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="catalog_models", to="core.tenant"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="models", to="core.catalogproduct"
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogSpecificationDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                (
                    "product_kind",
                    models.CharField(choices=[("hardware", "Hardware"), ("software", "Software")], max_length=16),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_specification_definitions",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_specification_definitions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="CatalogSpecificationDefinitionVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("schema", models.JSONField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_specification_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="core.catalogspecificationdefinition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_specification_versions",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_specification_versions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("definition_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="CatalogModelRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision", models.PositiveIntegerField()),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("discontinued", "Discontinued"),
                            ("pre_release", "Pre-release"),
                        ],
                        max_length=24,
                    ),
                ),
                ("specifications", models.JSONField(default=dict)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_model_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="core.catalogmodel"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_model_revisions",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_revision",
                        to="core.catalogmodelrevision",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_model_revisions",
                        to="core.tenant",
                    ),
                ),
                (
                    "specification_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_revisions",
                        to="core.catalogspecificationdefinitionversion",
                    ),
                ),
            ],
            options={
                "ordering": ("model_id", "revision"),
            },
        ),
        migrations.AddIndex(
            model_name="catalogproduct",
            index=models.Index(fields=["tenant", "organization", "kind", "archived_at"], name="core_catprod_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogmodel",
            index=models.Index(
                fields=["tenant", "organization", "product", "archived_at"], name="core_catmodel_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogmodel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organization", "product", "model_number"), name="unique_catalog_model_number"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogspecificationdefinition",
            index=models.Index(
                fields=["tenant", "organization", "product_kind", "archived_at"], name="core_catspecdef_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogspecificationdefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organization", "product_kind", "name"), name="unique_catalog_spec_definition_name"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogspecificationdefinitionversion",
            index=models.Index(
                fields=["tenant", "organization", "definition", "version"], name="core_catspecver_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogspecificationdefinitionversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "version"), name="unique_catalog_spec_definition_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogspecificationdefinitionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="catalog_spec_version_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogmodelrevision",
            index=models.Index(
                fields=["tenant", "organization", "model", "revision"], name="core_catmodelrev_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogmodelrevision",
            constraint=models.UniqueConstraint(fields=("model", "revision"), name="unique_catalog_model_revision"),
        ),
        migrations.AddConstraint(
            model_name="catalogmodelrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="catalog_model_revision_positive"
            ),
        ),
    ]
