# Generated by Django 5.2.17 on 2026-08-10 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_supplier_catalog_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_product_documents', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_associations', to='core.catalogmodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_product_documents', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_associations', to='core.catalogproduct')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_associations', to='core.documentpublication')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_product_documents', to='core.tenant')),
            ],
            options={
                'ordering': ('publication__title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specifications', models.JSONField(default=dict)),
                ('provenance_checksum', models.CharField(max_length=64)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_assets', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset', to='core.entity')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.catalogmodel')),
                ('model_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.catalogmodelrevision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.catalogproduct')),
                ('specification_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.catalogspecificationdefinitionversion')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplied_client_assets', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assets', to='core.tenant')),
            ],
            options={
                'ordering': ('entity__display_name', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='ClientAssetDocumentProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_provenance', to='core.clientasset')),
                ('catalog_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_provenance', to='core.catalogproductdocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_documents', to='core.organization')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_provenance', to='core.documentpublication')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_documents', to='core.tenant')),
            ],
            options={
                'ordering': ('publication__title', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='catalogproductdocument',
            index=models.Index(fields=['tenant', 'organization', 'product', 'model', 'archived_at'], name='core_catdoc_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('model__isnull', True)), fields=('product', 'publication'), name='unique_active_product_document'),
        ),
        migrations.AddConstraint(
            model_name='catalogproductdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('model__isnull', False)), fields=('product', 'model', 'publication'), name='unique_active_model_document'),
        ),
        migrations.AddIndex(
            model_name='clientasset',
            index=models.Index(fields=['tenant', 'organization', 'archived_at'], name='core_asset_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='clientasset',
            index=models.Index(fields=['tenant', 'organization', 'supplier'], name='core_asset_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='clientassetdocumentprovenance',
            index=models.Index(fields=['tenant', 'organization', 'asset'], name='core_assetdoc_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientassetdocumentprovenance',
            constraint=models.UniqueConstraint(fields=('asset', 'publication'), name='unique_client_asset_publication'),
        ),
    ]
