# Generated by Django 5.2.17 on 2026-08-10 12:20
# ruff: noqa: E501

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_client_asset_provenance_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssetLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('details_updated', 'Details updated'), ('state_changed', 'State changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('disposed', 'Disposed')], max_length=32)),
                ('from_state', models.CharField(blank=True, max_length=24)),
                ('to_state', models.CharField(blank=True, max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='core.clientasset')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_lifecycle_events', to='core.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.personassociation')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_asset_lifecycle_events', to='core.tenant')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'organization', 'asset', 'occurred_at'], name='core_hwevent_scope_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['created', 'details_updated', 'state_changed', 'assigned', 'unassigned', 'disposed'])), name='hardware_event_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='ClientHardwareAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('asset_tag', models.CharField(blank=True, max_length=120)),
                ('lifecycle_state', models.CharField(choices=[('in_stock', 'In stock'), ('in_service', 'In service'), ('repair', 'Repair'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='in_stock', max_length=24)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('acquisition_method', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('lease', 'Lease'), ('rental', 'Rental'), ('transfer', 'Transfer'), ('donation', 'Donation'), ('other', 'Other')], max_length=24)),
                ('acquisition_reference', models.CharField(blank=True, max_length=240)),
                ('warranty_provider', models.CharField(blank=True, max_length=160)),
                ('warranty_starts_on', models.DateField(blank=True, null=True)),
                ('warranty_ends_on', models.DateField(blank=True, null=True)),
                ('warranty_reference', models.CharField(blank=True, max_length=240)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, choices=[('recycled', 'Recycled'), ('returned', 'Returned'), ('sold', 'Sold'), ('donated', 'Donated'), ('destroyed', 'Destroyed'), ('lost', 'Lost'), ('other', 'Other')], max_length=24)),
                ('disposal_reason', models.CharField(blank=True, max_length=500)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hardware', to='core.clientasset')),
                ('assigned_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hardware', to='core.location')),
                ('assigned_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hardware', to='core.personassociation')),
                ('assigned_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_hardware', to='core.site')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_hardware_assets', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_hardware_assets', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'organization', 'lifecycle_state'], name='core_hwasset_scope_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lifecycle_state__in', ['in_stock', 'in_service', 'repair', 'retired', 'disposed'])), name='hardware_state_valid'), models.CheckConstraint(condition=models.Q(('acquisition_method', ''), ('acquisition_method__in', ['purchase', 'lease', 'rental', 'transfer', 'donation', 'other']), _connector='OR'), name='hardware_acquisition_method_valid'), models.CheckConstraint(condition=models.Q(('disposal_method', ''), ('disposal_method__in', ['recycled', 'returned', 'sold', 'donated', 'destroyed', 'lost', 'other']), _connector='OR'), name='hardware_disposal_method_valid'), models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('tenant', 'organization', 'serial_number'), name='unique_hardware_serial_in_org'), models.UniqueConstraint(condition=models.Q(('asset_tag', ''), _negated=True), fields=('tenant', 'organization', 'asset_tag'), name='unique_hardware_tag_in_org')],
            },
        ),
    ]
