# Generated by Django 5.2.17 on 2026-08-10 13:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_software_installations(apps, schema_editor):
    ClientAsset = apps.get_model("core", "ClientAsset")
    ClientSoftwareInstallation = apps.get_model("core", "ClientSoftwareInstallation")
    for asset in ClientAsset.objects.filter(product__kind="software").iterator():
        ClientSoftwareInstallation.objects.get_or_create(
            asset=asset,
            defaults={"tenant_id": asset.tenant_id, "organization_id": asset.organization_id},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_hardware_lifecycle_guards_and_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSoftwareInstallation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("installed", "Installed"),
                            ("suspended", "Suspended"),
                            ("uninstalled", "Uninstalled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("installed_version", models.CharField(blank=True, max_length=160)),
                ("installed_on", models.DateField(blank=True, null=True)),
                ("last_verified_on", models.DateField(blank=True, null=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_installation",
                        to="core.clientasset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_software_installations",
                        to="core.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_installations",
                        to="core.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_software_installations",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareLicense",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("subscription", "Subscription"), ("perpetual", "Perpetual"), ("trial", "Trial")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("seat_limit", models.PositiveIntegerField(default=1)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("renews_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "renewal_interval",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("multi_year", "Multi-year"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=240)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="software_license", to="core.entity"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_licenses",
                        to="core.catalogmodel",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_licenses",
                        to="core.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_licenses",
                        to="core.catalogproduct",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_software_licenses",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="software_licenses", to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareLicenseEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("details_updated", "Details updated"),
                            ("installation_linked", "Installation linked"),
                            ("installation_unlinked", "Installation unlinked"),
                            ("seat_assigned", "Seat assigned"),
                            ("seat_revoked", "Seat revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("seat_number", models.PositiveIntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.clientsoftwareinstallation",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="events", to="core.softwarelicense"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_events",
                        to="core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.personassociation"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_events",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SoftwareLicenseInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_links",
                        to="core.clientsoftwareinstallation",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installation_links",
                        to="core.softwarelicense",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_installations",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_installations",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareLicenseSeat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("seat_number", models.PositiveIntegerField()),
                ("assigned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_seats",
                        to="core.clientsoftwareinstallation",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="seats", to="core.softwarelicense"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_seats",
                        to="core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_seats",
                        to="core.personassociation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_license_seats",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="clientsoftwareinstallation",
            index=models.Index(fields=["tenant", "organization", "status"], name="core_swinstall_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="clientsoftwareinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["planned", "installed", "suspended", "uninstalled"])),
                name="software_installation_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarelicense",
            index=models.Index(
                fields=["tenant", "organization", "status", "renews_on"], name="core_swlicense_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("seat_limit__gte", 1)), name="software_license_seat_limit_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["subscription", "perpetual", "trial"])),
                name="software_license_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "suspended", "expired", "terminated"])),
                name="software_license_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("renewal_interval__in", ["none", "monthly", "annual", "multi_year"])),
                name="software_renewal_interval_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarelicenseevent",
            index=models.Index(
                fields=["tenant", "organization", "license", "occurred_at"], name="core_swlicevent_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicenseevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "created",
                            "details_updated",
                            "installation_linked",
                            "installation_unlinked",
                            "seat_assigned",
                            "seat_revoked",
                        ],
                    )
                ),
                name="software_license_event_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarelicenseinstallation",
            index=models.Index(fields=["tenant", "organization", "license"], name="core_swlicinst_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="softwarelicenseinstallation",
            constraint=models.UniqueConstraint(fields=("license", "installation"), name="unique_license_installation"),
        ),
        migrations.AddIndex(
            model_name="softwarelicenseseat",
            index=models.Index(
                fields=["tenant", "organization", "license", "revoked_at"], name="core_swseat_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicenseseat",
            constraint=models.UniqueConstraint(
                fields=("license", "seat_number"), name="unique_software_license_seat_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicenseseat",
            constraint=models.CheckConstraint(
                condition=models.Q(("seat_number__gte", 1)), name="software_license_seat_number_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarelicenseseat",
            constraint=models.CheckConstraint(
                condition=models.Q(("person__isnull", False), ("installation__isnull", False), _connector="OR"),
                name="software_seat_has_target",
            ),
        ),
        migrations.RunPython(seed_software_installations, migrations.RunPython.noop),
    ]
