# Generated by Django 5.2.17 on 2026-08-10 16:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_software_licensing_guards_and_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercialContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("support", "Support"),
                            ("lease", "Lease"),
                            ("subscription", "Subscription"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("reference", models.CharField(blank=True, max_length=240)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("renews_on", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("renewal_notice_days", models.PositiveSmallIntegerField(default=0)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commercial_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_contract",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_contracts",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_commercial_contracts",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commercial_contracts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="ContractCost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[
                            ("one_time", "One time"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=240)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="costs", to="core.commercialcontract"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_costs",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="contract_costs", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("label", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="commercialcontract",
            index=models.Index(
                fields=["tenant", "organization", "status", "renews_on"], name="core_contract_scope_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commercialcontract",
            index=models.Index(fields=["tenant", "organization", "provider"], name="core_contract_provider_idx"),
        ),
        migrations.AddConstraint(
            model_name="commercialcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["service", "support", "lease", "subscription", "other"])),
                name="commercial_contract_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "expired", "terminated"])),
                name="commercial_contract_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="commercialcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("renewal_notice_days__lte", 3650)),
                name="commercial_contract_notice_days_bounded",
            ),
        ),
        migrations.AddIndex(
            model_name="contractcost",
            index=models.Index(fields=["tenant", "organization", "contract"], name="core_contract_cost_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="contract_cost_amount_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="contract_cost_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("billing_interval__in", ["one_time", "monthly", "quarterly", "annual"])),
                name="contract_cost_interval_valid",
            ),
        ),
    ]
