# Generated by Django 5.2.17 on 2026-08-10 20:20

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_explicit_workspace_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentattachment',
            name='scan_engine',
            field=models.CharField(default='legacy-validation', max_length=120),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='scan_status',
            field=models.CharField(default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='storage_provider',
            field=models.CharField(default='django-default', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='documentattachment',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status', 'clean')), name='document_attachment_clean_only'),
        ),
    ]
