# Generated by Django 5.2.17 on 2026-08-11 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_person_identity_runtime_write_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('wireless_controller', 'Wireless controller'), ('access_point', 'Access point'), ('load_balancer', 'Load balancer'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('offline', 'Offline'), ('retired', 'Retired')], default='active', max_length=16)),
                ('rack_unit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rack_units', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('entity__display_name', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='NetworkRack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_count', models.PositiveSmallIntegerField(default=42)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
            ],
            options={
                'ordering': ('entity__display_name', 'entity_id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='entitylink',
            name='entity_link_type_supported',
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='link_type',
            field=models.CharField(choices=[('related_to', 'Related to'), ('connected_to', 'Connected to'), ('depends_on', 'Depends on'), ('managed_by', 'Managed by'), ('supplied_by', 'Supplied by'), ('manufactured_by', 'Manufactured by'), ('partnered_with', 'Partnered with'), ('located_at', 'Located at'), ('assigned_to', 'Assigned to'), ('references', 'References')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='entitylink',
            constraint=models.CheckConstraint(condition=models.Q(('link_type__in', ['related_to', 'connected_to', 'depends_on', 'managed_by', 'supplied_by', 'manufactured_by', 'partnered_with', 'located_at', 'assigned_to', 'references'])), name='entity_link_type_supported'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_device', to='core.entity'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='hardware_asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_device', to='core.clientasset'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='core.location'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='core.organization'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='core.site'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='networkrack',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_rack', to='core.entity'),
        ),
        migrations.AddField(
            model_name='networkrack',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_racks', to='core.location'),
        ),
        migrations.AddField(
            model_name='networkrack',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_racks', to='core.organization'),
        ),
        migrations.AddField(
            model_name='networkrack',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_racks', to='core.site'),
        ),
        migrations.AddField(
            model_name='networkrack',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_racks', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='core.networkrack'),
        ),
        migrations.AddIndex(
            model_name='networkrack',
            index=models.Index(fields=['tenant', 'organization', 'site'], name='core_netrack_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkrack',
            constraint=models.CheckConstraint(condition=models.Q(('unit_count__gte', 1), ('unit_count__lte', 100)), name='rack_units_valid'),
        ),
        migrations.AddConstraint(
            model_name='networkrack',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'retired'])), name='rack_status_valid'),
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['tenant', 'organization', 'role'], name='core_netdevice_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['rack', 'rack_unit'], name='core_netdevice_rack_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['router', 'switch', 'firewall', 'wireless_controller', 'access_point', 'load_balancer', 'other'])), name='network_device_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'offline', 'retired'])), name='network_device_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rack__isnull', True), ('rack_unit__isnull', True), ('rack_units', 1)), models.Q(('rack__isnull', False), ('rack_unit__isnull', False), ('rack_units__gte', 1), ('rack_units__lte', 100)), _connector='OR'), name='network_device_rack_placement_complete'),
        ),
        migrations.AddConstraint(
            model_name='networkdevice',
            constraint=models.CheckConstraint(condition=models.Q(('location__isnull', True), ('site__isnull', False), _connector='OR'), name='network_device_location_requires_site'),
        ),
    ]
