# Generated by Django 5.2.17 on 2026-08-11 07:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_network_inventory_guards_and_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkVLAN",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vlan_id", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_vlan", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_vlans",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_vlans", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("vlan_id", "entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="NetworkVRF",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("route_distinguisher", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_vrf", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_vrfs",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_vrfs", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="NetworkSubnet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cidr", models.CharField(max_length=49)),
                ("address_family", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_subnet", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_subnets",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_subnets", to="core.tenant"
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subnets",
                        to="core.networkvlan",
                    ),
                ),
                (
                    "vrf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subnets",
                        to="core.networkvrf",
                    ),
                ),
            ],
            options={
                "ordering": ("address_family", "cidr", "entity_id"),
            },
        ),
        migrations.AddIndex(
            model_name="networkvlan",
            index=models.Index(fields=["tenant", "organization", "vlan_id"], name="core_netvlan_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="networkvlan",
            constraint=models.CheckConstraint(
                condition=models.Q(("vlan_id__gte", 1), ("vlan_id__lte", 4094)), name="network_vlan_id_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="networkvlan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organization", "vlan_id"),
                name="network_vlan_id_unique_in_workspace",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="networkvrf",
            index=models.Index(fields=["tenant", "organization"], name="core_netvrf_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="networksubnet",
            index=models.Index(fields=["tenant", "organization", "vrf"], name="core_netsubnet_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="networksubnet",
            index=models.Index(fields=["tenant", "organization", "cidr"], name="core_netsubnet_cidr_idx"),
        ),
        migrations.AddConstraint(
            model_name="networksubnet",
            constraint=models.CheckConstraint(
                condition=models.Q(("address_family__in", (4, 6))), name="network_subnet_family_valid"
            ),
        ),
    ]
