# Generated by Django 5.2.17 on 2026-08-11 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_network_addressing_guards_and_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('lag', 'Link aggregation'), ('loopback', 'Loopback'), ('tunnel', 'Tunnel'), ('wireless', 'Wireless'), ('other', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('disabled', 'Disabled'), ('retired', 'Retired')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='core.networkdevice')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_interface', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_interfaces', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_interfaces', to='core.tenant')),
            ],
            options={
                'ordering': ('device__entity__display_name', 'entity__display_name', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='NetworkIPAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=45)),
                ('address_family', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('dhcp', 'DHCP'), ('deprecated', 'Deprecated')], max_length=24)),
                ('dns_name', models.CharField(blank=True, max_length=253)),
                ('description', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_ip_address', to='core.entity')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='core.networkinterface')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_ip_addresses', to='core.organization')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='core.networksubnet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_ip_addresses', to='core.tenant')),
            ],
            options={
                'ordering': ('address_family', 'address', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='NetworkMACAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=17)),
                ('description', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_mac_address', to='core.entity')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mac_addresses', to='core.networkinterface')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_mac_addresses', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_mac_addresses', to='core.tenant')),
            ],
            options={
                'ordering': ('address', 'entity_id'),
            },
        ),
        migrations.AddIndex(
            model_name='networkinterface',
            index=models.Index(fields=['tenant', 'organization', 'device'], name='core_netif_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='networkipaddress',
            index=models.Index(fields=['tenant', 'organization', 'subnet'], name='core_netip_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='networkipaddress',
            index=models.Index(fields=['tenant', 'organization', 'address'], name='core_netip_address_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkipaddress',
            constraint=models.CheckConstraint(condition=models.Q(('address_family__in', (4, 6))), name='network_ip_family_valid'),
        ),
        migrations.AddIndex(
            model_name='networkmacaddress',
            index=models.Index(fields=['tenant', 'organization', 'interface'], name='core_netmac_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkmacaddress',
            constraint=models.UniqueConstraint(fields=('tenant', 'organization', 'address'), name='network_mac_unique_in_workspace', nulls_distinct=False),
        ),
    ]
