# Generated by Django 5.2.17 on 2026-08-11 12:26

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_network_endpoint_guards_and_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=253)),
                ('description', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dns_zone', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dns_zones', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dns_zones', to='core.tenant')),
            ],
            options={
                'ordering': ('name', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=253)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('SRV', 'SRV'), ('CAA', 'CAA'), ('NS', 'NS'), ('PTR', 'PTR')], max_length=8)),
                ('value', models.TextField()),
                ('ttl', models.PositiveIntegerField(default=3600)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('port', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dns_record', to='core.entity')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dns_records', to='core.networkipaddress')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dns_records', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dns_records', to='core.tenant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.dnszone')),
            ],
            options={
                'ordering': ('zone__name', 'owner_name', 'record_type', 'value', 'entity_id'),
            },
        ),
        migrations.CreateModel(
            name='WirelessNetwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('corporate', 'Corporate'), ('guest', 'Guest'), ('iot', 'IoT'), ('voice', 'Voice'), ('other', 'Other')], max_length=16)),
                ('security', models.CharField(choices=[('open', 'Open'), ('owe', 'Enhanced open (OWE)'), ('wpa2_personal', 'WPA2 Personal'), ('wpa3_personal', 'WPA3 Personal'), ('wpa2_enterprise', 'WPA2 Enterprise'), ('wpa3_enterprise', 'WPA3 Enterprise'), ('mixed_personal', 'WPA2/WPA3 Personal'), ('mixed_enterprise', 'WPA2/WPA3 Enterprise')], max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('disabled', 'Disabled'), ('retired', 'Retired')], max_length=16)),
                ('hidden', models.BooleanField(default=False)),
                ('client_isolation', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wireless_network', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wireless_networks', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wireless_networks', to='core.site')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wireless_networks', to='core.networksubnet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wireless_networks', to='core.tenant')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wireless_networks', to='core.networkvlan')),
            ],
            options={
                'ordering': ('ssid', 'site_id', 'entity_id'),
            },
        ),
        migrations.AddIndex(
            model_name='dnszone',
            index=models.Index(fields=['tenant', 'organization', 'name'], name='core_dnszone_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='dnszone',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('tenant'), models.F('organization'), name='dns_zone_name_unique_in_workspace', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['tenant', 'organization', 'zone'], name='core_dnsrecord_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['zone', 'owner_name'], name='core_dnsrecord_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='dnsrecord',
            constraint=models.CheckConstraint(condition=models.Q(('record_type__in', ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'CAA', 'NS', 'PTR'])), name='dns_record_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='dnsrecord',
            constraint=models.CheckConstraint(condition=models.Q(('ttl__lte', 2147483647)), name='dns_record_ttl_valid'),
        ),
        migrations.AddConstraint(
            model_name='dnsrecord',
            constraint=models.UniqueConstraint(fields=('zone', 'owner_name', 'record_type', 'value', 'priority', 'weight', 'port'), name='dns_record_value_unique', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='wirelessnetwork',
            index=models.Index(fields=['tenant', 'organization', 'status'], name='core_wifi_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='wirelessnetwork',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['corporate', 'guest', 'iot', 'voice', 'other'])), name='wifi_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='wirelessnetwork',
            constraint=models.CheckConstraint(condition=models.Q(('security__in', ['open', 'owe', 'wpa2_personal', 'wpa3_personal', 'wpa2_enterprise', 'wpa3_enterprise', 'mixed_personal', 'mixed_enterprise'])), name='wifi_security_valid'),
        ),
        migrations.AddConstraint(
            model_name='wirelessnetwork',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'active', 'disabled', 'retired'])), name='wifi_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='wirelessnetwork',
            constraint=models.UniqueConstraint(fields=('tenant', 'organization', 'site', 'ssid'), name='wifi_ssid_unique_in_site', nulls_distinct=False),
        ),
    ]
