# Generated by Django 5.2.17 on 2026-08-11 13:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_wireless_dns_guards_and_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkCircuit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("service_identifier", models.CharField(max_length=240)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("internet", "Internet"),
                            ("wan", "WAN"),
                            ("mpls", "MPLS"),
                            ("dark_fiber", "Dark fiber"),
                            ("broadband", "Broadband"),
                            ("cellular", "Cellular"),
                            ("voice", "Voice"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("disconnected", "Disconnected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("bandwidth_down_mbps", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("bandwidth_up_mbps", models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ("installed_on", models.DateField(blank=True, null=True)),
                ("service_starts_on", models.DateField(blank=True, null=True)),
                ("review_on", models.DateField(blank=True, null=True)),
                ("planned_disconnect_on", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuits",
                        to="core.commercialcontract",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_circuit", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuits",
                        to="core.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_network_circuits",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="network_circuits", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "entity_id"),
            },
        ),
        migrations.CreateModel(
            name="NetworkCircuitHandoff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("side", models.CharField(choices=[("a", "A side"), ("z", "Z side")], max_length=1)),
                (
                    "media",
                    models.CharField(
                        choices=[
                            ("copper", "Copper"),
                            ("fiber", "Fiber"),
                            ("coax", "Coax"),
                            ("wireless", "Wireless"),
                            ("virtual", "Virtual"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("connector", models.CharField(blank=True, max_length=120)),
                ("provider_reference", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="handoffs", to="core.networkcircuit"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.networkdevice",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoff",
                        to="core.entity",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.networkinterface",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.organization",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.site",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="network_circuit_handoffs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("circuit__entity__display_name", "side", "entity__display_name", "entity_id"),
            },
        ),
        migrations.AddIndex(
            model_name="networkcircuit",
            index=models.Index(fields=["tenant", "organization", "status"], name="core_circuit_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="networkcircuit",
            index=models.Index(fields=["tenant", "organization", "provider"], name="core_circuit_provider_idx"),
        ),
        migrations.AddIndex(
            model_name="networkcircuit",
            index=models.Index(fields=["tenant", "organization", "review_on"], name="core_circuit_review_idx"),
        ),
        migrations.AddConstraint(
            model_name="networkcircuit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["internet", "wan", "mpls", "dark_fiber", "broadband", "cellular", "voice", "other"])
                ),
                name="circuit_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuit",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ordered", "provisioning", "active", "suspended", "disconnected"])),
                name="circuit_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bandwidth_down_mbps__isnull", True), ("bandwidth_down_mbps__gt", 0), _connector="OR"
                ),
                name="circuit_down_bandwidth_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuit",
            constraint=models.CheckConstraint(
                condition=models.Q(("bandwidth_up_mbps__isnull", True), ("bandwidth_up_mbps__gt", 0), _connector="OR"),
                name="circuit_up_bandwidth_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organization", "provider", "service_identifier"),
                name="circuit_service_id_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="networkcircuithandoff",
            index=models.Index(fields=["tenant", "organization", "circuit"], name="core_handoff_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="networkcircuithandoff",
            index=models.Index(fields=["tenant", "organization", "interface"], name="core_handoff_interface_idx"),
        ),
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.CheckConstraint(condition=models.Q(("side__in", ["a", "z"])), name="handoff_side_valid"),
        ),
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.CheckConstraint(
                condition=models.Q(("media__in", ["copper", "fiber", "coax", "wireless", "virtual", "other"])),
                name="handoff_media_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.CheckConstraint(
                condition=models.Q(("location__isnull", True), ("site__isnull", False), _connector="OR"),
                name="handoff_location_requires_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.CheckConstraint(
                condition=models.Q(("interface__isnull", True), ("device__isnull", False), _connector="OR"),
                name="handoff_interface_requires_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.UniqueConstraint(fields=("circuit", "side", "entity"), name="handoff_identity_unique"),
        ),
    ]
