# Generated by Django 5.2.17 on 2026-08-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_network_circuits_and_handoffs"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="networkcircuithandoff",
            constraint=models.UniqueConstraint(
                condition=models.Q(("interface__isnull", False)), fields=("interface",), name="handoff_interface_unique"
            ),
        ),
    ]
