# Generated by Django 5.2.17 on 2026-08-11 14:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_network_circuit_guards_and_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetBoxReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("dcim.rack", "Rack"),
                            ("dcim.device", "Device"),
                            ("dcim.macaddress", "MAC address"),
                            ("ipam.vlan", "VLAN"),
                            ("ipam.prefix", "Prefix"),
                            ("ipam.ipaddress", "IP address"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("observed_fingerprint", models.CharField(blank=True, max_length=64)),
                ("last_observed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="netbox_references", to="core.entity"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_references",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="netbox_references", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="netbox_references",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("object_type", "object_id", "id"),
                "indexes": [
                    models.Index(fields=["tenant", "organization", "archived_at"], name="core_netbox_scope_idx"),
                    models.Index(fields=["workspace", "object_type", "object_id"], name="core_netbox_remote_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "object_type__in",
                                [
                                    "dcim.rack",
                                    "dcim.device",
                                    "dcim.macaddress",
                                    "ipam.vlan",
                                    "ipam.prefix",
                                    "ipam.ipaddress",
                                ],
                            )
                        ),
                        name="netbox_type_valid",
                    ),
                    models.CheckConstraint(condition=models.Q(("object_id__gte", 1)), name="netbox_object_id_positive"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_fingerprint", ""),
                            ("observed_fingerprint__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="netbox_fingerprint_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("workspace", "entity"),
                        name="netbox_active_entity_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("workspace", "object_type", "object_id"),
                        name="netbox_active_remote_unique",
                    ),
                ],
            },
        ),
    ]
