# Generated by Django 5.2.17 on 2026-08-11 16:37
# ruff: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


def preserve_legacy_assignments(apps, schema_editor):
    NetworkDevice = apps.get_model("core", "NetworkDevice")
    NetworkIPAddress = apps.get_model("core", "NetworkIPAddress")
    NetworkMACAddress = apps.get_model("core", "NetworkMACAddress")

    NetworkDevice.objects.filter(hardware_asset_id__isnull=True).update(legacy_unbacked=True)
    for model in (NetworkIPAddress, NetworkMACAddress):
        records = list(
            model.objects.filter(interface__device__hardware_asset_id__isnull=False).select_related(
                "interface__device"
            )
        )
        for record in records:
            record.hardware_asset_id = record.interface.device.hardware_asset_id
        model.objects.bulk_update(records, ("hardware_asset",), batch_size=500)


def restore_legacy_shape(apps, schema_editor):
    apps.get_model("core", "NetworkDevice").objects.update(legacy_unbacked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_netbox_reference_guards_and_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='legacy_unbacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkipaddress',
            name='hardware_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_ip_addresses', to='core.clientasset'),
        ),
        migrations.AddField(
            model_name='networkmacaddress',
            name='hardware_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_mac_addresses', to='core.clientasset'),
        ),
        migrations.RunPython(preserve_legacy_assignments, restore_legacy_shape),
        migrations.AddIndex(
            model_name='networkipaddress',
            index=models.Index(fields=['tenant', 'organization', 'hardware_asset'], name='core_netip_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='networkmacaddress',
            index=models.Index(fields=['tenant', 'organization', 'hardware_asset'], name='core_netmac_asset_idx'),
        ),
    ]
