# Generated by Django 5.2.17 on 2026-08-11 23:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_refresh_publication_control_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=120)),
                ('subject_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='core.tenant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OutboxDeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer', models.CharField(max_length=80)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_delivery_receipts', to='core.tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipts', to='core.outboxevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['tenant', 'state', 'available_at', 'created_at'], name='core_outbox_tenant__ed96a6_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['tenant', 'topic', 'created_at'], name='core_outbox_tenant__7fe3d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_tenant_outbox_key'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 100)), name='outbox_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('locked_at__isnull', True), ('state', 'delivered')), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', True), ('state__in', ['pending', 'dead_letter'])), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', False), ('state', 'processing')), _connector='OR'), name='outbox_state_timestamps_consistent'),
        ),
        migrations.AddIndex(
            model_name='outboxdeliveryreceipt',
            index=models.Index(fields=['tenant', 'processed_at'], name='core_outbox_tenant__e0a641_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxdeliveryreceipt',
            constraint=models.UniqueConstraint(fields=('event', 'consumer'), name='unique_outbox_consumer_receipt'),
        ),
    ]
