# Generated by Django 5.2.17 on 2026-08-12 01:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_outbox_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.CharField(choices=[('msp', 'MSP'), ('client_portal', 'Client portal')], max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_notifications', to='core.outboxevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_notifications', to='core.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_notifications', to='core.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'recipient', 'surface', 'read_at', 'created_at'], name='core_inbox_recipient_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'recipient', 'surface'), name='unique_event_recipient_surface'), models.CheckConstraint(condition=models.Q(('surface__in', ['msp', 'client_portal'])), name='inbox_notification_surface_valid')],
            },
        ),
    ]
