# Generated by Django 5.2.17 on 2026-08-12 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_inbox_notification_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.CharField(choices=[('msp', 'MSP'), ('client_portal', 'Client portal')], max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('suppressed', 'Suppressed'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='core.inboxnotification')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_email_deliveries', to='core.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_email_deliveries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_email_deliveries', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'state', 'available_at', 'created_at'], name='core_notice_email_due_idx'), models.Index(fields=['tenant', 'recipient', 'surface', 'created_at'], name='core_notice_email_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__lte', 100)), name='notification_email_attempts_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('locked_at__isnull', True), ('state', 'delivered')), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', True), ('state__in', ['pending', 'suppressed', 'dead_letter'])), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', False), ('state', 'processing')), _connector='OR'), name='notification_email_state_timestamps_consistent')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.CharField(choices=[('msp', 'MSP'), ('client_portal', 'Client portal')], max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('invitation_events', models.BooleanField(default=True)),
                ('publication_events', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_preferences', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'surface'), name='unique_notification_preference_surface'), models.CheckConstraint(condition=models.Q(('surface__in', ['msp', 'client_portal'])), name='notification_preference_surface_valid')],
            },
        ),
    ]
