# Generated by Django 5.2.17 on 2026-08-12 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_notification_email_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationemaildelivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationemaildelivery',
            name='retry_generation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='daily_digest_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='delivery_mode',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly digest'), ('daily', 'Daily digest')], default='immediate', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_mode__in', ('immediate', 'hourly', 'daily'))), name='notification_preference_delivery_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(condition=models.Q(('daily_digest_hour__lte', 23)), name='notification_preference_daily_hour_valid'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quiet_end__isnull', True), ('quiet_start__isnull', True)), models.Q(('quiet_end__isnull', False), ('quiet_start__isnull', False), models.Q(('quiet_start', models.F('quiet_end')), _negated=True)), _connector='OR'), name='notification_preference_quiet_window_valid'),
        ),
    ]
