# Generated by Django 5.2.17 on 2026-08-12 04:10

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_vlan_numbers(apps, schema_editor):
    NetworkSubnet = apps.get_model("core", "NetworkSubnet")
    for record in NetworkSubnet.objects.select_related("vlan").filter(vlan__isnull=False, vlan_number__isnull=True):
        record.vlan_number = record.vlan.vlan_id
        record.save(update_fields=("vlan_number",))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_notification_delivery_scheduling_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksubnet',
            name='assignable_end',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='assignable_start',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='core.location'),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='primary_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='secondary_dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='use_full_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networksubnet',
            name='vlan_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_legacy_vlan_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='networksubnet',
            constraint=models.CheckConstraint(condition=models.Q(('vlan_number__isnull', True), models.Q(('vlan_number__gte', 1), ('vlan_number__lte', 4094)), _connector='OR'), name='network_record_vlan_valid'),
        ),
        migrations.AddConstraint(
            model_name='networksubnet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignable_end__isnull', True), ('assignable_start__isnull', True), ('use_full_range', True)), models.Q(('assignable_end__isnull', False), ('assignable_start__isnull', False), ('use_full_range', False)), _connector='OR'), name='network_record_range_mode_valid'),
        ),
    ]
