# Generated by Django 5.2.17 on 2026-08-12 07:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_network_record_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('topics', models.JSONField(default=list)),
                ('secret_envelope', models.JSONField()),
                ('secret_prefix', models.CharField(max_length=16)),
                ('secret_generation', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='core.tenant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WebhookInboundReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=120)),
                ('body_sha256', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_receipts', to='core.webhookendpoint')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_inbound_receipts', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_inbound_receipts', to='core.tenant')),
            ],
            options={
                'ordering': ('-received_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WebhookOutboundDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_deliveries', to='core.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='core.outboxevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_outbound_deliveries', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_outbound_deliveries', to='core.tenant')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['tenant', 'organization', 'direction', 'active'], name='core_webhoo_tenant__4ba657_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'outbound'), ('url__gt', '')), models.Q(('direction', 'inbound'), ('url', '')), _connector='OR'), name='webhook_direction_url_valid'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('secret_generation__gte', 1)), name='webhook_secret_generation_valid'),
        ),
        migrations.AddIndex(
            model_name='webhookinboundreceipt',
            index=models.Index(fields=['tenant', 'organization', 'received_at'], name='core_webhoo_tenant__6f0cb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookinboundreceipt',
            constraint=models.UniqueConstraint(fields=('endpoint', 'delivery_id'), name='unique_inbound_webhook_delivery'),
        ),
        migrations.AddIndex(
            model_name='webhookoutbounddelivery',
            index=models.Index(fields=['tenant', 'state', 'available_at', 'created_at'], name='core_webhoo_tenant__2e3f94_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookoutbounddelivery',
            index=models.Index(fields=['tenant', 'organization', 'created_at'], name='core_webhoo_tenant__cd97d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookoutbounddelivery',
            constraint=models.UniqueConstraint(fields=('endpoint', 'event'), name='unique_webhook_endpoint_event'),
        ),
        migrations.AddConstraint(
            model_name='webhookoutbounddelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 20)), name='webhook_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='webhookoutbounddelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('locked_at__isnull', True), ('state', 'delivered')), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', True), ('state__in', ['pending', 'dead_letter'])), models.Q(('delivered_at__isnull', True), ('locked_at__isnull', False), ('state', 'processing')), _connector='OR'), name='webhook_delivery_state_valid'),
        ),
    ]
