# Generated by Django 5.2.17 on 2026-08-12 08:44

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_webhook_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('netbox', 'NetBox')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('secret_envelope', models.JSONField()),
                ('secret_generation', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('next_sync_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_integration_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_connections', to='core.workspace')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_type', models.CharField(max_length=64)),
                ('remote_id', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_observations', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_observations', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_observations', to='core.workspace')),
            ],
            options={
                'ordering': ('remote_type', 'remote_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationConflict',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_type', models.CharField(max_length=64)),
                ('remote_id', models.CharField(max_length=160)),
                ('difference', models.CharField(max_length=32)),
                ('remote_fingerprint', models.CharField(blank=True, max_length=64)),
                ('local_fingerprint', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('keep_local', 'Keep local'), ('accept_remote', 'Accept remote identity'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('local_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_conflicts', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_conflicts', to='core.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_integration_conflicts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_conflicts', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_conflicts', to='core.workspace')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='core.integrationconnection')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='core.integrationobservation')),
            ],
            options={
                'ordering': ('status', 'remote_type', 'remote_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('trigger', models.CharField(default='scheduled', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('cursor_before', models.CharField(blank=True, max_length=500)),
                ('cursor_after', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('result_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_jobs', to='core.integrationconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_sync_jobs', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_integration_sync_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_sync_jobs', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_sync_jobs', to='core.workspace')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='integrationobservation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.integrationsyncjob'),
        ),
        migrations.CreateModel(
            name='IntegrationLogEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_events', to='core.integrationconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_log_events', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_log_events', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_log_events', to='core.workspace')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_events', to='core.integrationsyncjob')),
            ],
            options={
                'ordering': ('-occurred_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GitExportBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_manifest', models.JSONField()),
                ('content_digest', models.CharField(max_length=64)),
                ('artifact', models.FileField(max_length=500, upload_to=apps.core.models.git_export_upload_to)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='git_export_bundles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='git_export_bundles', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='git_export_bundles', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='git_export_bundles', to='core.workspace')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='core_gitexport_scope_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['tenant', 'organization', 'active'], name='core_intconn_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconnection',
            index=models.Index(fields=['tenant', 'active', 'next_sync_at'], name='core_intconn_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['netbox'])), name='integration_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.CheckConstraint(condition=models.Q(('secret_generation__gte', 1)), name='integration_secret_generation_valid'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.CheckConstraint(condition=models.Q(('sync_interval_minutes__gte', 5), ('sync_interval_minutes__lte', 10080)), name='integration_sync_interval_bounded'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='integration_connection_name_unique'),
        ),
        migrations.AddIndex(
            model_name='integrationconflict',
            index=models.Index(fields=['workspace', 'status'], name='core_intconf_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconflict',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'keep_local', 'accept_remote', 'ignored'])), name='integration_conflict_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='integrationconflict',
            constraint=models.CheckConstraint(condition=models.Q(('difference__in', ('unmatched', 'changed'))), name='integration_conflict_difference_valid'),
        ),
        migrations.AddConstraint(
            model_name='integrationconflict',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('remote_fingerprint', ''), ('remote_fingerprint__regex', '^[0-9a-f]{64}$'), _connector='OR'), models.Q(('local_fingerprint', ''), ('local_fingerprint__regex', '^[0-9a-f]{64}$'), _connector='OR')), name='integration_conflict_digests_valid'),
        ),
        migrations.AddConstraint(
            model_name='integrationconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('connection', 'remote_type', 'remote_id'), name='integration_open_conflict_unique'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncjob',
            index=models.Index(fields=['tenant', 'state', 'available_at'], name='core_intjob_due_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsyncjob',
            index=models.Index(fields=['workspace', 'created_at'], name='core_intjob_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationsyncjob',
            constraint=models.UniqueConstraint(fields=('connection', 'idempotency_key'), name='integration_job_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='integrationsyncjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 8)), name='integration_job_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='integrationsyncjob',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ('scheduled', 'manual'))), name='integration_job_trigger_valid'),
        ),
        migrations.AddIndex(
            model_name='integrationobservation',
            index=models.Index(fields=['workspace', 'remote_type', 'remote_id'], name='core_intobs_remote_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationobservation',
            constraint=models.UniqueConstraint(fields=('job', 'remote_type', 'remote_id'), name='integration_observation_unique'),
        ),
        migrations.AddConstraint(
            model_name='integrationobservation',
            constraint=models.CheckConstraint(condition=models.Q(('fingerprint__regex', '^[0-9a-f]{64}$')), name='integration_observation_digest_valid'),
        ),
        migrations.AddIndex(
            model_name='integrationlogevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='core_intlog_retention_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationlogevent',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ('info', 'warning', 'error'))), name='integration_log_level_valid'),
        ),
    ]
