# Generated by Django 5.2.17 on 2026-08-12 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_integration_runtime_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCatalogRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('version_label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('content_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_compliance_catalog_revisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_revisions', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_revisions', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_revisions', to='core.workspace')),
            ],
            options={
                'ordering': ('-revision_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_record', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_controls', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_controls', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_controls', to='core.workspace')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceControlRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('identifier', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('guidance', models.TextField(blank=True)),
                ('content_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.compliancecontrol')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_compliance_control_revisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_revisions', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_revisions', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_control_revisions', to='core.workspace')),
            ],
            options={
                'ordering': ('-revision_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_entries', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_entries', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_catalog_entries', to='core.workspace')),
                ('catalog_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.compliancecatalogrevision')),
                ('control_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_entries', to='core.compliancecontrolrevision')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_frameworks', to='core.compliancecatalogrevision')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_framework_record', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_frameworks', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_frameworks', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_frameworks', to='core.workspace')),
            ],
            options={
                'ordering': ('entity__display_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='core.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancecatalogrevision',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.complianceframework'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrolrevision',
            index=models.Index(fields=['workspace', 'created_at'], name='core_compctlrev_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrolrevision',
            constraint=models.UniqueConstraint(fields=('control', 'revision_number'), name='compliance_control_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrolrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='compliance_control_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrolrevision',
            constraint=models.CheckConstraint(condition=models.Q(('content_digest__regex', '^[0-9a-f]{64}$')), name='compliance_control_digest_valid'),
        ),
        migrations.AddIndex(
            model_name='compliancecatalogentry',
            index=models.Index(fields=['workspace', 'catalog_revision'], name='core_compentry_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancecatalogentry',
            constraint=models.UniqueConstraint(fields=('catalog_revision', 'position'), name='compliance_catalog_entry_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='compliancecatalogentry',
            constraint=models.UniqueConstraint(fields=('catalog_revision', 'control_revision'), name='compliance_catalog_entry_revision_unique'),
        ),
        migrations.AddIndex(
            model_name='complianceframework',
            index=models.Index(fields=['workspace', 'created_at'], name='core_compfw_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['workspace', 'framework'], name='core_compctl_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecatalogrevision',
            index=models.Index(fields=['workspace', 'created_at'], name='core_compcat_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancecatalogrevision',
            constraint=models.UniqueConstraint(fields=('framework', 'revision_number'), name='compliance_catalog_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='compliancecatalogrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='compliance_catalog_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='compliancecatalogrevision',
            constraint=models.CheckConstraint(condition=models.Q(('content_digest__regex', '^[0-9a-f]{64}$')), name='compliance_catalog_digest_valid'),
        ),
    ]
