# Generated by Django 5.2.17 on 2026-08-12 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_compliance_catalog_guards_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceControlAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicability', models.CharField(choices=[('unassessed', 'Not evaluated'), ('applicable', 'Applicable'), ('not_applicable', 'Not applicable')], default='unassessed', max_length=20)),
                ('implementation_status', models.CharField(choices=[('not_started', 'Not started'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('not_implemented', 'Not implemented')], default='not_started', max_length=24)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.compliancecontrol')),
                ('control_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.compliancecontrolrevision')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.complianceframework')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignments', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_compliance_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignments', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignments', to='core.workspace')),
            ],
            options={
                'ordering': ('framework_id', 'control_id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceAssignmentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicability', models.CharField(choices=[('unassessed', 'Not evaluated'), ('applicable', 'Applicable'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('implementation_status', models.CharField(choices=[('not_started', 'Not started'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('not_implemented', 'Not implemented')], max_length=24)),
                ('decision', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('control_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_reviews', to='core.compliancecontrolrevision')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignment_reviews', to='core.organization')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignment_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignment_reviews', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_assignment_reviews', to='core.workspace')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.compliancecontrolassignment')),
            ],
            options={
                'ordering': ('-reviewed_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='compliancecontrolassignment',
            index=models.Index(fields=['workspace', 'implementation_status'], name='core_compassign_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancecontrolassignment',
            constraint=models.UniqueConstraint(fields=('workspace', 'control'), name='compliance_assignment_unique'),
        ),
        migrations.AddIndex(
            model_name='complianceassignmentreview',
            index=models.Index(fields=['workspace', 'reviewed_at'], name='core_compreview_scope_idx'),
        ),
    ]
