# Generated by Django 5.2.17 on 2026-08-12 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_compliance_assignment_guards_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Recorded note'), ('url', 'External URL'), ('entity', 'TekDocs entity')], max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('collection_start', models.DateField(blank=True, null=True)),
                ('collection_end', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_compliance_evidence', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence', to='core.organization')),
                ('source_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_sources', to='core.entity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence', to='core.workspace')),
            ],
            options={
                'ordering': ('entity__display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='core.compliancecontrolassignment')),
                ('control_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='core.compliancecontrolrevision')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_links', to='core.complianceevidence')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_compliance_evidence', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_links', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_links', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_links', to='core.workspace')),
            ],
            options={
                'ordering': ('linked_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidenceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=16)),
                ('decision', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.complianceevidence')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_reviews', to='core.organization')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_reviews', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_evidence_reviews', to='core.workspace')),
            ],
            options={
                'ordering': ('-reviewed_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='complianceevidence',
            index=models.Index(fields=['workspace', 'kind'], name='core_compevidence_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceevidencelink',
            index=models.Index(fields=['workspace', 'linked_at'], name='core_compevlink_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidencelink',
            constraint=models.UniqueConstraint(fields=('assignment', 'evidence', 'control_revision'), name='compliance_evidence_link_unique'),
        ),
        migrations.AddIndex(
            model_name='complianceevidencereview',
            index=models.Index(fields=['workspace', 'reviewed_at'], name='core_compevreview_scope_idx'),
        ),
    ]
