# Generated by Django 5.2.17 on 2026-08-12 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_compliance_evidence_guards_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('accepted', 'Accepted'), ('closed', 'Closed')], max_length=16)),
                ('treatment', models.CharField(choices=[('mitigate', 'Mitigate'), ('avoid', 'Avoid'), ('transfer', 'Transfer'), ('accept', 'Accept')], max_length=16)),
                ('treatment_plan', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_compliance_risks', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='core.compliancecontrolassignment')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risk', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risks', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_compliance_risks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risks', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risks', to='core.workspace')),
            ],
            options={
                'ordering': ('-updated_at', 'entity__display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceRiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('monitoring', 'Monitoring'), ('accepted', 'Accepted'), ('closed', 'Closed')], max_length=16)),
                ('treatment', models.CharField(choices=[('mitigate', 'Mitigate'), ('avoid', 'Avoid'), ('transfer', 'Transfer'), ('accept', 'Accept')], max_length=16)),
                ('treatment_plan', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('control_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='core.compliancecontrolrevision')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risk_events', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risk_events', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.compliancerisk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risk_events', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_risk_events', to='core.workspace')),
            ],
            options={
                'ordering': ('-recorded_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='compliancerisk',
            index=models.Index(fields=['workspace', 'status', 'due_date'], name='core_comprisk_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='compliancerisk',
            constraint=models.CheckConstraint(condition=models.Q(('likelihood__gte', 1), ('likelihood__lte', 5)), name='risk_likelihood_1_5'),
        ),
        migrations.AddConstraint(
            model_name='compliancerisk',
            constraint=models.CheckConstraint(condition=models.Q(('impact__gte', 1), ('impact__lte', 5)), name='risk_impact_1_5'),
        ),
        migrations.AddIndex(
            model_name='complianceriskevent',
            index=models.Index(fields=['workspace', 'recorded_at'], name='core_compriskev_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='complianceriskevent',
            constraint=models.CheckConstraint(condition=models.Q(('likelihood__gte', 1), ('likelihood__lte', 5)), name='risk_event_likelihood_1_5'),
        ),
        migrations.AddConstraint(
            model_name='complianceriskevent',
            constraint=models.CheckConstraint(condition=models.Q(('impact__gte', 1), ('impact__lte', 5)), name='risk_event_impact_1_5'),
        ),
    ]
