# Generated by Django 5.2.17 on 2026-08-12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_compliance_risk_guards_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceEvidenceBundle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=500)),
                ("audience", models.CharField(max_length=32)),
                ("manifest", models.JSONField()),
                ("content_digest", models.CharField(max_length=64)),
                ("signature", models.TextField()),
                ("signature_algorithm", models.CharField(default="Ed25519", max_length=20)),
                ("public_key", models.TextField()),
                ("key_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_compliance_evidence_bundles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_evidence_bundle",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_evidence_bundles",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_evidence_bundles",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_evidence_bundles",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="complianceevidencebundle",
            index=models.Index(fields=["workspace", "created_at"], name="core_compbundle_scope_idx"),
        ),
    ]
