# Generated by Django 5.2.17 on 2026-08-12
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_deadline_permissions"),
        ("core", "0089_compliance_bundle_guards_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(choices=[("compliance", "Compliance"), ("inventory", "Inventory"), ("domain", "Domain")], max_length=20)),
                ("kind", models.CharField(max_length=48)),
                ("title", models.CharField(max_length=240)),
                ("due_on", models.DateField()),
                ("lead_days", models.PositiveSmallIntegerField(default=30)),
                ("recurrence", models.CharField(choices=[("none", "Does not repeat"), ("annual", "Annual")], default="none", max_length=16)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_reminder_schedules", to=settings.AUTH_USER_MODEL)),
                ("entity", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reminder_schedule", to="core.entity")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reminder_schedules", to="core.organization")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="owned_reminder_schedules", to=settings.AUTH_USER_MODEL)),
                ("source_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reminder_schedules", to="core.entity")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reminder_schedules", to="core.tenant")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reminder_schedules", to="core.workspace")),
            ],
            options={"ordering": ("due_on", "title", "id")},
        ),
        migrations.AddIndex(model_name="reminderschedule", index=models.Index(fields=["workspace", "active", "due_on"], name="core_reminder_due_idx")),
        migrations.AddConstraint(model_name="reminderschedule", constraint=models.CheckConstraint(condition=models.Q(("lead_days__lte", 3650)), name="reminder_lead_days_bounded")),
        migrations.AddConstraint(model_name="reminderschedule", constraint=models.UniqueConstraint(fields=("workspace", "source_entity", "kind", "due_on"), name="reminder_source_kind_due_unique")),
    ]
