# Generated by Django 5.2.17 on 2026-08-12
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_domain_permissions"),
        ("core", "0091_reminder_guards_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredDomain",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ascii_name", models.CharField(max_length=253)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("renewal_mode", models.CharField(choices=[("manual", "Manual"), ("auto", "Automatic"), ("external", "Managed externally")], max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("pending", "Pending"), ("expired", "Expired"), ("transferred", "Transferred")], max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_registered_domains", to=settings.AUTH_USER_MODEL)),
                ("entity", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="registered_domain", to="core.entity")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="registered_domains", to="core.organization")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="owned_registered_domains", to=settings.AUTH_USER_MODEL)),
                ("registrar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="registrar_domains", to="core.organization")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="registered_domains", to="core.tenant")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="registered_domains", to="core.workspace")),
            ],
            options={"ordering": ("ascii_name", "id")},
        ),
        migrations.AddIndex(model_name="registereddomain", index=models.Index(fields=["workspace", "status", "expiration_date"], name="core_domain_scope_idx")),
        migrations.AddConstraint(model_name="registereddomain", constraint=models.UniqueConstraint(condition=models.Q(("archived_at__isnull", True)), fields=("workspace", "ascii_name"), name="registered_domain_active_name_unique")),
    ]
