# Generated by Django 5.2.17 on 2026-08-12 20:11
# ruff: noqa: E501

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_registered_domain_guards_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedHostname',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ascii_name', models.CharField(max_length=253)),
                ('provenance', models.CharField(choices=[('entered', 'Entered'), ('discovered', 'Discovered')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_managed_hostnames', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostnames', to='core.registereddomain')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_hostname', to='core.entity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_hostnames', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.managedhostname')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_hostnames', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_hostnames', to='core.workspace')),
            ],
            options={
                'ordering': ('ascii_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DomainDNSObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=16)),
                ('value', models.CharField(max_length=1024)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('provenance', models.CharField(choices=[('entered', 'Entered'), ('discovered', 'Discovered')], max_length=16)),
                ('source', models.CharField(max_length=120)),
                ('content_digest', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_dns_observations', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_domain_dns_observations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_dns_observations', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_dns_observations', to='core.workspace')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dns_observations', to='core.managedhostname')),
            ],
            options={
                'ordering': ('-observed_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='managedhostname',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('workspace', 'ascii_name'), name='managed_hostname_active_name_unique'),
        ),
        migrations.AddIndex(
            model_name='domaindnsobservation',
            index=models.Index(fields=['workspace', 'hostname', 'observed_at'], name='core_domain_dns_obs_idx'),
        ),
        migrations.AddConstraint(
            model_name='domaindnsobservation',
            constraint=models.UniqueConstraint(fields=('hostname', 'record_type', 'content_digest', 'observed_at'), name='domain_dns_observation_unique'),
        ),
    ]
