# Generated by Django 5.2.17 on 2026-08-12 20:14
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_domain_hierarchy_guards_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddomain',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='observed_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='review_state',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('current', 'Current'), ('stale', 'Stale'), ('conflict', 'Conflicting source')], default='unreviewed', max_length=16),
        ),
        migrations.CreateModel(
            name='DomainReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('current', 'Current'), ('stale', 'Stale'), ('conflict', 'Conflicting source')], max_length=16)),
                ('entered_expiration_date', models.DateField(blank=True, null=True)),
                ('observed_expiration_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='core.registereddomain')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_review_events', to='core.organization')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_review_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_review_events', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_review_events', to='core.workspace')),
            ],
            options={
                'ordering': ('-reviewed_at', 'id'),
            },
        ),
    ]
