# Generated by Django 5.2.17 on 2026-08-12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_observation_domains(apps, schema_editor):  # type: ignore[no-untyped-def]
    observation = apps.get_model("core", "DomainDNSObservation")
    for row in observation.objects.select_related("hostname").all().iterator():
        row.domain_id = row.hostname.domain_id
        row.save(update_fields=("domain",))


def remove_apex_observations(apps, schema_editor):  # type: ignore[no-untyped-def]
    schema_editor.execute("ALTER TABLE core_domaindnsobservation DISABLE TRIGGER core_domain_dns_observation_guard")
    apps.get_model("core", "DomainDNSObservation").objects.filter(hostname__isnull=True).delete()
    schema_editor.execute("ALTER TABLE core_domaindnsobservation ENABLE TRIGGER core_domain_dns_observation_guard")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_domain_review_guards_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registereddomain",
            name="monitor_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="registereddomain",
            name="monitor_interval_hours",
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="registereddomain",
            name="monitor_state",
            field=models.CharField(
                choices=[
                    ("never", "Never checked"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("current", "Current"),
                    ("failed", "Check failed"),
                ],
                default="never",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="registereddomain",
            name="monitoring_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registereddomain",
            name="next_monitor_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="registereddomain",
            name="last_monitor_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domainreviewevent",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="domain_review_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="domaindnsobservation",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_domain_dns_observations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="domaindnsobservation",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dns_observations",
                to="core.registereddomain",
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE core_domaindnsobservation NO FORCE ROW LEVEL SECURITY; "
            "ALTER TABLE core_domaindnsobservation DISABLE ROW LEVEL SECURITY;",
            migrations.RunSQL.noop,
        ),
        migrations.RunPython(populate_observation_domains, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="domaindnsobservation",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dns_observations",
                to="core.registereddomain",
            ),
        ),
        migrations.AlterField(
            model_name="domaindnsobservation",
            name="hostname",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dns_observations",
                to="core.managedhostname",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, remove_apex_observations),
        migrations.RemoveConstraint(
            model_name="domaindnsobservation",
            name="domain_dns_observation_unique",
        ),
        migrations.AddConstraint(
            model_name="domaindnsobservation",
            constraint=models.UniqueConstraint(
                fields=("domain", "hostname", "record_type", "content_digest", "observed_at"),
                name="domain_dns_observation_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE core_domaindnsobservation ENABLE ROW LEVEL SECURITY; "
            "ALTER TABLE core_domaindnsobservation FORCE ROW LEVEL SECURITY;",
            "ALTER TABLE core_domaindnsobservation NO FORCE ROW LEVEL SECURITY; "
            "ALTER TABLE core_domaindnsobservation DISABLE ROW LEVEL SECURITY;",
        ),
        migrations.CreateModel(
            name="DomainMonitorRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "trigger",
                    models.CharField(choices=[("manual", "Manual"), ("scheduled", "Scheduled")], max_length=16),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("rdap_source", models.CharField(blank=True, max_length=120)),
                ("rdap_digest", models.CharField(blank=True, max_length=64)),
                ("observed_expiration_date", models.DateField(blank=True, null=True)),
                ("observed_registrar", models.CharField(blank=True, max_length=240)),
                ("dns_source", models.CharField(blank=True, max_length=120)),
                ("dns_digest", models.CharField(blank=True, max_length=64)),
                ("dnssec_validated", models.BooleanField(blank=True, null=True)),
                ("dns_record_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_runs",
                        to="core.registereddomain",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_runs",
                        to="core.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_domain_monitor_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_runs",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_runs",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="domainmonitorrun",
            index=models.Index(fields=["workspace", "state", "available_at"], name="core_domainrun_due_idx"),
        ),
        migrations.AddIndex(
            model_name="domainmonitorrun",
            index=models.Index(fields=["domain", "created_at"], name="core_domainrun_history_idx"),
        ),
        migrations.AddConstraint(
            model_name="domainmonitorrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", 5)), name="domain_monitor_attempts_bounded"
            ),
        ),
        migrations.AddConstraint(
            model_name="domainmonitorrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("trigger__in", ("manual", "scheduled"))), name="domain_monitor_trigger_valid"
            ),
        ),
        migrations.CreateModel(
            name="DomainMonitorAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("expiration_due", "Expiration due"),
                            ("expiration_changed", "Expiration changed"),
                            ("dns_changed", "DNS changed"),
                            ("collection_failed", "Collection failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("observed_expiration_date", models.DateField(blank=True, null=True)),
                ("prior_expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_alerts",
                        to="core.registereddomain",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_alerts",
                        to="core.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="alerts", to="core.domainmonitorrun"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_alerts",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_monitor_alerts",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("-created_at", "id")},
        ),
        migrations.AddConstraint(
            model_name="domainmonitoralert",
            constraint=models.UniqueConstraint(fields=("run", "kind"), name="domain_monitor_alert_run_kind_unique"),
        ),
    ]
