# Generated by Django 5.2.17 on 2026-08-13 03:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_domain_monitoring_guards_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('https', 'HTTPS'), ('smtps', 'SMTP over TLS'), ('imaps', 'IMAP over TLS'), ('pop3s', 'POP3 over TLS')], max_length=16)),
                ('port', models.PositiveSmallIntegerField()),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('monitor_interval_hours', models.PositiveSmallIntegerField(default=24)),
                ('next_monitor_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_monitor_at', models.DateTimeField(blank=True, null=True)),
                ('monitor_state', models.CharField(choices=[('never', 'Never checked'), ('queued', 'Queued'), ('running', 'Running'), ('current', 'Current'), ('failed', 'Check failed')], default='never', max_length=16)),
                ('monitor_error_code', models.CharField(blank=True, max_length=64)),
                ('current_leaf_sha256', models.CharField(blank=True, max_length=64)),
                ('current_not_after', models.DateTimeField(blank=True, null=True)),
                ('current_hostname_valid', models.BooleanField(blank=True, null=True)),
                ('current_trust_valid', models.BooleanField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_certificate_endpoints', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoints', to='core.registereddomain')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoint', to='core.entity')),
                ('hostname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoints', to='core.managedhostname')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoints', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoints', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_endpoints', to='core.workspace')),
            ],
            options={
                'ordering': ('domain__ascii_name', 'hostname__ascii_name', 'protocol', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CertificateMonitorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('leaf_sha256', models.CharField(blank=True, max_length=64)),
                ('chain_sha256', models.CharField(blank=True, max_length=64)),
                ('chain_length', models.PositiveSmallIntegerField(default=0)),
                ('subject_common_name', models.CharField(blank=True, max_length=253)),
                ('issuer_common_name', models.CharField(blank=True, max_length=253)),
                ('serial_sha256', models.CharField(blank=True, max_length=64)),
                ('san_sha256', models.CharField(blank=True, max_length=64)),
                ('san_count', models.PositiveSmallIntegerField(default=0)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('hostname_valid', models.BooleanField(blank=True, null=True)),
                ('trust_valid', models.BooleanField(blank=True, null=True)),
                ('tls_version', models.CharField(blank=True, max_length=32)),
                ('cipher_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_runs', to='core.certificateendpoint')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_runs', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_certificate_monitor_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_runs', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_runs', to='core.workspace')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CertificateMonitorAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('expiration_due', 'Certificate expiration due'), ('certificate_changed', 'Certificate changed'), ('validation_failed', 'Certificate validation failed'), ('collection_failed', 'Certificate collection failed')], max_length=32)),
                ('observed_not_after', models.DateTimeField(blank=True, null=True)),
                ('prior_not_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_alerts', to='core.certificateendpoint')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_alerts', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_alerts', to='core.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_monitor_alerts', to='core.workspace')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='core.certificatemonitorrun')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='certificateendpoint',
            index=models.Index(fields=['workspace', 'monitor_state', 'next_monitor_at'], name='core_certendpoint_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificateendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('hostname__isnull', True)), fields=('workspace', 'domain', 'protocol'), name='certificate_apex_endpoint_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='certificateendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('hostname__isnull', False)), fields=('workspace', 'hostname', 'protocol'), name='certificate_host_endpoint_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='certificateendpoint',
            constraint=models.CheckConstraint(condition=models.Q(('protocol__in', ['https', 'smtps', 'imaps', 'pop3s'])), name='certificate_endpoint_protocol_valid'),
        ),
        migrations.AddIndex(
            model_name='certificatemonitorrun',
            index=models.Index(fields=['workspace', 'state', 'available_at'], name='core_certrun_due_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatemonitorrun',
            index=models.Index(fields=['endpoint', 'created_at'], name='core_certrun_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificatemonitorrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 5)), name='certificate_run_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='certificatemonitorrun',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ('manual', 'scheduled'))), name='certificate_run_trigger_valid'),
        ),
        migrations.AddConstraint(
            model_name='certificatemonitoralert',
            constraint=models.UniqueConstraint(fields=('run', 'kind'), name='certificate_alert_run_kind_unique'),
        ),
    ]
