# Generated by Django 5.2.17 on 2026-08-13 04:35

import hashlib
import json

from django.db import migrations, models


def _digest(kind, values):
    payload = {"schema": 1, "kind": kind, **values}
    encoded = json.dumps(payload, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()
    return hashlib.sha256(encoded).hexdigest()


def backfill_evidence(apps, schema_editor):  # type: ignore[no-untyped-def]
    DomainRun = apps.get_model("core", "DomainMonitorRun")
    CertificateRun = apps.get_model("core", "CertificateMonitorRun")
    empty_caa_digest = hashlib.sha256(b"[]").hexdigest()
    for run in DomainRun.objects.filter(state="succeeded").iterator(chunk_size=500):
        run.caa_digest = empty_caa_digest
        run.evidence_digest = _digest(
            "domain_monitor_run",
            {
                "rdap_source": run.rdap_source,
                "rdap_digest": run.rdap_digest,
                "observed_expiration_date": (
                    run.observed_expiration_date.isoformat() if run.observed_expiration_date else None
                ),
                "observed_registrar": run.observed_registrar,
                "dns_source": run.dns_source,
                "dns_digest": run.dns_digest,
                "dnssec_validated": run.dnssec_validated,
                "dns_record_count": run.dns_record_count,
                "caa_digest": run.caa_digest,
                "caa_record_count": 0,
            },
        )
        run.save(update_fields=("caa_digest", "evidence_digest"))
    for run in CertificateRun.objects.filter(state="succeeded").iterator(chunk_size=500):
        run.evidence_digest = _digest(
            "certificate_monitor_run",
            {
                "leaf_sha256": run.leaf_sha256,
                "chain_sha256": run.chain_sha256,
                "chain_length": run.chain_length,
                "subject_common_name": run.subject_common_name,
                "issuer_common_name": run.issuer_common_name,
                "serial_sha256": run.serial_sha256,
                "san_sha256": run.san_sha256,
                "san_count": run.san_count,
                "not_before": run.not_before.isoformat() if run.not_before else None,
                "not_after": run.not_after.isoformat() if run.not_after else None,
                "hostname_valid": run.hostname_valid,
                "trust_valid": run.trust_valid,
                "tls_version": run.tls_version,
                "cipher_name": run.cipher_name,
            },
        )
        run.save(update_fields=("evidence_digest",))


def disable_terminal_evidence_guards(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Permit this migration to enrich terminal evidence without weakening runtime guards."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE core_domainmonitorrun DISABLE TRIGGER core_domain_monitor_run_guard"
    )
    schema_editor.execute(
        "ALTER TABLE core_certificatemonitorrun "
        "DISABLE TRIGGER core_certificate_monitor_run_guard"
    )


def enable_terminal_evidence_guards(apps, schema_editor):  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER TABLE core_domainmonitorrun ENABLE TRIGGER core_domain_monitor_run_guard"
    )
    schema_editor.execute(
        "ALTER TABLE core_certificatemonitorrun "
        "ENABLE TRIGGER core_certificate_monitor_run_guard"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_certificate_monitoring_guards_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemonitorrun',
            name='evidence_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='domainmonitorrun',
            name='caa_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='domainmonitorrun',
            name='caa_record_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domainmonitorrun',
            name='evidence_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(
            disable_terminal_evidence_guards,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(backfill_evidence, migrations.RunPython.noop),
        migrations.RunPython(
            enable_terminal_evidence_guards,
            migrations.RunPython.noop,
        ),
    ]
