# Generated by Django 5.2.17 on 2026-08-13 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_monitoring_stabilization_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificatemonitorrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), models.Q(('evidence_digest', ''), _negated=True), _connector='OR'), name='certificate_run_success_has_digest'),
        ),
        migrations.AddConstraint(
            model_name='domainmonitorrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), models.Q(('evidence_digest', ''), _negated=True), _connector='OR'), name='domain_monitor_success_has_digest'),
        ),
    ]
