# Generated by Django 5.2.17 on 2026-08-16 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD = r"""
CREATE OR REPLACE FUNCTION tekdocs_validate_document_attachment() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_document d
    WHERE d.id = NEW.document_id AND d.tenant_id = NEW.tenant_id
      AND d.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'attachment document workspace mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_entity e
    WHERE e.id = NEW.entity_id AND e.tenant_id = NEW.tenant_id
      AND e.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND e.entity_type = 'document_attachment'
  ) THEN RAISE EXCEPTION 'attachment entity workspace mismatch'; END IF;
  IF NEW.checksum !~ '^[0-9a-f]{64}$' OR NEW.size < 1 OR NEW.size > 10485760 THEN
    RAISE EXCEPTION 'attachment integrity metadata is invalid';
  END IF;
  IF TG_OP = 'UPDATE' AND (
    OLD.purpose = 'primary_file'
    OR NEW.purpose IS DISTINCT FROM OLD.purpose
    OR NEW.version_number IS DISTINCT FROM OLD.version_number
    OR NEW.replaces_id IS DISTINCT FROM OLD.replaces_id
  ) THEN RAISE EXCEPTION 'primary file version identity is immutable'; END IF;
  IF NEW.purpose = 'primary_file' AND (
    NEW.version_number IS NULL OR NEW.version_number < 1
    OR (NEW.version_number = 1 AND NEW.replaces_id IS NOT NULL)
    OR (NEW.version_number > 1 AND NOT EXISTS (
      SELECT 1 FROM core_documentattachment prior
      WHERE prior.id = NEW.replaces_id
        AND prior.document_id = NEW.document_id
        AND prior.tenant_id = NEW.tenant_id
        AND prior.organization_id IS NOT DISTINCT FROM NEW.organization_id
        AND prior.purpose = 'primary_file'
        AND prior.version_number = NEW.version_number - 1
        AND prior.archived_at IS NULL
    ))
  ) THEN RAISE EXCEPTION 'primary file version chain is invalid'; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_retain_primary_document_file() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.purpose = 'primary_file' THEN
    RAISE EXCEPTION 'primary document file versions are immutable';
  END IF;
  RETURN OLD;
END $$;

DROP TRIGGER IF EXISTS core_documentattachment_primary_file_retention ON core_documentattachment;
CREATE TRIGGER core_documentattachment_primary_file_retention
BEFORE DELETE ON core_documentattachment
FOR EACH ROW EXECUTE FUNCTION tekdocs_retain_primary_document_file();
"""

REVERSE = r"""
DROP TRIGGER IF EXISTS core_documentattachment_primary_file_retention ON core_documentattachment;
DROP FUNCTION IF EXISTS tekdocs_retain_primary_document_file();

CREATE OR REPLACE FUNCTION tekdocs_validate_document_attachment() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_document d
    WHERE d.id = NEW.document_id AND d.tenant_id = NEW.tenant_id
      AND d.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'attachment document workspace mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_entity e
    WHERE e.id = NEW.entity_id AND e.tenant_id = NEW.tenant_id
      AND e.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND e.entity_type = 'document_attachment'
  ) THEN RAISE EXCEPTION 'attachment entity workspace mismatch'; END IF;
  IF NEW.checksum !~ '^[0-9a-f]{64}$' OR NEW.size < 1 OR NEW.size > 10485760 THEN
    RAISE EXCEPTION 'attachment integrity metadata is invalid';
  END IF;
  RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_monitored_document_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentattachment",
            name="purpose",
            field=models.CharField(
                choices=[("attachment", "Attachment"), ("primary_file", "Primary document file")],
                default="attachment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentattachment",
            name="replaces",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement",
                to="core.documentattachment",
            ),
        ),
        migrations.AddField(
            model_name="documentattachment",
            name="version_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="documentattachment",
            index=models.Index(fields=["document", "purpose", "version_number"], name="core_docatt_primary_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("purpose", "attachment"), ("replaces__isnull", True), ("version_number__isnull", True)),
                    models.Q(("purpose", "primary_file"), ("version_number__isnull", False)),
                    _connector="OR",
                ),
                name="document_attachment_purpose_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentattachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "primary_file")),
                fields=("document", "version_number"),
                name="unique_document_primary_file_version",
            ),
        ),
        migrations.RunSQL(FORWARD, REVERSE),
    ]
