# Generated by Django 5.2.17 on 2026-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_documentattachment_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentpublicationartifact',
            name='publication_artifact_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='documentpublicationartifact',
            name='publication_artifact_source_valid',
        ),
        migrations.AlterField(
            model_name='documentpublicationartifact',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('attachment', 'Retained attachment'), ('diagram_svg', 'Diagram SVG'), ('diagram_png', 'Diagram PNG')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='documentpublicationartifact',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['pdf', 'attachment', 'diagram_svg', 'diagram_png'])), name='publication_artifact_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentpublicationartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('pdf', 'diagram_svg', 'diagram_png')), ('source_attachment__isnull', True)), models.Q(('kind', 'attachment'), ('source_attachment__isnull', False)), _connector='OR'), name='publication_artifact_source_valid'),
        ),
    ]
