# Generated by Django 5.2.17 on 2026-08-20 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_document_key_bindings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentkeybinding",
            name="document_key_binding_name_unique",
        ),
        migrations.AddField(
            model_name="documentkeybinding",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="documentkeybinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("document", "name"),
                name="document_key_binding_name_unique",
            ),
        ),
    ]
