# Generated by Django 5.2.17 on 2026-08-24 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_document_key_binding_archival"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFlow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_data_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_record",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flows",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flows",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flows",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="DataFlowRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("internal", "Internal record"),
                            ("external", "External party"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_label", models.CharField(blank=True, max_length=240)),
                (
                    "destination_kind",
                    models.CharField(
                        choices=[
                            ("internal", "Internal record"),
                            ("external", "External party"),
                        ],
                        max_length=16,
                    ),
                ),
                ("destination_label", models.CharField(blank=True, max_length=240)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("one_way", "One way"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "transfer_mechanism",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("file_transfer", "File transfer"),
                            ("database_replication", "Database replication"),
                            ("message_queue", "Message queue"),
                            ("email", "Email"),
                            ("physical_media", "Physical media"),
                            ("manual_entry", "Manual entry"),
                            ("backup", "Backup"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                            ("personal_data", "Personal data"),
                            ("special_category", "Special category personal data"),
                        ],
                        max_length=24,
                    ),
                ),
                ("purpose", models.CharField(max_length=1000)),
                ("crosses_trust_boundary", models.BooleanField()),
                (
                    "protection",
                    models.CharField(
                        choices=[
                            ("none", "No protection recorded"),
                            ("in_transit", "Encrypted in transit"),
                            ("at_rest", "Encrypted at rest"),
                            (
                                "in_transit_and_at_rest",
                                "Encrypted in transit and at rest",
                            ),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("review_due_on", models.DateField(blank=True, null=True)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("recorded_fact", "Recorded fact"),
                            ("imported_observation", "Imported observation"),
                            ("unverified_draft", "Unverified draft"),
                        ],
                        max_length=24,
                    ),
                ),
                ("content_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_data_flow_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="core.dataflow",
                    ),
                ),
                (
                    "destination_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_destinations",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_revisions",
                        to="core.organization",
                    ),
                ),
                (
                    "owner_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_data_flows",
                        to="core.entity",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_sources",
                        to="core.entity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_revisions",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_flow_revisions",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-revision_number", "id"),
            },
        ),
        migrations.AddField(
            model_name="dataflow",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.dataflowrevision",
            ),
        ),
        migrations.AddIndex(
            model_name="dataflowrevision",
            index=models.Index(
                fields=["workspace", "created_at"], name="core_dataflowrev_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.UniqueConstraint(
                fields=("data_flow", "revision_number"),
                name="data_flow_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_number__gte", 1)),
                name="data_flow_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_digest__regex", "^[0-9a-f]{64}$")),
                name="data_flow_revision_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_entity__isnull", False),
                        ("source_kind", "internal"),
                        ("source_label", ""),
                    ),
                    models.Q(
                        ("source_entity__isnull", True),
                        ("source_kind", "external"),
                        models.Q(("source_label", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="data_flow_revision_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destination_entity__isnull", False),
                        ("destination_kind", "internal"),
                        ("destination_label", ""),
                    ),
                    models.Q(
                        ("destination_entity__isnull", True),
                        ("destination_kind", "external"),
                        models.Q(("destination_label", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="data_flow_revision_destination_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["one_way", "bidirectional"])),
                name="data_flow_revision_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "transfer_mechanism__in",
                        [
                            "api",
                            "file_transfer",
                            "database_replication",
                            "message_queue",
                            "email",
                            "physical_media",
                            "manual_entry",
                            "backup",
                            "other",
                        ],
                    )
                ),
                name="data_flow_revision_transfer_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "data_classification__in",
                        [
                            "public",
                            "internal",
                            "confidential",
                            "restricted",
                            "personal_data",
                            "special_category",
                        ],
                    )
                ),
                name="data_flow_revision_classification_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "protection__in",
                        [
                            "none",
                            "in_transit",
                            "at_rest",
                            "in_transit_and_at_rest",
                            "unknown",
                        ],
                    )
                ),
                name="data_flow_revision_protection_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataflowrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "provenance__in",
                        ["recorded_fact", "imported_observation", "unverified_draft"],
                    )
                ),
                name="data_flow_revision_provenance_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="dataflow",
            index=models.Index(
                fields=["workspace", "archived_at"], name="core_dataflow_scope_idx"
            ),
        ),
    ]
