# Generated by Django 5.2.17 on 2026-08-29 16:51

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_catalog_product_price() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.unit_amount IS NULL) <> (NEW.currency = '') THEN
    RAISE EXCEPTION 'catalog product price and currency must be provided together';
  END IF;
  IF NEW.currency <> '' AND NEW.currency !~ '^[A-Z]{3}$' THEN
    RAISE EXCEPTION 'catalog product price currency invalid';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_catalog_product_price_guard BEFORE INSERT OR UPDATE ON core_catalogproduct
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_catalog_product_price();

CREATE FUNCTION tekdocs_validate_service_rate() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'service rate currency invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_service_rate_guard BEFORE INSERT OR UPDATE ON core_servicerate
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_service_rate();

CREATE FUNCTION tekdocs_validate_invoice_draft() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_organization organization
    WHERE organization.id=NEW.organization_id AND organization.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice organization scope mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_organizationclassification classification
    WHERE classification.organization_id=NEW.organization_id AND classification.tenant_id=NEW.tenant_id
      AND classification.kind='client'
  ) THEN RAISE EXCEPTION 'invoice requires client organization'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_entity entity
    WHERE entity.id=NEW.entity_id AND entity.tenant_id=NEW.tenant_id
      AND entity.organization_id=NEW.organization_id AND entity.entity_type='invoice'
      AND entity.visibility='msp_private'
  ) THEN RAISE EXCEPTION 'invoice entity scope mismatch'; END IF;
  IF TG_OP = 'UPDATE'
    AND (NEW.tenant_id, NEW.organization_id, NEW.currency)
      IS DISTINCT FROM (OLD.tenant_id, OLD.organization_id, OLD.currency)
    AND EXISTS (SELECT 1 FROM core_invoiceline line WHERE line.invoice_id=NEW.id)
  THEN RAISE EXCEPTION 'invoice scope and currency are fixed while lines exist'; END IF;
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'invoice currency invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_draft_guard BEFORE INSERT OR UPDATE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_draft();

CREATE FUNCTION tekdocs_validate_invoice_line() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_invoice invoice
    WHERE invoice.id=NEW.invoice_id AND invoice.tenant_id=NEW.tenant_id
      AND invoice.organization_id=NEW.organization_id AND invoice.currency=NEW.currency
      AND invoice.state='draft'
  ) THEN RAISE EXCEPTION 'invoice line scope or currency mismatch'; END IF;
  IF NEW.catalog_product_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_catalogproduct product
    WHERE product.id=NEW.catalog_product_id AND product.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line product origin scope mismatch'; END IF;
  IF NEW.service_rate_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_servicerate rate
    WHERE rate.id=NEW.service_rate_id AND rate.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line service-rate origin scope mismatch'; END IF;
  IF NEW.contract_cost_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contractcost cost
    WHERE cost.id=NEW.contract_cost_id AND cost.tenant_id=NEW.tenant_id
      AND cost.organization_id=NEW.organization_id
  ) THEN RAISE EXCEPTION 'invoice line contract-cost origin scope mismatch'; END IF;
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'invoice line currency invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_line_guard BEFORE INSERT OR UPDATE ON core_invoiceline
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_line();

DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_invoice', 'core_invoiceline'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY %I_runtime_scope ON %I USING (tekdocs_scope_matches(tenant_id, organization_id)) WITH CHECK (tekdocs_scope_matches(tenant_id, organization_id))',
      table_name, table_name);
  END LOOP;
  ALTER TABLE core_servicerate ENABLE ROW LEVEL SECURITY;
  ALTER TABLE core_servicerate FORCE ROW LEVEL SECURITY;
  CREATE POLICY core_servicerate_runtime_scope ON core_servicerate
    USING (tenant_id=tekdocs_current_tenant_id()) WITH CHECK (tenant_id=tekdocs_current_tenant_id());
END $$;
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_servicerate_runtime_scope ON core_servicerate;
ALTER TABLE core_servicerate NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_servicerate DISABLE ROW LEVEL SECURITY;
DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_invoice', 'core_invoiceline'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_runtime_scope ON %I', table_name, table_name);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;
DROP TRIGGER IF EXISTS core_invoice_line_guard ON core_invoiceline;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_line();
DROP TRIGGER IF EXISTS core_invoice_draft_guard ON core_invoice;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_draft();
DROP TRIGGER IF EXISTS core_service_rate_guard ON core_servicerate;
DROP FUNCTION IF EXISTS tekdocs_validate_service_rate();
DROP TRIGGER IF EXISTS core_catalog_product_price_guard ON core_catalogproduct;
DROP FUNCTION IF EXISTS tekdocs_validate_catalog_product_price();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_billing_money_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name='catalogproduct',
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(('currency', ''), ('unit_amount__isnull', True)), models.Q(('unit_amount__isnull', False), models.Q(('currency', ''), _negated=True)), _connector='OR'),
                name='catalog_product_price_pair',
            ),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.entity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.tenant')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_rates', to='core.tenant')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('tax_rate_name', models.CharField(blank=True, max_length=120)),
                ('tax_rate_value', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.catalogproduct')),
                ('contract_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.contractcost')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.tenant')),
                ('service_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='core.servicerate')),
            ],
            options={
                'ordering': ('position', 'created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'organization', 'state', 'invoice_date'], name='core_invoice_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'draft')), name='invoice_draft_state_only'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('invoice_date'))), name='invoice_due_date_valid'),
        ),
        migrations.AddIndex(
            model_name='servicerate',
            index=models.Index(fields=['tenant', 'archived_at', 'name'], name='core_servicerate_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerate',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0)), name='service_rate_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='servicerate',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('tenant'), condition=models.Q(('archived_at__isnull', True)), name='service_rate_name_active_unique'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['tenant', 'organization', 'invoice'], name='core_invline_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='invoice_line_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_value__gte', 0)), name='invoice_line_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_product__isnull', True), ('service_rate__isnull', True)), models.Q(('catalog_product__isnull', True), ('contract_cost__isnull', True)), models.Q(('contract_cost__isnull', True), ('service_rate__isnull', True)), _connector='OR'), name='invoice_line_one_origin'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='invoice_line_position_unique'),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
