# Generated by Django 5.2.17 on 2026-08-29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_invoice_series() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.prefix !~ '^[A-Z0-9-]{1,16}$' THEN RAISE EXCEPTION 'invoice series prefix invalid'; END IF;
  IF NEW.yearly_reset = FALSE AND NEW.current_year IS NOT NULL THEN
    RAISE EXCEPTION 'non-yearly invoice series cannot retain a year';
  END IF;
  IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM core_invoice invoice WHERE invoice.number_series_id=OLD.id)
    AND (NEW.tenant_id, NEW.prefix, NEW.yearly_reset) IS DISTINCT FROM (OLD.tenant_id, OLD.prefix, OLD.yearly_reset)
  THEN RAISE EXCEPTION 'used invoice series identity is immutable'; END IF;
  IF TG_OP = 'UPDATE' AND NEW.next_number < OLD.next_number
    AND NOT (NEW.yearly_reset AND NEW.current_year > OLD.current_year AND NEW.next_number=1)
  THEN RAISE EXCEPTION 'invoice series counter cannot move backward'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_series_guard BEFORE INSERT OR UPDATE ON core_invoicenumberseries
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_series();

CREATE FUNCTION tekdocs_validate_invoice_issue_fields() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE series core_invoicenumberseries%ROWTYPE;
BEGIN
  IF NEW.state <> 'issued' THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND OLD.state = 'issued' THEN RETURN NEW; END IF;
  SELECT * INTO series FROM core_invoicenumberseries WHERE id=NEW.number_series_id AND tenant_id=NEW.tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'invoice number series scope mismatch'; END IF;
  IF NEW.series_sequence <> series.next_number THEN
    RAISE EXCEPTION 'issued invoice does not consume the next series number';
  END IF;
  IF series.yearly_reset THEN
    IF NEW.series_year IS NULL OR NEW.series_year <> series.current_year
      OR NEW.number <> series.prefix || '-' || NEW.series_year || '-' || lpad(NEW.series_sequence::text, 6, '0')
    THEN RAISE EXCEPTION 'issued invoice yearly number mismatch'; END IF;
  ELSIF NEW.series_year IS NOT NULL OR NEW.number <> series.prefix || '-' || lpad(NEW.series_sequence::text, 6, '0') THEN
    RAISE EXCEPTION 'issued invoice number mismatch';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_issue_scope_guard BEFORE INSERT OR UPDATE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_issue_fields();

CREATE FUNCTION tekdocs_reject_issued_invoice_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state = 'issued' THEN RAISE EXCEPTION 'issued invoice is immutable'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_issued_update_guard BEFORE UPDATE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_reject_issued_invoice_mutation();

CREATE FUNCTION tekdocs_reject_issued_invoice_delete() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state = 'issued' THEN RAISE EXCEPTION 'issued invoice is retained'; END IF;
  RETURN OLD;
END $$;
CREATE TRIGGER core_invoice_issued_delete_guard BEFORE DELETE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_reject_issued_invoice_delete();

CREATE FUNCTION tekdocs_reject_issued_invoice_line_delete() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM core_invoice invoice WHERE invoice.id=OLD.invoice_id AND invoice.state='issued') THEN
    RAISE EXCEPTION 'issued invoice lines are immutable';
  END IF;
  RETURN OLD;
END $$;
CREATE TRIGGER core_invoice_line_issued_delete_guard BEFORE DELETE ON core_invoiceline
FOR EACH ROW EXECUTE FUNCTION tekdocs_reject_issued_invoice_line_delete();

CREATE FUNCTION tekdocs_validate_invoice_artifact() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_invoice invoice
    WHERE invoice.id=NEW.invoice_id AND invoice.tenant_id=NEW.tenant_id
      AND invoice.organization_id=NEW.organization_id AND invoice.state='issued'
  ) THEN RAISE EXCEPTION 'invoice artifact scope or state mismatch'; END IF;
  IF NEW.media_type <> 'application/pdf' OR NEW.checksum !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'invoice artifact metadata invalid';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_artifact_insert_guard BEFORE INSERT ON core_invoiceartifact
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_artifact();

CREATE FUNCTION tekdocs_reject_invoice_artifact_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'issued invoice artifact is retained and immutable';
END $$;
CREATE TRIGGER core_invoice_artifact_update_guard BEFORE UPDATE OR DELETE ON core_invoiceartifact
FOR EACH ROW EXECUTE FUNCTION tekdocs_reject_invoice_artifact_mutation();

ALTER TABLE core_invoiceartifact ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_invoiceartifact FORCE ROW LEVEL SECURITY;
CREATE POLICY core_invoiceartifact_runtime_scope ON core_invoiceartifact
  USING (tekdocs_scope_matches(tenant_id, organization_id))
  WITH CHECK (tekdocs_scope_matches(tenant_id, organization_id));
ALTER TABLE core_invoicenumberseries ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_invoicenumberseries FORCE ROW LEVEL SECURITY;
CREATE POLICY core_invoicenumberseries_runtime_scope ON core_invoicenumberseries
  USING (tenant_id=tekdocs_current_tenant_id()) WITH CHECK (tenant_id=tekdocs_current_tenant_id());
"""


REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_invoicenumberseries_runtime_scope ON core_invoicenumberseries;
ALTER TABLE core_invoicenumberseries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_invoicenumberseries DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS core_invoiceartifact_runtime_scope ON core_invoiceartifact;
ALTER TABLE core_invoiceartifact NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_invoiceartifact DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_invoice_artifact_update_guard ON core_invoiceartifact;
DROP FUNCTION IF EXISTS tekdocs_reject_invoice_artifact_mutation();
DROP TRIGGER IF EXISTS core_invoice_artifact_insert_guard ON core_invoiceartifact;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_artifact();
DROP TRIGGER IF EXISTS core_invoice_line_issued_delete_guard ON core_invoiceline;
DROP FUNCTION IF EXISTS tekdocs_reject_issued_invoice_line_delete();
DROP TRIGGER IF EXISTS core_invoice_issued_delete_guard ON core_invoice;
DROP FUNCTION IF EXISTS tekdocs_reject_issued_invoice_delete();
DROP TRIGGER IF EXISTS core_invoice_issued_update_guard ON core_invoice;
DROP FUNCTION IF EXISTS tekdocs_reject_issued_invoice_mutation();
DROP TRIGGER IF EXISTS core_invoice_issue_scope_guard ON core_invoice;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_issue_fields();
DROP TRIGGER IF EXISTS core_invoice_series_guard ON core_invoicenumberseries;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_series();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0128_invoice_drafts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=500, upload_to=apps.core.models.invoice_artifact_upload_to)),
                ("original_filename", models.CharField(max_length=240)),
                ("media_type", models.CharField(default="application/pdf", max_length=120)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceNumberSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("prefix", models.CharField(max_length=16)),
                ("yearly_reset", models.BooleanField(default=False)),
                ("current_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("next_number", models.PositiveBigIntegerField(default=1)),
            ],
            options={"ordering": ("prefix", "id")},
        ),
        migrations.RemoveConstraint(model_name="invoice", name="invoice_draft_state_only"),
        migrations.AddField(
            model_name="invoice", name="content_digest", field=models.CharField(blank=True, max_length=64)
        ),
        migrations.AddField(
            model_name="invoice", name="customer_snapshot", field=models.JSONField(blank=True, default=dict)
        ),
        migrations.AddField(model_name="invoice", name="issued_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(
            model_name="invoice",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice", name="issuer_snapshot", field=models.JSONField(blank=True, default=dict)
        ),
        migrations.AddField(
            model_name="invoice", name="key_fingerprint", field=models.CharField(blank=True, max_length=64)
        ),
        migrations.AddField(
            model_name="invoice", name="key_resolutions", field=models.JSONField(blank=True, default=list)
        ),
        migrations.AddField(model_name="invoice", name="number", field=models.CharField(blank=True, max_length=64)),
        migrations.AddField(model_name="invoice", name="public_key", field=models.TextField(blank=True)),
        migrations.AddField(
            model_name="invoice", name="series_sequence", field=models.PositiveBigIntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="invoice", name="series_year", field=models.PositiveSmallIntegerField(blank=True, null=True)
        ),
        migrations.AddField(model_name="invoice", name="signature", field=models.TextField(blank=True)),
        migrations.AddField(
            model_name="invoice", name="signature_algorithm", field=models.CharField(blank=True, max_length=20)
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal_amount",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="state",
            field=models.CharField(choices=[("draft", "Draft"), ("issued", "Issued")], default="draft", max_length=16),
        ),
        migrations.AddField(
            model_name="invoiceartifact",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="artifact", to="core.invoice"
            ),
        ),
        migrations.AddField(
            model_name="invoiceartifact",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_artifacts", to="core.organization"
            ),
        ),
        migrations.AddField(
            model_name="invoiceartifact",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_artifacts", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="invoicenumberseries",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_number_series", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="number_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.invoicenumberseries",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(state__in=["draft", "issued"]), name="invoice_state_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="draft")
                    | models.Q(total_amount=models.F("subtotal_amount") + models.F("tax_amount"))
                ),
                name="invoice_stored_totals_reconcile",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state="draft",
                        number_series__isnull=True,
                        number="",
                        series_year__isnull=True,
                        series_sequence__isnull=True,
                        subtotal_amount__isnull=True,
                        tax_amount__isnull=True,
                        total_amount__isnull=True,
                        issued_by__isnull=True,
                        issued_at__isnull=True,
                        content_digest="",
                        signature="",
                        signature_algorithm="",
                        public_key="",
                        key_fingerprint="",
                    )
                    | models.Q(
                        state="issued",
                        number_series__isnull=False,
                        number__gt="",
                        series_sequence__isnull=False,
                        subtotal_amount__isnull=False,
                        tax_amount__isnull=False,
                        total_amount__isnull=False,
                        issued_by__isnull=False,
                        issued_at__isnull=False,
                        content_digest__regex=r"^[0-9a-f]{64}$",
                        signature__gt="",
                        signature_algorithm="Ed25519",
                        public_key__gt="",
                        key_fingerprint__regex=r"^[0-9a-f]{64}$",
                    )
                ),
                name="invoice_issue_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=~models.Q(number=""), fields=("tenant", "number"), name="invoice_number_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceartifact",
            index=models.Index(fields=["tenant", "organization", "invoice"], name="core_invart_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoicenumberseries",
            constraint=models.UniqueConstraint(fields=("tenant", "prefix"), name="invoice_series_prefix_unique"),
        ),
        migrations.AddConstraint(
            model_name="invoicenumberseries",
            constraint=models.CheckConstraint(
                condition=models.Q(next_number__gte=1), name="invoice_series_next_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicenumberseries",
            constraint=models.CheckConstraint(
                condition=models.Q(yearly_reset=True) | models.Q(yearly_reset=False, current_year__isnull=True),
                name="invoice_series_year_mode_valid",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
