# Generated by Django 5.2.17 on 2026-08-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION tekdocs_reject_issued_invoice_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state = 'issued' AND
    (to_jsonb(NEW) - ARRAY['updated_at', 'delivered_at', 'delivered_by_id', 'delivery_recipient', 'delivery_count'])
      IS DISTINCT FROM
    (to_jsonb(OLD) - ARRAY['updated_at', 'delivered_at', 'delivered_by_id', 'delivery_recipient', 'delivery_count'])
  THEN RAISE EXCEPTION 'issued invoice is immutable'; END IF;
  IF OLD.state = 'issued' AND (
    NEW.delivered_at IS NULL OR NEW.delivered_by_id IS NULL OR NEW.delivery_recipient = ''
    OR NEW.delivery_count < 1 OR NEW.delivery_count < OLD.delivery_count
  ) THEN RAISE EXCEPTION 'issued invoice delivery metadata is invalid'; END IF;
  RETURN NEW;
END $$;
"""


REVERSE_SQL = r"""
CREATE OR REPLACE FUNCTION tekdocs_reject_issued_invoice_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state = 'issued' THEN RAISE EXCEPTION 'issued invoice is immutable'; END IF;
  RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [("core", "0129_gapless_invoice_issue")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivered_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="delivery_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="delivery_recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        delivery_count=0,
                        delivered_at__isnull=True,
                        delivered_by__isnull=True,
                        delivery_recipient="",
                    )
                    | models.Q(
                        state="issued",
                        delivery_count__gte=1,
                        delivered_at__isnull=False,
                        delivered_by__isnull=False,
                        delivery_recipient__gt="",
                    )
                ),
                name="invoice_delivery_fields_consistent",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
