# Generated by Django 5.2.17 on 2026-08-29
# ruff: noqa: E501, I001

from django.db import migrations, models


DROP_OLD_GUARDS = """
DROP TRIGGER IF EXISTS core_invoice_issue_scope_guard ON core_invoice;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_issue_fields();
DROP TRIGGER IF EXISTS core_invoice_series_guard ON core_invoicenumberseries;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_series();
DROP TRIGGER IF EXISTS core_billingprofile_validate ON core_tenantbillingprofile;
DROP FUNCTION IF EXISTS tekdocs_validate_billing_profile();
"""

OLD_GUARDS = r"""
CREATE FUNCTION tekdocs_validate_billing_profile() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.default_currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'billing profile currency invalid'; END IF;
  IF NEW.country_code <> '' AND NEW.country_code !~ '^[A-Z]{2}$' THEN RAISE EXCEPTION 'billing profile country invalid'; END IF;
  IF NEW.invoice_prefix !~ '^[A-Z0-9-]{1,16}$' THEN RAISE EXCEPTION 'billing profile invoice prefix invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_billingprofile_validate BEFORE INSERT OR UPDATE ON core_tenantbillingprofile
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_billing_profile();

CREATE FUNCTION tekdocs_validate_invoice_series() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.prefix !~ '^[A-Z0-9-]{1,16}$' THEN RAISE EXCEPTION 'invoice series prefix invalid'; END IF;
  IF NEW.yearly_reset = FALSE AND NEW.current_year IS NOT NULL THEN RAISE EXCEPTION 'non-yearly invoice series cannot retain a year'; END IF;
  IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM core_invoice invoice WHERE invoice.number_series_id=OLD.id)
    AND (NEW.tenant_id, NEW.prefix, NEW.yearly_reset) IS DISTINCT FROM (OLD.tenant_id, OLD.prefix, OLD.yearly_reset)
  THEN RAISE EXCEPTION 'used invoice series identity is immutable'; END IF;
  IF TG_OP = 'UPDATE' AND NEW.next_number < OLD.next_number
    AND NOT (NEW.yearly_reset AND NEW.current_year > OLD.current_year AND NEW.next_number=1)
  THEN RAISE EXCEPTION 'invoice series counter cannot move backward'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_series_guard BEFORE INSERT OR UPDATE ON core_invoicenumberseries
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_series();

CREATE FUNCTION tekdocs_validate_invoice_issue_fields() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE series core_invoicenumberseries%ROWTYPE;
BEGIN
  IF NEW.state <> 'issued' THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND OLD.state = 'issued' THEN RETURN NEW; END IF;
  SELECT * INTO series FROM core_invoicenumberseries WHERE id=NEW.number_series_id AND tenant_id=NEW.tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'invoice number series scope mismatch'; END IF;
  IF NEW.series_sequence <> series.next_number THEN RAISE EXCEPTION 'issued invoice does not consume the next series number'; END IF;
  IF series.yearly_reset THEN
    IF NEW.series_year IS NULL OR NEW.series_year <> series.current_year
      OR NEW.number <> series.prefix || '-' || NEW.series_year || '-' || lpad(NEW.series_sequence::text, 6, '0')
    THEN RAISE EXCEPTION 'issued invoice yearly number mismatch'; END IF;
  ELSIF NEW.series_year IS NOT NULL OR NEW.number <> series.prefix || '-' || lpad(NEW.series_sequence::text, 6, '0') THEN
    RAISE EXCEPTION 'issued invoice number mismatch';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_issue_scope_guard BEFORE INSERT OR UPDATE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_issue_fields();
"""

NEW_GUARDS = r"""
CREATE FUNCTION tekdocs_validate_billing_profile() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.default_currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'billing profile currency invalid'; END IF;
  IF NEW.country_code <> '' AND NEW.country_code NOT IN ('AD','AE','AF','AG','AI','AL','AM','AO','AQ','AR','AS','AT','AU','AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BJ','BL','BM','BN','BO','BQ','BR','BS','BT','BV','BW','BY','BZ','CA','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','CR','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EE','EG','EH','ER','ES','ET','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL','GM','GN','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE','IL','IM','IN','IO','IQ','IR','IS','IT','JE','JM','JO','JP','KE','KG','KH','KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY','MA','MC','MD','ME','MF','MG','MH','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ','NA','NC','NE','NF','NG','NI','NL','NO','NP','NR','NU','NZ','OM','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PS','PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SR','SS','ST','SV','SX','SY','SZ','TC','TD','TF','TG','TH','TJ','TK','TL','TM','TN','TO','TR','TT','TV','TW','TZ','UA','UG','UM','US','UY','UZ','VA','VC','VE','VG','VI','VN','VU','WF','WS','YE','YT','ZA','ZM','ZW') THEN RAISE EXCEPTION 'billing profile country invalid'; END IF;
  IF NEW.invoice_prefix !~ '^[A-Z0-9-]{1,16}$' THEN RAISE EXCEPTION 'billing profile invoice prefix invalid'; END IF;
  IF NEW.invoice_date_component NOT IN ('none','year','short_year','year_month','short_year_month','month_year','month_short_year','year_month_code','short_year_month_code')
    THEN RAISE EXCEPTION 'billing profile invoice date component invalid'; END IF;
  IF NEW.invoice_separator NOT IN ('-','/','.','') THEN RAISE EXCEPTION 'billing profile invoice separator invalid'; END IF;
  IF NEW.invoice_sequence_digits < 1 OR NEW.invoice_sequence_digits > 12 THEN RAISE EXCEPTION 'billing profile invoice digits invalid'; END IF;
  IF NEW.invoice_reset_period NOT IN ('never','yearly','monthly') THEN RAISE EXCEPTION 'billing profile invoice reset invalid'; END IF;
  IF NEW.invoice_reset_period='yearly' AND NEW.invoice_date_component='none' THEN RAISE EXCEPTION 'yearly reset requires a year component'; END IF;
  IF NEW.invoice_reset_period='monthly' AND NEW.invoice_date_component NOT IN ('year_month','short_year_month','month_year','month_short_year','year_month_code','short_year_month_code') THEN RAISE EXCEPTION 'monthly reset requires a month component'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_billingprofile_validate BEFORE INSERT OR UPDATE ON core_tenantbillingprofile
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_billing_profile();

CREATE FUNCTION tekdocs_validate_invoice_series() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.prefix !~ '^[A-Z0-9-]{1,16}$' THEN RAISE EXCEPTION 'invoice series prefix invalid'; END IF;
  IF NEW.date_component NOT IN ('none','year','short_year','year_month','short_year_month','month_year','month_short_year','year_month_code','short_year_month_code')
    THEN RAISE EXCEPTION 'invoice series date component invalid'; END IF;
  IF NEW.separator NOT IN ('-','/','.','') THEN RAISE EXCEPTION 'invoice series separator invalid'; END IF;
  IF NEW.sequence_digits < 1 OR NEW.sequence_digits > 12 THEN RAISE EXCEPTION 'invoice series digits invalid'; END IF;
  IF NEW.reset_period NOT IN ('never','yearly','monthly') THEN RAISE EXCEPTION 'invoice series reset invalid'; END IF;
  IF NEW.reset_period='yearly' AND NEW.date_component='none' THEN RAISE EXCEPTION 'yearly reset requires a year component'; END IF;
  IF NEW.reset_period='monthly' AND NEW.date_component NOT IN ('year_month','short_year_month','month_year','month_short_year','year_month_code','short_year_month_code') THEN RAISE EXCEPTION 'monthly reset requires a month component'; END IF;
  IF (NEW.reset_period='never' AND NEW.current_period <> '')
    OR (NEW.reset_period='yearly' AND NEW.current_period <> '' AND NEW.current_period !~ '^[0-9]{4}$')
    OR (NEW.reset_period='monthly' AND NEW.current_period <> '' AND NEW.current_period !~ '^[0-9]{4}-(0[1-9]|1[0-2])$')
  THEN RAISE EXCEPTION 'invoice series current period invalid'; END IF;
  IF TG_OP='UPDATE' AND EXISTS (SELECT 1 FROM core_invoice invoice WHERE invoice.number_series_id=OLD.id)
    AND (NEW.tenant_id,NEW.prefix,NEW.date_component,NEW.separator,NEW.sequence_digits,NEW.reset_period)
      IS DISTINCT FROM (OLD.tenant_id,OLD.prefix,OLD.date_component,OLD.separator,OLD.sequence_digits,OLD.reset_period)
  THEN RAISE EXCEPTION 'used invoice series identity is immutable'; END IF;
  IF TG_OP='UPDATE' AND NEW.next_number < OLD.next_number
    AND NOT (NEW.reset_period <> 'never' AND NEW.current_period > OLD.current_period AND NEW.next_number=1)
  THEN RAISE EXCEPTION 'invoice series counter cannot move backward'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_series_guard BEFORE INSERT OR UPDATE ON core_invoicenumberseries
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_series();

CREATE FUNCTION tekdocs_validate_invoice_issue_fields() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  series core_invoicenumberseries%ROWTYPE;
  date_value text := '';
  expected text := '';
  expected_period text := '';
  month_code text;
BEGIN
  IF NEW.state <> 'issued' THEN RETURN NEW; END IF;
  IF TG_OP='UPDATE' AND OLD.state='issued' THEN RETURN NEW; END IF;
  SELECT * INTO series FROM core_invoicenumberseries WHERE id=NEW.number_series_id AND tenant_id=NEW.tenant_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'invoice number series scope mismatch'; END IF;
  IF NEW.series_sequence <> series.next_number THEN RAISE EXCEPTION 'issued invoice does not consume the next series number'; END IF;
  IF NEW.series_sequence >= power(10::numeric, series.sequence_digits) THEN RAISE EXCEPTION 'invoice series exhausted'; END IF;
  month_code := chr(64 + extract(month from NEW.invoice_date)::integer);
  date_value := CASE series.date_component
    WHEN 'none' THEN '' WHEN 'year' THEN to_char(NEW.invoice_date,'YYYY') WHEN 'short_year' THEN to_char(NEW.invoice_date,'YY')
    WHEN 'year_month' THEN to_char(NEW.invoice_date,'YYYYMM') WHEN 'short_year_month' THEN to_char(NEW.invoice_date,'YYMM')
    WHEN 'month_year' THEN to_char(NEW.invoice_date,'MMYYYY') WHEN 'month_short_year' THEN to_char(NEW.invoice_date,'MMYY')
    WHEN 'year_month_code' THEN to_char(NEW.invoice_date,'YYYY') || month_code
    WHEN 'short_year_month_code' THEN to_char(NEW.invoice_date,'YY') || month_code END;
  IF series.prefix <> '' THEN expected := series.prefix; END IF;
  IF date_value <> '' THEN
    IF expected <> '' THEN expected := expected || series.separator; END IF;
    expected := expected || date_value;
  END IF;
  IF expected <> '' THEN expected := expected || series.separator; END IF;
  expected := expected || lpad(NEW.series_sequence::text, series.sequence_digits, '0');
  expected_period := CASE series.reset_period WHEN 'yearly' THEN to_char(NEW.invoice_date,'YYYY')
    WHEN 'monthly' THEN to_char(NEW.invoice_date,'YYYY-MM') ELSE '' END;
  IF series.current_period <> expected_period OR NEW.number <> expected THEN RAISE EXCEPTION 'issued invoice number mismatch'; END IF;
  IF (series.reset_period='never' AND NEW.series_year IS NOT NULL)
    OR (series.reset_period <> 'never' AND NEW.series_year <> extract(year from NEW.invoice_date)::integer)
  THEN RAISE EXCEPTION 'issued invoice period mismatch'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_issue_scope_guard BEFORE INSERT OR UPDATE ON core_invoice
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_issue_fields();
"""

DROP_NEW_GUARDS = DROP_OLD_GUARDS


def forwards(apps, schema_editor):
    Profile = apps.get_model("core", "TenantBillingProfile")
    Series = apps.get_model("core", "InvoiceNumberSeries")
    for series in Series.objects.all().iterator():
        series.date_component = "year" if series.yearly_reset else "none"
        series.reset_period = "yearly" if series.yearly_reset else "never"
        series.current_period = str(series.current_year) if series.current_year else ""
        series.save(update_fields=("date_component", "reset_period", "current_period"))
    for profile in Profile.objects.all().iterator():
        series = Series.objects.filter(tenant_id=profile.tenant_id, prefix=profile.invoice_prefix).first()
        if series and series.yearly_reset:
            profile.invoice_date_component = "year"
            profile.invoice_reset_period = "yearly"
            profile.save(update_fields=("invoice_date_component", "invoice_reset_period"))


def backwards(apps, schema_editor):
    Series = apps.get_model("core", "InvoiceNumberSeries")
    for series in Series.objects.all().iterator():
        series.yearly_reset = series.reset_period != "never"
        series.current_year = int(series.current_period[:4]) if series.current_period else None
        series.save(update_fields=("yearly_reset", "current_year"))


class Migration(migrations.Migration):
    dependencies = [("core", "0130_invoice_client_delivery")]

    operations = [
        migrations.AddField(model_name="tenantbillingprofile", name="invoice_date_component", field=models.CharField(choices=[("none", "No date"), ("year", "Four-digit year"), ("short_year", "Two-digit year"), ("year_month", "Year and month"), ("short_year_month", "Short year and month"), ("month_year", "Month and year"), ("month_short_year", "Month and short year"), ("year_month_code", "Year and month letter"), ("short_year_month_code", "Short year and month letter")], default="none", max_length=24)),
        migrations.AddField(model_name="tenantbillingprofile", name="invoice_reset_period", field=models.CharField(choices=[("never", "Never"), ("yearly", "Every year"), ("monthly", "Every month")], default="never", max_length=8)),
        migrations.AddField(model_name="tenantbillingprofile", name="invoice_separator", field=models.CharField(blank=True, choices=[("-", "Hyphen"), ("/", "Slash"), (".", "Period"), ("", "None")], default="-", max_length=1)),
        migrations.AddField(model_name="tenantbillingprofile", name="invoice_sequence_digits", field=models.PositiveSmallIntegerField(default=6)),
        migrations.AddField(model_name="invoicenumberseries", name="current_period", field=models.CharField(blank=True, default="", max_length=7)),
        migrations.AddField(model_name="invoicenumberseries", name="date_component", field=models.CharField(default="none", max_length=24)),
        migrations.AddField(model_name="invoicenumberseries", name="reset_period", field=models.CharField(default="never", max_length=8)),
        migrations.AddField(model_name="invoicenumberseries", name="separator", field=models.CharField(blank=True, default="-", max_length=1)),
        migrations.AddField(model_name="invoicenumberseries", name="sequence_digits", field=models.PositiveSmallIntegerField(default=6)),
        migrations.RunPython(forwards, backwards),
        migrations.RunSQL(DROP_OLD_GUARDS, OLD_GUARDS),
        migrations.RemoveConstraint(model_name="invoicenumberseries", name="invoice_series_prefix_unique"),
        migrations.RemoveConstraint(model_name="invoicenumberseries", name="invoice_series_year_mode_valid"),
        migrations.RemoveField(model_name="invoicenumberseries", name="current_year"),
        migrations.RemoveField(model_name="invoicenumberseries", name="yearly_reset"),
        migrations.AddConstraint(model_name="invoicenumberseries", constraint=models.UniqueConstraint(fields=("tenant", "prefix", "date_component", "separator", "sequence_digits", "reset_period"), name="invoice_series_format_unique")),
        migrations.AddConstraint(model_name="invoicenumberseries", constraint=models.CheckConstraint(condition=models.Q(sequence_digits__gte=1, sequence_digits__lte=12), name="invoice_series_digits_bounded")),
        migrations.RunSQL(NEW_GUARDS, DROP_NEW_GUARDS),
    ]
