# Generated by Django 5.2.17 on 2026-09-01 05:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_documentation_map() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspace workspace
    WHERE workspace.id=NEW.workspace_id AND workspace.tenant_id=NEW.tenant_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'documentation map workspace mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_entity entity
    WHERE entity.id=NEW.entity_id AND entity.tenant_id=NEW.tenant_id
      AND entity.workspace_id=NEW.workspace_id
      AND entity.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND entity.entity_type='documentation_map'
  ) THEN RAISE EXCEPTION 'documentation map entity mismatch'; END IF;
  IF NEW.owner_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership membership
    WHERE membership.tenant_id=NEW.tenant_id AND membership.user_id=NEW.owner_id
  ) THEN RAISE EXCEPTION 'documentation map owner mismatch'; END IF;
  IF NEW.current_revision_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_documentationmaprevision revision
    WHERE revision.id=NEW.current_revision_id AND revision.documentation_map_id=NEW.id
      AND revision.tenant_id=NEW.tenant_id AND revision.workspace_id=NEW.workspace_id
      AND revision.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'documentation map current revision mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_documentation_map_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_documentationmap map
    WHERE map.id=NEW.documentation_map_id AND map.tenant_id=NEW.tenant_id
      AND map.workspace_id=NEW.workspace_id
      AND map.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'documentation map revision scope mismatch'; END IF;
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_documentationmaprevision parent
    WHERE parent.id=NEW.parent_id AND parent.documentation_map_id=NEW.documentation_map_id
      AND parent.revision_number + 1=NEW.revision_number
  ) THEN RAISE EXCEPTION 'documentation map revision parent mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership membership
    WHERE membership.tenant_id=NEW.tenant_id AND membership.user_id=NEW.created_by_id
  ) THEN RAISE EXCEPTION 'documentation map revision creator mismatch'; END IF;
  IF NEW.audience='client_visible' AND NEW.organization_id IS NULL
  THEN RAISE EXCEPTION 'client documentation map requires organization'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_documentation_map_entry() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE revision_audience text; owner_map_id uuid;
BEGIN
  SELECT revision.audience, revision.documentation_map_id INTO revision_audience, owner_map_id
  FROM core_documentationmaprevision revision
  WHERE revision.id=NEW.revision_id AND revision.tenant_id=NEW.tenant_id
    AND revision.workspace_id=NEW.workspace_id
    AND revision.organization_id IS NOT DISTINCT FROM NEW.organization_id;
  IF revision_audience IS NULL THEN RAISE EXCEPTION 'documentation map entry revision mismatch'; END IF;
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_documentationmapentry parent
    WHERE parent.id=NEW.parent_id AND parent.revision_id=NEW.revision_id
  ) THEN RAISE EXCEPTION 'documentation map entry parent mismatch'; END IF;
  IF NEW.kind='document' AND (
    NEW.document_id IS NULL OR NEW.document_revision_id IS NOT NULL OR NEW.publication_id IS NOT NULL
    OR NEW.subordinate_map_id IS NOT NULL OR NEW.external_url <> ''
  ) THEN RAISE EXCEPTION 'documentation map live document target mismatch'; END IF;
  IF NEW.kind='document_revision' AND (
    NEW.document_id IS NULL OR NEW.document_revision_id IS NULL OR NEW.publication_id IS NOT NULL
    OR NEW.subordinate_map_id IS NOT NULL OR NEW.external_url <> ''
  ) THEN RAISE EXCEPTION 'documentation map document revision target mismatch'; END IF;
  IF NEW.kind='publication' AND (
    NEW.publication_id IS NULL OR NEW.document_id IS NOT NULL OR NEW.document_revision_id IS NOT NULL
    OR NEW.subordinate_map_id IS NOT NULL OR NEW.external_url <> ''
  ) THEN RAISE EXCEPTION 'documentation map publication target mismatch'; END IF;
  IF NEW.kind='map' AND (
    NEW.subordinate_map_id IS NULL OR NEW.document_id IS NOT NULL OR NEW.document_revision_id IS NOT NULL
    OR NEW.publication_id IS NOT NULL OR NEW.external_url <> ''
  ) THEN RAISE EXCEPTION 'documentation map subordinate target mismatch'; END IF;
  IF NEW.kind='external' AND (
    NEW.external_url='' OR NEW.document_id IS NOT NULL OR NEW.document_revision_id IS NOT NULL
    OR NEW.publication_id IS NOT NULL OR NEW.subordinate_map_id IS NOT NULL
  ) THEN RAISE EXCEPTION 'documentation map external target mismatch'; END IF;
  IF NEW.document_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_document document JOIN core_entity entity ON entity.id=document.entity_id
    WHERE document.id=NEW.document_id AND document.tenant_id=NEW.tenant_id
      AND document.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND entity.workspace_id=NEW.workspace_id
  ) THEN RAISE EXCEPTION 'documentation map document scope mismatch'; END IF;
  IF NEW.document_revision_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_blockrevision block_revision
    JOIN core_block block ON block.id=block_revision.block_id
    WHERE block_revision.id=NEW.document_revision_id AND block.source_document_id=NEW.document_id
      AND block_revision.tenant_id=NEW.tenant_id
      AND block_revision.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'documentation map document revision scope mismatch'; END IF;
  IF NEW.publication_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_documentpublication publication
    JOIN core_document document ON document.id=publication.document_id
    JOIN core_entity entity ON entity.id=document.entity_id
    WHERE publication.id=NEW.publication_id AND publication.tenant_id=NEW.tenant_id
      AND publication.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND entity.workspace_id=NEW.workspace_id
      AND (revision_audience <> 'client_visible' OR publication.audience='client_visible')
  ) THEN RAISE EXCEPTION 'documentation map publication scope mismatch'; END IF;
  IF NEW.subordinate_map_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_documentationmap subordinate
    JOIN core_documentationmaprevision current ON current.id=subordinate.current_revision_id
    WHERE subordinate.id=NEW.subordinate_map_id AND subordinate.id <> owner_map_id
      AND subordinate.tenant_id=NEW.tenant_id AND subordinate.workspace_id=NEW.workspace_id
      AND subordinate.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND (revision_audience <> 'client_visible' OR current.audience='client_visible')
  ) THEN RAISE EXCEPTION 'documentation map subordinate scope mismatch'; END IF;
  IF revision_audience='client_visible' AND NEW.kind NOT IN ('publication', 'map')
  THEN RAISE EXCEPTION 'client documentation map entry kind mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_documentation_map_baseline() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_documentationmap map
    JOIN core_documentationmaprevision revision ON revision.id=NEW.revision_id
    WHERE map.id=NEW.documentation_map_id AND revision.documentation_map_id=map.id
      AND map.tenant_id=NEW.tenant_id AND map.workspace_id=NEW.workspace_id
      AND map.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'documentation map baseline scope mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership membership
    WHERE membership.tenant_id=NEW.tenant_id AND membership.user_id=NEW.created_by_id
  ) THEN RAISE EXCEPTION 'documentation map baseline creator mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_documentation_map_retained() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'documentation map retained records are immutable';
END $$;

CREATE TRIGGER core_docmap_validate BEFORE INSERT OR UPDATE ON core_documentationmap
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_documentation_map();
CREATE TRIGGER core_docmaprev_validate BEFORE INSERT ON core_documentationmaprevision
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_documentation_map_revision();
CREATE TRIGGER core_docmapentry_validate BEFORE INSERT ON core_documentationmapentry
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_documentation_map_entry();
CREATE TRIGGER core_docmapbase_validate BEFORE INSERT ON core_documentationmapbaseline
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_documentation_map_baseline();
CREATE TRIGGER core_docmaprev_retained BEFORE UPDATE OR DELETE ON core_documentationmaprevision
FOR EACH ROW EXECUTE FUNCTION tekdocs_documentation_map_retained();
CREATE TRIGGER core_docmapentry_retained BEFORE UPDATE OR DELETE ON core_documentationmapentry
FOR EACH ROW EXECUTE FUNCTION tekdocs_documentation_map_retained();
CREATE TRIGGER core_docmapbase_retained BEFORE UPDATE OR DELETE ON core_documentationmapbaseline
FOR EACH ROW EXECUTE FUNCTION tekdocs_documentation_map_retained();

DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'core_documentationmap', 'core_documentationmaprevision',
    'core_documentationmapentry', 'core_documentationmapbaseline'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY %I_runtime_scope ON %I '
      'USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id)) '
      'WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))',
      table_name, table_name);
  END LOOP;
END $$;
"""

REVERSE_SQL = r"""
DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'core_documentationmap', 'core_documentationmaprevision',
    'core_documentationmapentry', 'core_documentationmapbaseline'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_runtime_scope ON %I', table_name, table_name);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;
DROP TRIGGER IF EXISTS core_docmapbase_retained ON core_documentationmapbaseline;
DROP TRIGGER IF EXISTS core_docmapentry_retained ON core_documentationmapentry;
DROP TRIGGER IF EXISTS core_docmaprev_retained ON core_documentationmaprevision;
DROP TRIGGER IF EXISTS core_docmapbase_validate ON core_documentationmapbaseline;
DROP TRIGGER IF EXISTS core_docmapentry_validate ON core_documentationmapentry;
DROP TRIGGER IF EXISTS core_docmaprev_validate ON core_documentationmaprevision;
DROP TRIGGER IF EXISTS core_docmap_validate ON core_documentationmap;
DROP FUNCTION IF EXISTS tekdocs_documentation_map_retained();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_baseline();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_entry();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_revision();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0132_import_framework"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationMap",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_record",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_maps",
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_documentation_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="documentation_maps", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_maps",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("entity__display_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="DocumentationMapRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=240)),
                ("purpose", models.CharField(blank=True, max_length=1000)),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("operating_manual", "Operating manual"),
                            ("disaster_recovery", "Disaster recovery book"),
                            ("onboarding", "Onboarding pack"),
                            ("compliance", "Compliance binder"),
                            ("handoff", "Handoff package"),
                            ("general", "General documentation set"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("msp_internal", "MSP internal"), ("client_visible", "Client visible")], max_length=24
                    ),
                ),
                ("content_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documentation_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="core.documentationmap",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_revisions",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="core.documentationmaprevision",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_revisions",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_revisions",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("revision_number", "id"),
            },
        ),
        migrations.CreateModel(
            name="DocumentationMapEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "Live document"),
                            ("document_revision", "Exact document revision"),
                            ("publication", "STATIC publication"),
                            ("map", "Subordinate map"),
                            ("external", "External resource"),
                        ],
                        max_length=24,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=240)),
                ("external_url", models.URLField(blank=True, max_length=1000)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.document",
                    ),
                ),
                (
                    "document_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.blockrevision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.documentationmapentry",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.documentpublication",
                    ),
                ),
                (
                    "subordinate_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_map_entries",
                        to="core.documentationmap",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_entries",
                        to="core.workspace",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="core.documentationmaprevision",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="DocumentationMapBaseline",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("manifest", models.JSONField()),
                ("content_digest", models.CharField(max_length=64)),
                ("byte_size", models.PositiveBigIntegerField()),
                (
                    "artifact",
                    models.FileField(max_length=500, upload_to=apps.core.models.documentation_map_baseline_upload_to),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_baselines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documentation_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baselines",
                        to="core.documentationmap",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_baselines",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_baselines",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentation_map_baselines",
                        to="core.workspace",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baselines",
                        to="core.documentationmaprevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="documentationmap",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_maps",
                to="core.documentationmaprevision",
            ),
        ),
        migrations.AddIndex(
            model_name="documentationmaprevision",
            index=models.Index(
                fields=["workspace", "documentation_map", "revision_number"], name="core_docmaprev_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmaprevision",
            constraint=models.UniqueConstraint(
                fields=("documentation_map", "revision_number"), name="documentation_map_revision_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmaprevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "map_type__in",
                        ["operating_manual", "disaster_recovery", "onboarding", "compliance", "handoff", "general"],
                    )
                ),
                name="documentation_map_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmaprevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("audience__in", ["msp_internal", "client_visible"])),
                name="documentation_map_audience_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmaprevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_digest__regex", "^[0-9a-f]{64}$")),
                name="documentation_map_revision_digest_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="documentationmapentry",
            index=models.Index(
                fields=["workspace", "revision", "parent", "position"], name="core_docmapentry_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmapentry",
            constraint=models.UniqueConstraint(
                fields=("revision", "parent", "position"), name="documentation_map_entry_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmapentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["document", "document_revision", "publication", "map", "external"])),
                name="documentation_map_entry_kind_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="documentationmapbaseline",
            index=models.Index(
                fields=["workspace", "documentation_map", "created_at"], name="core_docmapbase_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationmapbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_digest__regex", "^[0-9a-f]{64}$")),
                name="documentation_map_baseline_digest_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="documentationmap",
            index=models.Index(fields=["workspace", "archived_at"], name="core_docmap_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentationmap",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_state__in", ["unreviewed", "pending", "approved", "changes_requested"])),
                name="documentation_map_review_valid",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
