# Generated by Django 5.2.17 on 2026-09-02 02:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_taxonomy() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='UPDATE' AND (NEW.tenant_id<>OLD.tenant_id OR NEW.key<>OLD.key OR NEW.binding<>OLD.binding)
  THEN RAISE EXCEPTION 'taxonomy identity is immutable'; END IF;
  IF NEW.current_version_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_taxonomyversion version
    WHERE version.id=NEW.current_version_id AND version.taxonomy_id=NEW.id AND version.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'taxonomy current version mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_taxonomy_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_taxonomy taxonomy
    WHERE taxonomy.id=NEW.taxonomy_id AND taxonomy.tenant_id=NEW.tenant_id
  )
  THEN RAISE EXCEPTION 'taxonomy version scope mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership membership
    WHERE membership.tenant_id=NEW.tenant_id AND membership.user_id=NEW.created_by_id
  )
  THEN RAISE EXCEPTION 'taxonomy version creator mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_taxonomy_term() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_taxonomyversion version
    WHERE version.id=NEW.version_id AND version.taxonomy_id=NEW.taxonomy_id AND version.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'taxonomy term version mismatch'; END IF;
  IF NEW.parent_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_taxonomyterm parent
    WHERE parent.id=NEW.parent_id AND parent.version_id=NEW.version_id AND parent.taxonomy_id=NEW.taxonomy_id
  ) THEN RAISE EXCEPTION 'taxonomy term parent mismatch'; END IF;
  IF jsonb_typeof(NEW.aliases) <> 'array' OR EXISTS (
    SELECT 1 FROM jsonb_array_elements(NEW.aliases) alias WHERE jsonb_typeof(alias) <> 'string'
  ) THEN RAISE EXCEPTION 'taxonomy aliases must be strings'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_document_taxonomy_term() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_document document
    WHERE document.id=NEW.document_id AND document.tenant_id=NEW.tenant_id
      AND document.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'document taxonomy assignment scope mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_taxonomy taxonomy JOIN core_taxonomyterm term ON term.taxonomy_id=taxonomy.id
    WHERE taxonomy.id=NEW.taxonomy_id AND taxonomy.tenant_id=NEW.tenant_id
      AND taxonomy.archived_at IS NULL AND taxonomy.binding='document_tags'
      AND term.id=NEW.term_id AND term.tenant_id=NEW.tenant_id
      AND term.version_id=taxonomy.current_version_id AND term.status='active'
  ) THEN RAISE EXCEPTION 'document taxonomy term mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_taxonomy_retained() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'taxonomy version records are immutable';
END $$;

CREATE TRIGGER core_taxonomy_validate BEFORE INSERT OR UPDATE ON core_taxonomy
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_taxonomy();
CREATE TRIGGER core_taxonomyversion_validate BEFORE INSERT ON core_taxonomyversion
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_taxonomy_version();
CREATE TRIGGER core_taxonomyterm_validate BEFORE INSERT ON core_taxonomyterm
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_taxonomy_term();
CREATE TRIGGER core_documenttaxonomyterm_validate BEFORE INSERT OR UPDATE ON core_documenttaxonomyterm
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_document_taxonomy_term();
CREATE TRIGGER core_taxonomyversion_retained BEFORE UPDATE OR DELETE ON core_taxonomyversion
FOR EACH ROW EXECUTE FUNCTION tekdocs_taxonomy_retained();
CREATE TRIGGER core_taxonomyterm_retained BEFORE UPDATE OR DELETE ON core_taxonomyterm
FOR EACH ROW EXECUTE FUNCTION tekdocs_taxonomy_retained();

DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_taxonomy', 'core_taxonomyversion', 'core_taxonomyterm'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY %I_runtime_scope ON %I '
      'USING (tenant_id=tekdocs_current_tenant_id()) '
      'WITH CHECK (tenant_id=tekdocs_current_tenant_id())',
      table_name, table_name
    );
  END LOOP;
END $$;
ALTER TABLE core_documenttaxonomyterm ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_documenttaxonomyterm FORCE ROW LEVEL SECURITY;
CREATE POLICY core_documenttaxonomyterm_runtime_scope ON core_documenttaxonomyterm
USING (tekdocs_scope_matches(tenant_id, organization_id))
WITH CHECK (tekdocs_scope_matches(tenant_id, organization_id));
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_documenttaxonomyterm_runtime_scope ON core_documenttaxonomyterm;
ALTER TABLE core_documenttaxonomyterm NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_documenttaxonomyterm DISABLE ROW LEVEL SECURITY;
DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_taxonomy', 'core_taxonomyversion', 'core_taxonomyterm'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_runtime_scope ON %I', table_name, table_name);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;
DROP TRIGGER IF EXISTS core_taxonomyterm_retained ON core_taxonomyterm;
DROP TRIGGER IF EXISTS core_taxonomyversion_retained ON core_taxonomyversion;
DROP TRIGGER IF EXISTS core_documenttaxonomyterm_validate ON core_documenttaxonomyterm;
DROP TRIGGER IF EXISTS core_taxonomyterm_validate ON core_taxonomyterm;
DROP TRIGGER IF EXISTS core_taxonomyversion_validate ON core_taxonomyversion;
DROP TRIGGER IF EXISTS core_taxonomy_validate ON core_taxonomy;
DROP FUNCTION IF EXISTS tekdocs_taxonomy_retained();
DROP FUNCTION IF EXISTS tekdocs_validate_document_taxonomy_term();
DROP FUNCTION IF EXISTS tekdocs_validate_taxonomy_term();
DROP FUNCTION IF EXISTS tekdocs_validate_taxonomy_version();
DROP FUNCTION IF EXISTS tekdocs_validate_taxonomy();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0135_expand_document_topic_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80)),
                (
                    "binding",
                    models.CharField(
                        choices=[
                            ("document_tags", "Document tags"),
                            ("technology", "Technology"),
                            ("service_family", "Service family"),
                            ("platform", "Platform"),
                            ("risk_level", "Risk level"),
                            ("support_tier", "Support tier"),
                            ("compliance_domain", "Compliance domain"),
                            ("document_subject", "Document subject"),
                        ],
                        max_length=40,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="taxonomies", to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxonomyVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("allow_local_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_taxonomy_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="core.taxonomy"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="taxonomy_versions", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("taxonomy_id", "version"),
            },
        ),
        migrations.CreateModel(
            name="TaxonomyTerm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stable_key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("aliases", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")], default="active", max_length=16
                    ),
                ),
                ("replacement_key", models.SlugField(blank=True, max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.taxonomyterm",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="terms", to="core.taxonomy"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="taxonomy_terms", to="core.tenant"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="terms", to="core.taxonomyversion"
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "label", "stable_key"),
            },
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for",
                to="core.taxonomyversion",
            ),
        ),
        migrations.CreateModel(
            name="DocumentTaxonomyTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="taxonomy_terms", to="core.document"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_taxonomy_terms",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_taxonomy_terms",
                        to="core.tenant",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_assignments",
                        to="core.taxonomy",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_assignments",
                        to="core.taxonomyterm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "organization", "document"], name="core_doc_taxonomy_scope_idx"),
                    models.Index(fields=["tenant", "taxonomy", "term"], name="core_doc_taxonomy_term_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "taxonomy", "term"), name="unique_document_taxonomy_term"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taxonomyversion",
            constraint=models.UniqueConstraint(fields=("taxonomy", "version"), name="unique_taxonomy_version"),
        ),
        migrations.AddConstraint(
            model_name="taxonomyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="taxonomy_version_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomyterm",
            index=models.Index(fields=["tenant", "taxonomy", "version"], name="core_taxonomy_term_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="taxonomyterm",
            constraint=models.UniqueConstraint(
                fields=("version", "stable_key"), name="unique_term_key_per_taxonomy_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonomyterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "retired"])), name="taxonomy_term_status_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=models.Index(fields=["tenant", "binding", "archived_at"], name="core_taxonomy_binding_idx"),
        ),
        migrations.AddConstraint(
            model_name="taxonomy",
            constraint=models.UniqueConstraint(fields=("tenant", "key"), name="unique_taxonomy_key_per_tenant"),
        ),
        migrations.AddConstraint(
            model_name="taxonomy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "binding__in",
                        [
                            "document_tags",
                            "technology",
                            "service_family",
                            "platform",
                            "risk_level",
                            "support_tier",
                            "compliance_domain",
                            "document_subject",
                        ],
                    )
                ),
                name="taxonomy_binding_valid",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
