# Generated by Django 5.2.17 on 2026-09-02 02:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_local_taxonomy_term() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_organization organization
    WHERE organization.id=NEW.organization_id AND organization.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'local taxonomy organization scope mismatch'; END IF;
  IF NEW.archived_at IS NULL AND NOT EXISTS (
    SELECT 1 FROM core_taxonomy taxonomy
    JOIN core_taxonomyversion version ON version.id=NEW.taxonomy_version_id
    WHERE taxonomy.id=NEW.taxonomy_id AND taxonomy.tenant_id=NEW.tenant_id
      AND taxonomy.current_version_id=version.id AND version.taxonomy_id=taxonomy.id
      AND version.allow_local_terms AND taxonomy.archived_at IS NULL
  ) THEN RAISE EXCEPTION 'local taxonomy term is not permitted'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership membership
    WHERE membership.tenant_id=NEW.tenant_id AND membership.user_id=NEW.created_by_id
  ) THEN RAISE EXCEPTION 'local taxonomy term creator mismatch'; END IF;
  IF jsonb_typeof(NEW.aliases) <> 'array' OR EXISTS (
    SELECT 1 FROM jsonb_array_elements(NEW.aliases) alias WHERE jsonb_typeof(alias) <> 'string'
  ) THEN RAISE EXCEPTION 'local taxonomy aliases must be strings'; END IF;
  IF TG_OP='UPDATE' AND (
    NEW.tenant_id<>OLD.tenant_id OR NEW.organization_id<>OLD.organization_id
    OR NEW.taxonomy_id<>OLD.taxonomy_id OR NEW.stable_key<>OLD.stable_key
  ) THEN RAISE EXCEPTION 'local taxonomy term identity is immutable'; END IF;
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_document_taxonomy_term() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_document document
    WHERE document.id=NEW.document_id AND document.tenant_id=NEW.tenant_id
      AND document.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'document taxonomy assignment scope mismatch'; END IF;
  IF NEW.term_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_taxonomy taxonomy JOIN core_taxonomyterm term ON term.taxonomy_id=taxonomy.id
    WHERE taxonomy.id=NEW.taxonomy_id AND taxonomy.tenant_id=NEW.tenant_id
      AND taxonomy.archived_at IS NULL AND taxonomy.binding='document_tags'
      AND term.id=NEW.term_id AND term.tenant_id=NEW.tenant_id
      AND term.version_id=taxonomy.current_version_id AND term.status='active'
  ) THEN RAISE EXCEPTION 'document taxonomy term mismatch'; END IF;
  IF NEW.local_term_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_organizationtaxonomyterm local_term
    JOIN core_taxonomy taxonomy ON taxonomy.id=local_term.taxonomy_id
    JOIN core_taxonomyversion version ON version.id=local_term.taxonomy_version_id
    WHERE local_term.id=NEW.local_term_id AND local_term.tenant_id=NEW.tenant_id
      AND local_term.organization_id=NEW.organization_id AND local_term.taxonomy_id=NEW.taxonomy_id
      AND local_term.archived_at IS NULL AND taxonomy.current_version_id=version.id
      AND taxonomy.archived_at IS NULL AND taxonomy.binding='document_tags' AND version.allow_local_terms
  ) THEN RAISE EXCEPTION 'document local taxonomy term mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER core_organizationtaxonomyterm_validate
BEFORE INSERT OR UPDATE ON core_organizationtaxonomyterm
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_local_taxonomy_term();
ALTER TABLE core_organizationtaxonomyterm ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_organizationtaxonomyterm FORCE ROW LEVEL SECURITY;
CREATE POLICY core_organizationtaxonomyterm_runtime_scope ON core_organizationtaxonomyterm
USING (tekdocs_scope_matches(tenant_id, organization_id))
WITH CHECK (tekdocs_scope_matches(tenant_id, organization_id));
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_organizationtaxonomyterm_runtime_scope ON core_organizationtaxonomyterm;
ALTER TABLE core_organizationtaxonomyterm NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_organizationtaxonomyterm DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_organizationtaxonomyterm_validate ON core_organizationtaxonomyterm;
DROP FUNCTION IF EXISTS tekdocs_validate_local_taxonomy_term();
CREATE OR REPLACE FUNCTION tekdocs_validate_document_taxonomy_term() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_document document
    WHERE document.id=NEW.document_id AND document.tenant_id=NEW.tenant_id
      AND document.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'document taxonomy assignment scope mismatch'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_taxonomy taxonomy JOIN core_taxonomyterm term ON term.taxonomy_id=taxonomy.id
    WHERE taxonomy.id=NEW.taxonomy_id AND taxonomy.tenant_id=NEW.tenant_id
      AND taxonomy.archived_at IS NULL AND taxonomy.binding='document_tags'
      AND term.id=NEW.term_id AND term.tenant_id=NEW.tenant_id
      AND term.version_id=taxonomy.current_version_id AND term.status='active'
  ) THEN RAISE EXCEPTION 'document taxonomy term mismatch'; END IF;
  RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0136_controlled_taxonomies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTaxonomyTerm",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stable_key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("label", "stable_key"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="documenttaxonomyterm",
            name="unique_document_taxonomy_term",
        ),
        migrations.AlterField(
            model_name="documenttaxonomyterm",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_assignments",
                to="core.taxonomyterm",
            ),
        ),
        migrations.AddField(
            model_name="organizationtaxonomyterm",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_organization_taxonomy_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationtaxonomyterm",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_taxonomy_terms",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationtaxonomyterm",
            name="taxonomy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="organization_terms", to="core.taxonomy"
            ),
        ),
        migrations.AddField(
            model_name="organizationtaxonomyterm",
            name="taxonomy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_terms",
                to="core.taxonomyversion",
            ),
        ),
        migrations.AddField(
            model_name="organizationtaxonomyterm",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_taxonomy_terms",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="documenttaxonomyterm",
            name="local_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_assignments",
                to="core.organizationtaxonomyterm",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttaxonomyterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("local_term__isnull", True), ("term__isnull", False)),
                    models.Q(("local_term__isnull", False), ("term__isnull", True)),
                    _connector="OR",
                ),
                name="document_taxonomy_exactly_one_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttaxonomyterm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("term__isnull", False)),
                fields=("document", "taxonomy", "term"),
                name="unique_document_taxonomy_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttaxonomyterm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("local_term__isnull", False)),
                fields=("document", "taxonomy", "local_term"),
                name="unique_document_local_taxonomy_term",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationtaxonomyterm",
            index=models.Index(
                fields=["tenant", "organization", "taxonomy", "archived_at"], name="core_local_taxonomy_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationtaxonomyterm",
            constraint=models.UniqueConstraint(
                fields=("organization", "taxonomy", "stable_key"), name="unique_local_term_key_per_taxonomy"
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
