# Generated by Django 5.2.17 on 2026-09-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_invoice_lifecycle_handoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='health_status',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='last_successful_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='reconciliation_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrationobservation',
            name='provenance',
            field=models.CharField(default='provider_api', max_length=32),
        ),
        migrations.AddField(
            model_name='integrationobservation',
            name='safe_projection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='integrationobservation',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='integrationobservation',
            name='source_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.CheckConstraint(
                condition=models.Q(('health_status__in', ('unknown', 'healthy', 'degraded', 'failing', 'paused'))),
                name='integration_connection_health_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='integrationobservation',
            constraint=models.CheckConstraint(
                condition=models.Q(('schema_version__gte', 1)),
                name='integration_observation_schema_valid',
            ),
        ),
    ]
