# Generated by Django 5.2.17 on 2026-09-03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_provider_neutral_contract"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="integrationconflict",
            name="integration_conflict_difference_valid",
        ),
        migrations.AddField(
            model_name="integrationobservation",
            name="state",
            field=models.CharField(default="observed", max_length=16),
        ),
        migrations.AddField(
            model_name="integrationsyncjob",
            name="sync_run_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="integrationsyncjob",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("dead_letter", "Dead letter"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(difference__in=("unmatched", "changed", "retired_remote")),
                name="integration_conflict_difference_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(state__in=("observed", "retired")),
                name="integration_observation_state_valid",
            ),
        ),
    ]
