# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0140_integration_sync_controls")]

    operations = [
        migrations.RemoveConstraint(
            model_name="integrationconnection",
            name="integration_provider_valid",
        ),
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider",
            field=models.CharField(
                choices=[("netbox", "NetBox"), ("microsoft_graph", "Microsoft 365")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="integrationsyncjob",
            name="cursor_before",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="integrationsyncjob",
            name="cursor_after",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(provider__in=("netbox", "microsoft_graph")),
                name="integration_provider_valid",
            ),
        ),
    ]
