# Generated by Django 5.2.17 on 2026-09-03

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_integration_mapping() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM core_integrationconnection c WHERE c.id=NEW.connection_id
    AND c.tenant_id=NEW.tenant_id AND c.workspace_id=NEW.workspace_id
    AND c.organization_id IS NOT DISTINCT FROM NEW.organization_id)
  THEN RAISE EXCEPTION 'integration mapping connection scope mismatch'; END IF;
  IF NOT EXISTS (SELECT 1 FROM core_entity e WHERE e.id=NEW.local_entity_id AND e.tenant_id=NEW.tenant_id)
  THEN RAISE EXCEPTION 'integration mapping entity tenant mismatch'; END IF;
  IF TG_OP='UPDATE' AND
    (OLD.tenant_id, OLD.workspace_id, OLD.organization_id, OLD.connection_id,
      OLD.remote_type, OLD.remote_id, OLD.local_entity_id)
    IS DISTINCT FROM
    (NEW.tenant_id, NEW.workspace_id, NEW.organization_id, NEW.connection_id,
      NEW.remote_type, NEW.remote_id, NEW.local_entity_id)
  THEN RAISE EXCEPTION 'integration mapping identity is immutable'; END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER core_intmap_validate BEFORE INSERT OR UPDATE ON core_integrationentitymapping
  FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_integration_mapping();
ALTER TABLE core_integrationentitymapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_integrationentitymapping FORCE ROW LEVEL SECURITY;
CREATE POLICY core_integrationentitymapping_runtime_scope ON core_integrationentitymapping
  USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))
  WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id));
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_integrationentitymapping_runtime_scope ON core_integrationentitymapping;
ALTER TABLE core_integrationentitymapping DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_intmap_validate ON core_integrationentitymapping;
DROP FUNCTION IF EXISTS tekdocs_validate_integration_mapping();
"""


class Migration(migrations.Migration):
    dependencies = [("core", "0141_microsoft_graph_provider")]

    operations = [
        migrations.RemoveConstraint(model_name="integrationconnection", name="integration_provider_valid"),
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider",
            field=models.CharField(
                choices=[("netbox", "NetBox"), ("microsoft_graph", "Microsoft 365"), ("halopsa", "HaloPSA")],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(provider__in=("netbox", "microsoft_graph", "halopsa")),
                name="integration_provider_valid",
            ),
        ),
        migrations.CreateModel(
            name="IntegrationEntityMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remote_type", models.CharField(max_length=64)),
                ("remote_id", models.CharField(max_length=160)),
                ("observed_fingerprint", models.CharField(max_length=64)),
                ("last_observed_at", models.DateTimeField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_mappings",
                        to="core.integrationconnection",
                    ),
                ),
                (
                    "local_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_mappings",
                        to="core.entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_entity_mappings",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_entity_mappings",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_entity_mappings",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("remote_type", "remote_id", "id")},
        ),
        migrations.AddConstraint(
            model_name="integrationentitymapping",
            constraint=models.UniqueConstraint(
                fields=("connection", "remote_type", "remote_id"), name="integration_entity_mapping_remote_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationentitymapping",
            constraint=models.CheckConstraint(
                condition=models.Q(observed_fingerprint__regex=r"^[0-9a-f]{64}$"),
                name="integration_entity_mapping_digest_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationentitymapping",
            index=models.Index(fields=["workspace", "local_entity"], name="core_intmap_local_idx"),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
