# Generated by Django 5.2.17 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_integration_conflict_suggestion() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.suggested_local_entity_id IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM core_entity e
      WHERE e.id=NEW.suggested_local_entity_id AND e.tenant_id=NEW.tenant_id)
  THEN RAISE EXCEPTION 'integration conflict suggestion tenant mismatch'; END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER core_intconf_suggestion_validate
  BEFORE INSERT OR UPDATE ON core_integrationconflict
  FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_integration_conflict_suggestion();
"""

REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS core_intconf_suggestion_validate ON core_integrationconflict;
DROP FUNCTION IF EXISTS tekdocs_validate_integration_conflict_suggestion();
"""


class Migration(migrations.Migration):
    dependencies = [("core", "0142_halopsa_provider")]

    operations = [
        migrations.RemoveConstraint(model_name="integrationconnection", name="integration_provider_valid"),
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("netbox", "NetBox"),
                    ("microsoft_graph", "Microsoft 365"),
                    ("halopsa", "HaloPSA"),
                    ("ninjaone", "NinjaOne"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(provider__in=("netbox", "microsoft_graph", "halopsa", "ninjaone")),
                name="integration_provider_valid",
            ),
        ),
        migrations.AddField(
            model_name="integrationconflict",
            name="suggested_local_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggested_integration_conflicts",
                to="core.entity",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
