# Generated by Django 5.2.17 on 2026-09-05

from importlib import import_module

from django.db import migrations

REMOVE_DATABASE_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS core_docmapbase_retained ON core_documentationmapbaseline;
DROP TRIGGER IF EXISTS core_docmapentry_retained ON core_documentationmapentry;
DROP TRIGGER IF EXISTS core_docmaprev_retained ON core_documentationmaprevision;
DROP TRIGGER IF EXISTS core_docmapbase_validate ON core_documentationmapbaseline;
DROP TRIGGER IF EXISTS core_docmapentry_validate ON core_documentationmapentry;
DROP TRIGGER IF EXISTS core_docmaprev_validate ON core_documentationmaprevision;
DROP TRIGGER IF EXISTS core_docmap_validate ON core_documentationmap;
DROP FUNCTION IF EXISTS tekdocs_documentation_map_retained();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_baseline();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_entry();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map_revision();
DROP FUNCTION IF EXISTS tekdocs_validate_documentation_map();
"""

# Reversing restores the exact guards and row policies originally installed by 0133.
RESTORE_DATABASE_GUARDS_SQL = import_module(
    "apps.core.migrations.0133_documentationmap_documentationmaprevision_and_more"
).FORWARD_SQL


class Migration(migrations.Migration):
    dependencies = [("core", "0143_ninjaone_provider")]

    operations = [
        migrations.RunSQL(REMOVE_DATABASE_GUARDS_SQL, RESTORE_DATABASE_GUARDS_SQL),
        migrations.RemoveIndex(model_name="documentationmaprevision", name="core_docmaprev_scope_idx"),
        migrations.RemoveConstraint(model_name="documentationmaprevision", name="documentation_map_revision_unique"),
        migrations.RemoveConstraint(model_name="documentationmaprevision", name="documentation_map_type_valid"),
        migrations.RemoveConstraint(model_name="documentationmaprevision", name="documentation_map_audience_valid"),
        migrations.RemoveConstraint(
            model_name="documentationmaprevision", name="documentation_map_revision_digest_valid"
        ),
        migrations.RemoveIndex(model_name="documentationmapentry", name="core_docmapentry_scope_idx"),
        migrations.RemoveConstraint(model_name="documentationmapentry", name="documentation_map_entry_position_unique"),
        migrations.RemoveConstraint(model_name="documentationmapentry", name="documentation_map_entry_kind_valid"),
        migrations.RemoveIndex(model_name="documentationmapbaseline", name="core_docmapbase_scope_idx"),
        migrations.RemoveConstraint(
            model_name="documentationmapbaseline", name="documentation_map_baseline_digest_valid"
        ),
        migrations.RemoveField(model_name="documentationmapbaseline", name="documentation_map"),
        migrations.RemoveField(model_name="documentationmaprevision", name="documentation_map"),
        migrations.RemoveField(model_name="documentationmapentry", name="subordinate_map"),
        migrations.RemoveField(model_name="documentationmapbaseline", name="created_by"),
        migrations.RemoveField(model_name="documentationmapbaseline", name="organization"),
        migrations.RemoveField(model_name="documentationmapbaseline", name="revision"),
        migrations.RemoveField(model_name="documentationmapbaseline", name="tenant"),
        migrations.RemoveField(model_name="documentationmapbaseline", name="workspace"),
        migrations.RemoveField(model_name="documentationmapentry", name="document"),
        migrations.RemoveField(model_name="documentationmapentry", name="document_revision"),
        migrations.RemoveField(model_name="documentationmapentry", name="organization"),
        migrations.RemoveField(model_name="documentationmapentry", name="parent"),
        migrations.RemoveField(model_name="documentationmapentry", name="publication"),
        migrations.RemoveField(model_name="documentationmapentry", name="revision"),
        migrations.RemoveField(model_name="documentationmapentry", name="tenant"),
        migrations.RemoveField(model_name="documentationmapentry", name="workspace"),
        migrations.RemoveField(model_name="documentationmaprevision", name="created_by"),
        migrations.RemoveField(model_name="documentationmaprevision", name="organization"),
        migrations.RemoveField(model_name="documentationmaprevision", name="parent"),
        migrations.RemoveField(model_name="documentationmaprevision", name="tenant"),
        migrations.RemoveField(model_name="documentationmaprevision", name="workspace"),
        migrations.DeleteModel(name="DocumentationMap"),
        migrations.DeleteModel(name="DocumentationMapBaseline"),
        migrations.DeleteModel(name="DocumentationMapEntry"),
        migrations.DeleteModel(name="DocumentationMapRevision"),
    ]
