# Generated by Django 5.2.17 on 2026-09-05 15:51

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_stock_item() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'stock currency invalid'; END IF;
  IF NEW.vendor_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_organizationclassification classification
    WHERE classification.organization_id=NEW.vendor_id AND classification.tenant_id=NEW.tenant_id
      AND classification.kind='vendor'
  ) THEN RAISE EXCEPTION 'stock vendor scope invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_stock_item_scope_guard BEFORE INSERT OR UPDATE ON core_stockitem
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_stock_item();

CREATE FUNCTION tekdocs_validate_stock_movement() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_stockitem item WHERE item.id=NEW.stock_item_id AND item.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'stock movement item scope invalid'; END IF;
  IF NEW.client_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_organizationclassification classification
    WHERE classification.organization_id=NEW.client_id AND classification.tenant_id=NEW.tenant_id
      AND classification.kind='client'
  ) THEN RAISE EXCEPTION 'stock movement client scope invalid'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM accounts_tenantmembership member
    WHERE member.tenant_id=NEW.tenant_id AND member.user_id=NEW.actor_id
  ) THEN RAISE EXCEPTION 'stock movement actor scope invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_stock_movement_scope_guard BEFORE INSERT ON core_stockmovement
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_stock_movement();

CREATE FUNCTION tekdocs_retain_stock_movement() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'stock movements are immutable and retained';
END $$;
CREATE TRIGGER core_stock_movement_retain BEFORE UPDATE OR DELETE ON core_stockmovement
FOR EACH ROW EXECUTE FUNCTION tekdocs_retain_stock_movement();

DROP TRIGGER core_invoice_line_guard ON core_invoiceline;
DROP FUNCTION tekdocs_validate_invoice_line();
CREATE FUNCTION tekdocs_validate_invoice_line() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_invoice invoice
    WHERE invoice.id=NEW.invoice_id AND invoice.tenant_id=NEW.tenant_id
      AND invoice.organization_id=NEW.organization_id AND invoice.currency=NEW.currency
      AND invoice.state='draft'
  ) THEN RAISE EXCEPTION 'invoice line scope or currency mismatch'; END IF;
  IF NEW.catalog_product_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_catalogproduct product
    WHERE product.id=NEW.catalog_product_id AND product.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line product origin scope mismatch'; END IF;
  IF NEW.service_rate_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_servicerate rate
    WHERE rate.id=NEW.service_rate_id AND rate.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line service-rate origin scope mismatch'; END IF;
  IF NEW.contract_cost_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contractcost cost
    WHERE cost.id=NEW.contract_cost_id AND cost.tenant_id=NEW.tenant_id
      AND cost.organization_id=NEW.organization_id
  ) THEN RAISE EXCEPTION 'invoice line contract-cost origin scope mismatch'; END IF;
  IF NEW.stock_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_stockitem item
    WHERE item.id=NEW.stock_item_id AND item.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line stock origin scope mismatch'; END IF;
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'invoice line currency invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_line_guard BEFORE INSERT OR UPDATE ON core_invoiceline
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_line();

ALTER TABLE core_stockitem ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_stockitem FORCE ROW LEVEL SECURITY;
CREATE POLICY core_stockitem_runtime_scope ON core_stockitem
USING (tenant_id=tekdocs_current_tenant_id()) WITH CHECK (tenant_id=tekdocs_current_tenant_id());
ALTER TABLE core_stockmovement ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_stockmovement FORCE ROW LEVEL SECURITY;
CREATE POLICY core_stockmovement_runtime_scope ON core_stockmovement
USING (tenant_id=tekdocs_current_tenant_id()) WITH CHECK (tenant_id=tekdocs_current_tenant_id());
"""


REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_stockmovement_runtime_scope ON core_stockmovement;
ALTER TABLE core_stockmovement NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_stockmovement DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS core_stockitem_runtime_scope ON core_stockitem;
ALTER TABLE core_stockitem NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_stockitem DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_stock_movement_retain ON core_stockmovement;
DROP FUNCTION IF EXISTS tekdocs_retain_stock_movement();
DROP TRIGGER IF EXISTS core_stock_movement_scope_guard ON core_stockmovement;
DROP FUNCTION IF EXISTS tekdocs_validate_stock_movement();
DROP TRIGGER IF EXISTS core_stock_item_scope_guard ON core_stockitem;
DROP FUNCTION IF EXISTS tekdocs_validate_stock_item();
DROP TRIGGER IF EXISTS core_invoice_line_guard ON core_invoiceline;
DROP FUNCTION IF EXISTS tekdocs_validate_invoice_line();
CREATE FUNCTION tekdocs_validate_invoice_line() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_invoice invoice
    WHERE invoice.id=NEW.invoice_id AND invoice.tenant_id=NEW.tenant_id
      AND invoice.organization_id=NEW.organization_id AND invoice.currency=NEW.currency
      AND invoice.state='draft'
  ) THEN RAISE EXCEPTION 'invoice line scope or currency mismatch'; END IF;
  IF NEW.catalog_product_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_catalogproduct product
    WHERE product.id=NEW.catalog_product_id AND product.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line product origin scope mismatch'; END IF;
  IF NEW.service_rate_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_servicerate rate
    WHERE rate.id=NEW.service_rate_id AND rate.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'invoice line service-rate origin scope mismatch'; END IF;
  IF NEW.contract_cost_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contractcost cost
    WHERE cost.id=NEW.contract_cost_id AND cost.tenant_id=NEW.tenant_id
      AND cost.organization_id=NEW.organization_id
  ) THEN RAISE EXCEPTION 'invoice line contract-cost origin scope mismatch'; END IF;
  IF NEW.currency !~ '^[A-Z]{3}$' THEN RAISE EXCEPTION 'invoice line currency invalid'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_invoice_line_guard BEFORE INSERT OR UPDATE ON core_invoiceline
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_invoice_line();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0144_remove_documentation_maps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("vendor_part_number", models.CharField(blank=True, max_length=120)),
                ("unit", models.CharField(default="each", max_length=32)),
                ("quantity_on_hand", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("reorder_level", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("cost_per_unit", models.DecimalField(decimal_places=6, max_digits=18)),
                ("client_price_per_unit", models.DecimalField(decimal_places=4, max_digits=18)),
                ("purchase_quantity", models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ("purchase_price", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("order_total", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("order_number", models.CharField(blank=True, max_length=120)),
                ("order_url", models.URLField(blank=True, max_length=1000)),
                ("ordered_on", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=160)),
                ("tracking_url", models.URLField(blank=True, max_length=1000)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("used", "Used at client"),
                            ("returned", "Returned to stock"),
                            ("correction", "Correction"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity_change", models.DecimalField(decimal_places=3, max_digits=15)),
                ("quantity_after", models.DecimalField(decimal_places=3, max_digits=15)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-occurred_at", "-recorded_at", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="invoiceline",
            name="invoice_line_one_origin",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_items", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplied_stock_items",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="core.stockitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("catalog_product__isnull", True),
                        ("contract_cost__isnull", True),
                        ("service_rate__isnull", True),
                    ),
                    models.Q(
                        ("catalog_product__isnull", True), ("service_rate__isnull", True), ("stock_item__isnull", True)
                    ),
                    models.Q(
                        ("catalog_product__isnull", True), ("contract_cost__isnull", True), ("stock_item__isnull", True)
                    ),
                    models.Q(
                        ("contract_cost__isnull", True), ("service_rate__isnull", True), ("stock_item__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="invoice_line_one_origin",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stock_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="core.stockitem"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="core.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["tenant", "archived_at", "name"], name="core_stockitem_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_on_hand__gte", 0)), name="stock_quantity_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reorder_level__isnull", True), ("reorder_level__gte", 0), _connector="OR"),
                name="stock_reorder_level_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost_per_unit__gte", 0)), name="stock_cost_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("client_price_per_unit__gte", 0)), name="stock_client_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                condition=models.Q(("archived_at__isnull", True)),
                name="stock_item_name_active_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "stock_item", "occurred_at"], name="core_stockmove_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_change", 0), _negated=True), name="stock_movement_change_nonzero"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_after__gte", 0)), name="stock_movement_after_nonnegative"
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
