# Generated by Django 5.2.17 on 2026-09-11 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_invoice_line_stock_consumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoiceSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('interval', models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('contract_cost', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_schedule', to='core.contractcost')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_schedules', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_schedules', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('due_days', models.PositiveSmallIntegerField(default=30)),
                ('source_digest', models.CharField(max_length=64)),
                ('source_snapshot', models.JSONField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_terms', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_terms', to='core.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='core.recurringinvoiceschedule')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxrate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_terms', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoicePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateField()),
                ('ends_before', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_period', to='core.invoice')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_period', to='core.invoiceline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_periods', to='core.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoice_periods', to='core.tenant')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='core.recurringinvoiceschedule')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='core.recurringinvoiceterms')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval__in', ('monthly', 'quarterly', 'annual'))), name='recurring_schedule_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('anchor')), _connector='OR'), name='recurring_schedule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceterms',
            constraint=models.UniqueConstraint(fields=('schedule', 'version'), name='recurring_terms_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceterms',
            constraint=models.CheckConstraint(condition=models.Q(('version', 1)), name='recurring_terms_initial_version_only'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceterms',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recurring_terms_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceterms',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0)), name='recurring_terms_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceterms',
            constraint=models.CheckConstraint(condition=models.Q(('due_days__lte', 3650)), name='recurring_terms_due_days_bounded'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceperiod',
            constraint=models.UniqueConstraint(fields=('schedule', 'starts_on'), name='recurring_period_once'),
        ),
        migrations.AddConstraint(
            model_name='recurringinvoiceperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_before__gt', models.F('starts_on'))), name='recurring_period_dates_valid'),
        ),
    ]
