# Generated by Django 5.2.17 on 2026-09-12 22:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Tenant/user scope deliberately ignores workspace: preferences follow the person.
# Trusted maintenance principals need access for upgrade and recovery workflows.
FORWARD_SQL = """
ALTER TABLE core_collectionpreference ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_collectionpreference FORCE ROW LEVEL SECURITY;
CREATE POLICY core_collectionpreference_runtime_scope ON core_collectionpreference
USING (tenant_id = tekdocs_current_tenant_id() AND
       (tekdocs_system_principal_active() OR user_id = tekdocs_current_user_id()))
WITH CHECK (tenant_id = tekdocs_current_tenant_id() AND
       (tekdocs_system_principal_active() OR user_id = tekdocs_current_user_id()));
"""
REVERSE_SQL = """
DROP POLICY IF EXISTS core_collectionpreference_runtime_scope ON core_collectionpreference;
ALTER TABLE core_collectionpreference NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_collectionpreference DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0148_recurring_invoice_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("feature", models.CharField(max_length=64)),
                ("columns", models.JSONField(default=list)),
                ("page_size", models.PositiveSmallIntegerField(default=25)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user", "feature"), name="collection_preference_owner_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("page_size__in", (25, 50, 100))), name="collection_preference_page_size"
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
