# Generated by Django 5.2.17 on 2026-10-03 16:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0161_invoice_corrections"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryCommit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "object_format",
                    models.CharField(choices=[("sha1", "SHA-1"), ("sha256", "SHA-256")], default="sha1", max_length=8),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("verified_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="repository_commits", to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceRepository",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("storage_relative_path", models.CharField(max_length=160, unique=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[("active", "Active"), ("read_only", "Read only"), ("retired", "Retired")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "health_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("blocked", "Blocked"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "last_reconciliation_state",
                    models.CharField(
                        choices=[
                            ("never", "Never reconciled"),
                            ("matched", "Matched"),
                            ("missing", "Accepted head missing"),
                            ("advanced", "Repository advanced"),
                            ("mismatched", "Head mismatched"),
                            ("unavailable", "Repository unavailable"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_by_repositories",
                        to="core.repositorycommit",
                    ),
                ),
                (
                    "indexed_commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indexed_by_repositories",
                        to="core.repositorycommit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace_repositories",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="repository", to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repositorycommit",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_commits",
                to="core.workspacerepository",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacerepository",
            index=models.Index(fields=["tenant", "lifecycle_state"], name="core_repo_tenant_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="workspacerepository",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("storage_relative_path__regex", "^repositories/[0-9a-f-]{36}\\.git$"),
                    models.Q(("storage_relative_path__contains", ".."), _negated=True),
                    models.Q(("storage_relative_path__contains", "\\"), _negated=True),
                ),
                name="workspace_repository_path_safe",
            ),
        ),
        migrations.AddIndex(
            model_name="repositorycommit",
            index=models.Index(fields=["tenant", "repository"], name="core_repocommit_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="repositorycommit",
            constraint=models.UniqueConstraint(
                fields=("repository", "object_format", "object_id"), name="repository_commit_object_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repositorycommit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("object_format", "sha1"), ("object_id__regex", "^[0-9a-f]{40}$")),
                    models.Q(("object_format", "sha256"), ("object_id__regex", "^[0-9a-f]{64}$")),
                    _connector="OR",
                ),
                name="repository_commit_object_id_valid",
            ),
        ),
    ]
