# Generated by Django 5.2.17 on 2026-10-05

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_content_node() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspacerepository repository
    JOIN core_workspace workspace ON workspace.id=repository.workspace_id
    WHERE repository.id=NEW.repository_id AND repository.tenant_id=NEW.tenant_id
      AND workspace.id=NEW.workspace_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND NEW.indexed_commit_id=repository.accepted_commit_id
  ) THEN RAISE EXCEPTION 'content node scope mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_content_child() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE parent_id uuid;
DECLARE linked_target_id uuid;
DECLARE linked_content_id uuid;
BEGIN
  parent_id := COALESCE(
    (to_jsonb(NEW)->>'source_id')::uuid,
    (to_jsonb(NEW)->>'node_id')::uuid
  );
  IF NOT EXISTS (
    SELECT 1 FROM core_contentnode node
    WHERE node.id=parent_id AND node.tenant_id=NEW.tenant_id
      AND node.workspace_id=NEW.workspace_id
      AND node.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'content projection child scope mismatch' USING ERRCODE='23514'; END IF;
  linked_target_id := (to_jsonb(NEW)->>'target_id')::uuid;
  linked_content_id := (to_jsonb(NEW)->>'target_content_id')::uuid;
  IF linked_target_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contentnode target
    WHERE target.id=linked_target_id
      AND target.repository_id=(SELECT repository_id FROM core_contentnode WHERE id=parent_id)
      AND target.content_id=linked_content_id
  ) THEN RAISE EXCEPTION 'content link target mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_content_attempt() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspacerepository repository
    JOIN core_workspace workspace ON workspace.id=repository.workspace_id
    JOIN core_repositorycommit commit ON commit.id=NEW.commit_id
    WHERE repository.id=NEW.repository_id AND repository.tenant_id=NEW.tenant_id
      AND workspace.id=NEW.workspace_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND commit.repository_id=repository.id AND commit.tenant_id=NEW.tenant_id
  ) THEN RAISE EXCEPTION 'content index attempt scope mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER core_contentnode_validate BEFORE INSERT OR UPDATE ON core_contentnode
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_node();
CREATE TRIGGER core_contentproperty_validate BEFORE INSERT OR UPDATE ON core_contentproperty
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_child();
CREATE TRIGGER core_contentlink_validate BEFORE INSERT OR UPDATE ON core_contentlink
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_child();
CREATE TRIGGER core_contentfinding_validate BEFORE INSERT OR UPDATE ON core_contentfinding
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_child();
CREATE TRIGGER core_contentindexattempt_validate BEFORE INSERT OR UPDATE ON core_contentindexattempt
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_attempt();

DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'core_contentnode', 'core_contentproperty', 'core_contentlink',
    'core_contentfinding', 'core_contentindexattempt'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY %I_runtime_scope ON %I '
      'USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id)) '
      'WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))',
      table_name, table_name
    );
  END LOOP;
END $$;
"""


REVERSE_SQL = r"""
DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'core_contentnode', 'core_contentproperty', 'core_contentlink',
    'core_contentfinding', 'core_contentindexattempt'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_runtime_scope ON %I', table_name, table_name);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;
DROP TRIGGER IF EXISTS core_contentindexattempt_validate ON core_contentindexattempt;
DROP TRIGGER IF EXISTS core_contentfinding_validate ON core_contentfinding;
DROP TRIGGER IF EXISTS core_contentlink_validate ON core_contentlink;
DROP TRIGGER IF EXISTS core_contentproperty_validate ON core_contentproperty;
DROP TRIGGER IF EXISTS core_contentnode_validate ON core_contentnode;
DROP FUNCTION IF EXISTS tekdocs_validate_content_attempt();
DROP FUNCTION IF EXISTS tekdocs_validate_content_child();
DROP FUNCTION IF EXISTS tekdocs_validate_content_node();
"""


class Migration(migrations.Migration):
    dependencies = [("core", "0164_repository_reconciliation_audit")]

    operations = [
        migrations.CreateModel(
            name="ContentNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content_id", models.UUIDField()),
                ("source_path", models.CharField(max_length=512)),
                ("kind", models.CharField(choices=[("document", "Document"), ("fragment", "Fragment")], max_length=16)),
                ("title", models.CharField(max_length=240)),
                ("markdown", models.TextField()),
                ("frontmatter", models.JSONField(default=dict)),
                ("taxonomy_keys", models.JSONField(default=dict)),
                ("topic_type", models.CharField(blank=True, max_length=32)),
                ("topic_schema_version", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("content_digest", models.CharField(max_length=64)),
                (
                    "indexed_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_nodes",
                        to="core.repositorycommit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_nodes",
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_nodes",
                        to="core.workspacerepository",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_nodes", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_nodes", to="core.workspace"
                    ),
                ),
            ],
            options={"ordering": ("source_path", "content_id")},
        ),
        migrations.CreateModel(
            name="ContentLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_content_id", models.UUIDField()),
                ("fragment", models.CharField(blank=True, max_length=120)),
                ("label", models.CharField(blank=True, max_length=240)),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_links",
                        to="core.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="core.contentnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlinks",
                        to="core.contentnode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_links", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_links", to="core.workspace"
                    ),
                ),
            ],
            options={"ordering": ("source_id", "ordinal", "id")},
        ),
        migrations.CreateModel(
            name="ContentFinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=80)),
                ("severity", models.CharField(max_length=16)),
                ("detail", models.JSONField(default=dict)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="core.contentnode"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_findings",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_findings", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_findings",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("node_id", "code", "id")},
        ),
        migrations.CreateModel(
            name="ContentProperty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=80)),
                ("value", models.JSONField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="properties", to="core.contentnode"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_properties",
                        to="core.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_properties", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_properties",
                        to="core.workspace",
                    ),
                ),
            ],
            options={"ordering": ("key", "id")},
        ),
        migrations.CreateModel(
            name="ContentIndexAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(choices=[("accepted", "Accepted"), ("rejected", "Rejected")], max_length=16),
                ),
                ("diagnostics", models.JSONField(default=list)),
                ("projection_digest", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_index_attempts",
                        to="core.repositorycommit",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_index_attempts",
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_index_attempts",
                        to="core.workspacerepository",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_index_attempts",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_index_attempts",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("repository", "commit"), name="content_index_attempt_unique"),
                    models.CheckConstraint(
                        condition=models.Q(status__in=["accepted", "rejected"]), name="content_index_status_valid"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentnode",
            index=models.Index(fields=["workspace", "kind", "source_path"], name="core_contentnode_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="contentnode",
            constraint=models.UniqueConstraint(
                fields=("repository", "content_id"), name="content_node_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentnode",
            constraint=models.UniqueConstraint(fields=("repository", "source_path"), name="content_node_path_unique"),
        ),
        migrations.AddConstraint(
            model_name="contentnode",
            constraint=models.CheckConstraint(
                condition=models.Q(kind__in=["document", "fragment"]), name="content_node_kind_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentnode",
            constraint=models.CheckConstraint(
                condition=models.Q(content_digest__regex=r"^[0-9a-f]{64}$"), name="content_node_digest_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="contentlink",
            index=models.Index(fields=["workspace", "target_content_id"], name="core_contentlink_target_idx"),
        ),
        migrations.AddConstraint(
            model_name="contentlink",
            constraint=models.UniqueConstraint(fields=("source", "ordinal"), name="content_link_ordinal_unique"),
        ),
        migrations.AddConstraint(
            model_name="contentproperty",
            constraint=models.UniqueConstraint(fields=("node", "key"), name="content_property_key_unique"),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
