# Generated by Django 5.2.17 on 2026-10-05 06:54

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE OR REPLACE FUNCTION tekdocs_validate_content_node() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspacerepository repository
    JOIN core_workspace workspace ON workspace.id=repository.workspace_id
    WHERE repository.id=NEW.repository_id AND repository.tenant_id=NEW.tenant_id
      AND workspace.id=NEW.workspace_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND NEW.indexed_commit_id=repository.accepted_commit_id
  ) THEN RAISE EXCEPTION 'content node scope mismatch' USING ERRCODE='23514'; END IF;
  IF (NEW.derived_from_content_id IS NULL) <> (NEW.derived_from_object_id = '') THEN
    RAISE EXCEPTION 'content provenance shape mismatch' USING ERRCODE='23514';
  END IF;
  IF NEW.derived_from_object_id <> '' AND NOT EXISTS (
    SELECT 1 FROM core_repositorycommit commit
    WHERE commit.repository_id=NEW.repository_id AND commit.tenant_id=NEW.tenant_id
      AND commit.object_id=NEW.derived_from_object_id
  ) THEN RAISE EXCEPTION 'content provenance commit mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_content_include() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE source_repository_id uuid;
DECLARE source_commit_id uuid;
BEGIN
  SELECT repository_id, indexed_commit_id INTO source_repository_id, source_commit_id
  FROM core_contentnode
  WHERE id=NEW.source_id AND tenant_id=NEW.tenant_id AND workspace_id=NEW.workspace_id
    AND organization_id IS NOT DISTINCT FROM NEW.organization_id;
  IF source_repository_id IS NULL THEN
    RAISE EXCEPTION 'content include scope mismatch' USING ERRCODE='23514';
  END IF;
  IF NEW.target_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contentnode target
    WHERE target.id=NEW.target_id AND target.repository_id=source_repository_id
      AND target.content_id=NEW.target_content_id
  ) THEN RAISE EXCEPTION 'content include target mismatch' USING ERRCODE='23514'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_repositorycommit commit
    WHERE commit.repository_id=source_repository_id AND commit.tenant_id=NEW.tenant_id
      AND commit.object_id=NEW.resolved_object_id
  ) THEN RAISE EXCEPTION 'content include commit mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.resolution_mode='live' AND NEW.resolved_object_id<>(
    SELECT object_id FROM core_repositorycommit WHERE id=source_commit_id
  ) THEN RAISE EXCEPTION 'live content include commit mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.resolution_mode='pinned' AND NEW.pinned_object_id<>NEW.resolved_object_id THEN
    RAISE EXCEPTION 'pinned content include commit mismatch' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_validate_content_template_source() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE source_repository_id uuid;
BEGIN
  SELECT repository_id INTO source_repository_id FROM core_contentnode
  WHERE id=NEW.template_id AND tenant_id=NEW.tenant_id AND workspace_id=NEW.workspace_id
    AND organization_id IS NOT DISTINCT FROM NEW.organization_id;
  IF source_repository_id IS NULL THEN
    RAISE EXCEPTION 'content template source scope mismatch' USING ERRCODE='23514';
  END IF;
  IF NEW.current_target_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM core_contentnode target
    WHERE target.id=NEW.current_target_id AND target.repository_id=source_repository_id
      AND target.content_id=NEW.source_content_id
  ) THEN RAISE EXCEPTION 'content template current target mismatch' USING ERRCODE='23514'; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM core_repositorycommit commit
    WHERE commit.repository_id=source_repository_id AND commit.tenant_id=NEW.tenant_id
      AND commit.object_id=NEW.pinned_object_id
  ) THEN RAISE EXCEPTION 'content template source commit mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER core_contentinclude_validate BEFORE INSERT OR UPDATE ON core_contentinclude
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_include();
CREATE TRIGGER core_contenttemplatesource_validate BEFORE INSERT OR UPDATE ON core_contenttemplatesource
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_template_source();

DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_contentinclude', 'core_contenttemplatesource'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'CREATE POLICY %I_runtime_scope ON %I '
      'USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id)) '
      'WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))',
      table_name, table_name
    );
  END LOOP;
END $$;

UPDATE core_workspacerepository SET indexed_commit_id=NULL WHERE indexed_commit_id IS NOT NULL;
"""


REVERSE_SQL = r"""
DO $$ DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['core_contentinclude', 'core_contenttemplatesource'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_runtime_scope ON %I', table_name, table_name);
    EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END $$;
DROP TRIGGER IF EXISTS core_contenttemplatesource_validate ON core_contenttemplatesource;
DROP TRIGGER IF EXISTS core_contentinclude_validate ON core_contentinclude;
DROP FUNCTION IF EXISTS tekdocs_validate_content_template_source();
DROP FUNCTION IF EXISTS tekdocs_validate_content_include();
CREATE OR REPLACE FUNCTION tekdocs_validate_content_node() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspacerepository repository
    JOIN core_workspace workspace ON workspace.id=repository.workspace_id
    WHERE repository.id=NEW.repository_id AND repository.tenant_id=NEW.tenant_id
      AND workspace.id=NEW.workspace_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND NEW.indexed_commit_id=repository.accepted_commit_id
  ) THEN RAISE EXCEPTION 'content node scope mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0165_content_graph_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentnode",
            name="composition_variants",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="derived_from_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentnode",
            name="derived_from_object_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="ContentInclude",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_content_id", models.UUIDField()),
                ("ordinal", models.PositiveIntegerField()),
                ("resolution_mode", models.CharField(choices=[("live", "Live"), ("pinned", "Pinned")], max_length=12)),
                (
                    "audience_profile",
                    models.CharField(
                        choices=[
                            ("shared", "Shared"),
                            ("msp_internal", "MSP internal"),
                            ("client_visible", "Client visible"),
                        ],
                        max_length=24,
                    ),
                ),
                ("pinned_object_id", models.CharField(blank=True, max_length=64)),
                ("resolved_object_id", models.CharField(max_length=64)),
                ("resolved_content_digest", models.CharField(max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_includes",
                        to="core.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="includes", to="core.contentnode"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_by",
                        to="core.contentnode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="content_includes", to="core.tenant"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_includes",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "ordinal", "id"),
                "indexes": [
                    models.Index(fields=["workspace", "target_content_id"], name="core_contentincl_target_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("source", "ordinal"), name="content_include_ordinal_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("resolution_mode__in", ["live", "pinned"])),
                        name="content_include_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("audience_profile__in", ["shared", "msp_internal", "client_visible"])),
                        name="content_include_audience_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("pinned_object_id", ""), ("resolution_mode", "live")),
                            models.Q(("resolution_mode", "pinned"), models.Q(("pinned_object_id", ""), _negated=True)),
                            _connector="OR",
                        ),
                        name="content_include_pin_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplateSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_content_id", models.UUIDField()),
                ("ordinal", models.PositiveIntegerField()),
                ("pinned_object_id", models.CharField(max_length=64)),
                ("pinned_content_digest", models.CharField(max_length=64)),
                ("pinned_title", models.CharField(max_length=240)),
                ("current_content_digest", models.CharField(blank=True, max_length=64)),
                ("change_preview", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("current", "Current"), ("changed", "Changed"), ("missing", "Missing")], max_length=16
                    ),
                ),
                (
                    "current_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_source_for",
                        to="core.contentnode",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_template_sources",
                        to="core.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_sources",
                        to="core.contentnode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_template_sources",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_template_sources",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("template_id", "ordinal", "id"),
                "indexes": [
                    models.Index(fields=["workspace", "source_content_id"], name="core_contenttplsrc_target_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "ordinal"), name="content_template_source_ordinal_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["current", "changed", "missing"])),
                        name="content_template_source_state_valid",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
