# Generated by Django 5.2.17 on 2026-10-06

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_content_entity_link() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_contentnode node
    WHERE node.id=NEW.source_id AND node.tenant_id=NEW.tenant_id
      AND node.workspace_id=NEW.workspace_id
      AND node.organization_id IS NOT DISTINCT FROM NEW.organization_id
  ) THEN RAISE EXCEPTION 'content entity link scope mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER core_contententitylink_validate BEFORE INSERT OR UPDATE ON core_contententitylink
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_content_entity_link();
ALTER TABLE core_contententitylink ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_contententitylink FORCE ROW LEVEL SECURITY;
CREATE POLICY core_contententitylink_runtime_scope ON core_contententitylink
USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))
WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id));
UPDATE core_workspacerepository SET indexed_commit_id=NULL WHERE indexed_commit_id IS NOT NULL;
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_contententitylink_runtime_scope ON core_contententitylink;
ALTER TABLE core_contententitylink NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_contententitylink DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_contententitylink_validate ON core_contententitylink;
DROP FUNCTION IF EXISTS tekdocs_validate_content_entity_link();
"""


class Migration(migrations.Migration):
    dependencies = [("core", "0166_file_backed_fragment_composition")]

    operations = [
        migrations.CreateModel(
            name="ContentEntityLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_entity_id", models.UUIDField()),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("enrollment", "Enrollment"),
                            ("maintenance", "Maintenance"),
                            ("troubleshooting", "Troubleshooting"),
                            ("repair_event", "Repair/event"),
                            ("mention", "Mention"),
                        ],
                        max_length=24,
                    ),
                ),
                ("origin", models.CharField(choices=[("typed", "Typed"), ("narrative", "Narrative")], max_length=12)),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_entity_links",
                        to="core.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="core.contentnode",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_entity_links",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_entity_links",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "ordinal", "id"),
                "indexes": [
                    models.Index(fields=["workspace", "target_entity_id"], name="core_contententity_target_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("source", "ordinal"), name="content_entity_link_ordinal_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            relationship__in=[
                                "setup",
                                "enrollment",
                                "maintenance",
                                "troubleshooting",
                                "repair_event",
                                "mention",
                            ]
                        ),
                        name="content_entity_link_relationship_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(origin__in=["typed", "narrative"]),
                        name="content_entity_link_origin_valid",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
