# Generated by Django 5.2.17 on 2026-10-07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_repository_publication_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_workspacerepository repository
    JOIN core_workspace workspace ON workspace.id=repository.workspace_id
    JOIN core_repositorycommit commit ON commit.id=NEW.source_commit_id
    WHERE repository.id=NEW.repository_id AND repository.tenant_id=NEW.tenant_id
      AND workspace.id=NEW.workspace_id
      AND workspace.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND commit.repository_id=repository.id AND commit.tenant_id=NEW.tenant_id
      AND repository.accepted_commit_id=commit.id
      AND repository.indexed_commit_id=commit.id
      AND NEW.manifest->>'source_commit'=commit.object_id
      AND NEW.manifest->'source'->>'accepted_commit'=commit.object_id
      AND NEW.manifest->'source'->>'object_format'=commit.object_format
  ) THEN RAISE EXCEPTION 'repository publication evidence source mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.content_digest !~ '^[0-9a-f]{64}$'
    OR NEW.key_fingerprint !~ '^[0-9a-f]{64}$'
    OR NEW.signature_algorithm IS DISTINCT FROM 'Ed25519'
    OR jsonb_typeof(NEW.manifest) IS DISTINCT FROM 'object'
    OR NEW.manifest->>'format' IS DISTINCT FROM 'tekdocs-repository-publication-evidence/v1'
    OR NEW.manifest->>'evidence_id' IS DISTINCT FROM NEW.id::text
    OR NEW.manifest->>'repository_id' IS DISTINCT FROM NEW.repository_id::text
    OR NEW.manifest->>'workspace_id' IS DISTINCT FROM NEW.workspace_id::text
    OR NEW.manifest->>'content_id' IS DISTINCT FROM NEW.content_id::text
    OR NEW.manifest->>'audience' IS DISTINCT FROM NEW.audience
    OR NEW.manifest->>'signed_by' IS DISTINCT FROM NEW.signed_by_id::text
    OR NEW.manifest->'source'->>'format' IS DISTINCT FROM 'tekdocs.git-dependencies/v1'
    OR NEW.manifest->'source'->>'repository_id' IS DISTINCT FROM NEW.repository_id::text
    OR NEW.manifest->'source'->>'workspace_id' IS DISTINCT FROM NEW.workspace_id::text
    OR NEW.manifest->'source'->>'content_id' IS DISTINCT FROM NEW.content_id::text
    OR NEW.manifest->'source'->>'audience' IS DISTINCT FROM NEW.audience
  THEN RAISE EXCEPTION 'repository publication evidence manifest mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_guard_repository_publication_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'repository publication evidence is append-only' USING ERRCODE='23514';
END $$;

CREATE TRIGGER core_repositorypublicationevidence_validate
BEFORE INSERT ON core_repositorypublicationevidence
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_repository_publication_evidence();
CREATE TRIGGER core_repositorypublicationevidence_immutable
BEFORE UPDATE OR DELETE ON core_repositorypublicationevidence
FOR EACH ROW EXECUTE FUNCTION tekdocs_guard_repository_publication_evidence();
ALTER TABLE core_repositorypublicationevidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_repositorypublicationevidence FORCE ROW LEVEL SECURITY;
CREATE POLICY core_repositorypublicationevidence_runtime_scope ON core_repositorypublicationevidence
USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))
WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id));
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_repositorypublicationevidence_runtime_scope ON core_repositorypublicationevidence;
ALTER TABLE core_repositorypublicationevidence NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_repositorypublicationevidence DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_repositorypublicationevidence_immutable ON core_repositorypublicationevidence;
DROP TRIGGER IF EXISTS core_repositorypublicationevidence_validate ON core_repositorypublicationevidence;
DROP FUNCTION IF EXISTS tekdocs_guard_repository_publication_evidence();
DROP FUNCTION IF EXISTS tekdocs_validate_repository_publication_evidence();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0167_contententitylink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryPublicationEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content_id", models.UUIDField()),
                (
                    "audience",
                    models.CharField(
                        choices=[("msp_internal", "MSP internal"), ("client_visible", "Client visible")], max_length=24
                    ),
                ),
                ("canonical_markdown", models.TextField()),
                ("manifest", models.JSONField()),
                ("content_digest", models.CharField(max_length=64)),
                ("signature", models.TextField()),
                ("signature_algorithm", models.CharField(default="Ed25519", max_length=20)),
                ("public_key", models.TextField()),
                ("key_fingerprint", models.CharField(max_length=64)),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repository_publication_evidence",
                        to="core.organization",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_evidence",
                        to="core.workspacerepository",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repository_publication_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_evidence",
                        to="core.repositorycommit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repository_publication_evidence",
                        to="core.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_evidence",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-signed_at", "id"),
                "indexes": [
                    models.Index(fields=["workspace", "content_id", "signed_at"], name="core_repubevid_source_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("audience__in", ["msp_internal", "client_visible"])),
                        name="repository_publication_evidence_audience_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("audience", "msp_internal"), ("organization__isnull", False), _connector="OR"
                        ),
                        name="repository_publication_evidence_client_scoped",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_digest__regex", "^[0-9a-f]{64}$")),
                        name="repository_publication_evidence_digest_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="repository_publication_evidence_key_valid",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
