# Generated by Django 5.2.17 on 2026-10-07 17:07

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models

FORWARD_SQL = r"""
CREATE FUNCTION tekdocs_validate_repository_evidence_attachment() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core_repositorypublicationevidence evidence
    JOIN core_documentattachment attachment ON attachment.id=NEW.source_attachment_id
    JOIN core_document document ON document.id=attachment.document_id
    JOIN core_entity entity ON entity.id=document.entity_id
    WHERE evidence.id=NEW.evidence_id
      AND evidence.tenant_id=NEW.tenant_id
      AND evidence.workspace_id=NEW.workspace_id
      AND evidence.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND attachment.tenant_id=NEW.tenant_id
      AND attachment.organization_id IS NOT DISTINCT FROM NEW.organization_id
      AND document.id=evidence.content_id
      AND entity.workspace_id=NEW.workspace_id
      AND attachment.purpose='attachment'
  ) THEN RAISE EXCEPTION 'repository evidence attachment scope mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.checksum !~ '^[0-9a-f]{64}$' OR NEW.size=0
    OR NEW.file IS DISTINCT FROM
      ('repository-evidence-attachments/' || NEW.tenant_id::text || '/' || NEW.evidence_id::text || '/' || NEW.id::text)
    OR NOT EXISTS (
      SELECT 1 FROM core_repositorypublicationevidence evidence,
        jsonb_array_elements(COALESCE(evidence.manifest->'attachments', '[]'::jsonb)) descriptor
      WHERE evidence.id=NEW.evidence_id
        AND descriptor->>'id'=NEW.id::text
        AND descriptor->>'source_id'=NEW.source_attachment_id::text
        AND descriptor->>'checksum'=NEW.checksum
        AND descriptor->>'size'=NEW.size::text
        AND descriptor->>'media_type'=NEW.media_type
    )
  THEN RAISE EXCEPTION 'repository evidence attachment manifest mismatch' USING ERRCODE='23514'; END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION tekdocs_guard_repository_evidence_attachment() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'repository evidence attachment is append-only' USING ERRCODE='23514';
END $$;

CREATE TRIGGER core_repositoryevidenceattachment_validate
BEFORE INSERT ON core_repositoryevidenceattachment
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_repository_evidence_attachment();
CREATE TRIGGER core_repositoryevidenceattachment_immutable
BEFORE UPDATE OR DELETE ON core_repositoryevidenceattachment
FOR EACH ROW EXECUTE FUNCTION tekdocs_guard_repository_evidence_attachment();
ALTER TABLE core_repositoryevidenceattachment ENABLE ROW LEVEL SECURITY;
ALTER TABLE core_repositoryevidenceattachment FORCE ROW LEVEL SECURITY;
CREATE POLICY core_repositoryevidenceattachment_runtime_scope ON core_repositoryevidenceattachment
USING (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id))
WITH CHECK (workspace_id=tekdocs_current_workspace_id() AND tekdocs_scope_matches(tenant_id, organization_id));
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS core_repositoryevidenceattachment_runtime_scope ON core_repositoryevidenceattachment;
ALTER TABLE core_repositoryevidenceattachment NO FORCE ROW LEVEL SECURITY;
ALTER TABLE core_repositoryevidenceattachment DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS core_repositoryevidenceattachment_immutable ON core_repositoryevidenceattachment;
DROP TRIGGER IF EXISTS core_repositoryevidenceattachment_validate ON core_repositoryevidenceattachment;
DROP FUNCTION IF EXISTS tekdocs_guard_repository_evidence_attachment();
DROP FUNCTION IF EXISTS tekdocs_validate_repository_evidence_attachment();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0168_repositorypublicationevidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryEvidenceAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=apps.core.models.repository_evidence_attachment_upload_to
                    ),
                ),
                ("media_type", models.CharField(max_length=120)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="core.repositorypublicationevidence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.organization"
                    ),
                ),
                (
                    "source_attachment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.documentattachment"),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.tenant")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.workspace")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evidence", "source_attachment"), name="one_repo_evidence_attachment"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("checksum__regex", "^[0-9a-f]{64}$")),
                        name="repo_evidence_attachment_checksum_valid",
                    ),
                ],
            },
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
