from dataclasses import dataclass

from apps.accounts.policy import PermissionKey


@dataclass(frozen=True, slots=True)
class RoutePermissionContract:
    route_name: str
    methods: tuple[str, ...]
    read_permission: PermissionKey | None = None
    mutation_permissions: tuple[PermissionKey, ...] = ()
    organization_scoped: bool = False


def route(
    route_name: str,
    methods: tuple[str, ...],
    read: PermissionKey | None = None,
    mutations: tuple[PermissionKey, ...] = (),
    *,
    organization_scoped: bool = False,
) -> RoutePermissionContract:
    return RoutePermissionContract(route_name, methods, read, mutations, organization_scoped)


AUTHENTICATED_ROUTE_PERMISSIONS = (
    route("auth-context", ("GET",)),
    route("auth-profile", ("PATCH",)),
    route("api-token-list-create", ("GET", "POST")),
    route("api-token-rotate", ("POST",)),
    route("api-token-revoke", ("DELETE",)),
    route("markdown-render", ("POST",), PermissionKey.DOCUMENTS_VIEW),
    route("document-topic-schemas", ("GET",)),
    route(
        "msp-taxonomy-list-create",
        ("GET", "POST"),
        PermissionKey.CUSTOM_FIELDS_VIEW,
        (PermissionKey.CUSTOM_FIELDS_MANAGE,),
    ),
    route("msp-taxonomy-migration", ("POST",), mutations=(PermissionKey.CUSTOM_FIELDS_MANAGE,)),
    route(
        "msp-taxonomy-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CUSTOM_FIELDS_MANAGE, PermissionKey.CUSTOM_FIELDS_MANAGE),
    ),
    route(
        "msp-credential-reference-list-create",
        ("GET", "POST"),
        PermissionKey.CREDENTIAL_REFERENCES_VIEW,
        (PermissionKey.CREDENTIAL_REFERENCES_MANAGE,),
    ),
    route(
        "msp-credential-reference-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CREDENTIAL_REFERENCES_MANAGE, PermissionKey.CREDENTIAL_REFERENCES_MANAGE),
    ),
    route("msp-credential-reference-open", ("GET",), PermissionKey.CREDENTIAL_REFERENCES_OPEN),
    route(
        "msp-document-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-document-search", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-preflight", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-topic-conversion", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-operations-choices", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-operations", ("PUT",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-review-request", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-review-decision", ("POST",), mutations=(PermissionKey.DOCUMENTS_APPROVE,)),
    route("msp-document-file-backed-create", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route(
        "msp-document-detail",
        ("GET", "PUT", "DELETE"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route(
        "msp-document-restructure",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_EDIT,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-document-revision-list", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-revision-detail", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route(
        "msp-document-placement-list-create",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
    ),
    route(
        "msp-document-placement-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
    ),
    route(
        "msp-document-placement-reuse", ("GET", "PUT"), PermissionKey.DOCUMENTS_VIEW, (PermissionKey.DOCUMENTS_EDIT,)
    ),
    route("msp-document-placement-detach", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-mention-search", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-block-library", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route(
        "msp-documentation-map-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-documentation-map-choices", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route(
        "msp-documentation-map-detail",
        ("GET", "PUT", "DELETE"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-documentation-map-review", ("POST",), mutations=(PermissionKey.DOCUMENTS_APPROVE,)),
    route("msp-documentation-map-preview", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-documentation-map-baselines", ("POST",), mutations=(PermissionKey.DOCUMENTS_PUBLISH,)),
    route("msp-documentation-map-baseline-download", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-template-instantiate", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-import", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-export", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-remote-source", ("GET", "PUT"), PermissionKey.DOCUMENTS_VIEW, (PermissionKey.DOCUMENTS_EDIT,)),
    route(
        "msp-document-key-binding-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-document-key-binding-detail", ("DELETE",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-keys", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-key-bindings", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route(
        "msp-document-remote-observations",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("msp-document-remote-observation-apply", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-attachment-list-create", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-primary-file", ("POST",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-attachment-detail", ("DELETE",), mutations=(PermissionKey.DOCUMENTS_EDIT,)),
    route("msp-document-attachment-download", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route(
        "msp-document-publication-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_PUBLISH,),
    ),
    route("msp-document-publication-detail", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-publication-approve", ("POST",), mutations=(PermissionKey.DOCUMENTS_APPROVE,)),
    route("msp-document-publication-withdraw", ("POST",), mutations=(PermissionKey.DOCUMENTS_WITHDRAW,)),
    route("msp-document-publication-markdown", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-publication-export", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-publication-manifest", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-document-publication-artifact-download", ("GET",), PermissionKey.DOCUMENTS_VIEW),
    route("msp-integration-provider-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-halopsa-ticket-summary-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route(
        "msp-integration-connection-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
    ),
    route("msp-integration-connection-detail", ("PATCH",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route("msp-integration-connection-rotate", ("POST",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route(
        "msp-integration-job-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
    ),
    route("msp-integration-job-cancel", ("POST",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route("msp-integration-log-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-integration-observation-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-integration-conflict-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-integration-conflict-resolve", ("POST",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route(
        "msp-git-export-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
    ),
    route("msp-git-export-download", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route(
        "msp-import-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
    ),
    route("msp-import-template", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-import-detail", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-import-row-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route("msp-import-apply", ("POST",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route("msp-import-cancel", ("POST",), mutations=(PermissionKey.INTEGRATIONS_MANAGE,)),
    route("msp-import-report", ("GET",), PermissionKey.INTEGRATIONS_VIEW),
    route(
        "msp-compliance-framework-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
    ),
    route("msp-compliance-framework-detail", ("GET",), PermissionKey.COMPLIANCE_VIEW),
    route(
        "msp-compliance-catalog-revision-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
    ),
    route("msp-compliance-catalog-revision-detail", ("GET",), PermissionKey.COMPLIANCE_VIEW),
    route("msp-compliance-assignment-list", ("GET",), PermissionKey.COMPLIANCE_VIEW),
    route("msp-compliance-assignment-review", ("POST",), mutations=(PermissionKey.COMPLIANCE_EDIT,)),
    route(
        "msp-compliance-evidence-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
    ),
    route("msp-compliance-evidence-review", ("POST",), mutations=(PermissionKey.COMPLIANCE_EDIT,)),
    route(
        "msp-data-flows",
        ("GET", "POST"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT,),
    ),
    route("msp-data-flow-choices", ("GET",), PermissionKey.DATA_FLOWS_VIEW),
    route(
        "msp-data-flow-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT, PermissionKey.DATA_FLOWS_EDIT),
    ),
    route("msp-data-flow-revisions", ("GET",), PermissionKey.DATA_FLOWS_VIEW),
    route(
        "msp-data-flow-snapshots",
        ("GET", "POST"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT,),
    ),
    route("msp-data-flow-snapshot-export", ("GET",), PermissionKey.DATA_FLOWS_VIEW),
    route(
        "msp-compliance-risk-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
    ),
    route("msp-compliance-risk-review", ("POST",), mutations=(PermissionKey.COMPLIANCE_EDIT,)),
    route(
        "msp-compliance-bundle-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
    ),
    route(
        "msp-reminder-list-create",
        ("GET", "POST"),
        PermissionKey.DEADLINES_VIEW,
        (PermissionKey.DEADLINES_EDIT,),
    ),
    route("msp-reminder-calendar", ("GET",), PermissionKey.DEADLINES_VIEW),
    route(
        "msp-domain-list-create",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
    ),
    route("msp-domain-review", ("POST",), mutations=(PermissionKey.DOMAINS_EDIT,)),
    route("msp-domain-monitoring", ("GET", "POST"), PermissionKey.DOMAINS_VIEW, (PermissionKey.DOMAINS_EDIT,)),
    route(
        "msp-certificate-endpoint-list-create",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
    ),
    route(
        "msp-certificate-monitoring",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
    ),
    route("msp-hostname-list-create", ("GET", "POST"), PermissionKey.DOMAINS_VIEW, (PermissionKey.DOMAINS_EDIT,)),
    route("msp-domain-observation-create", ("POST",), mutations=(PermissionKey.DOMAINS_EDIT,)),
    route("msp-compliance-assignment-evidence-link", ("POST",), mutations=(PermissionKey.COMPLIANCE_EDIT,)),
    route(
        "msp-document-reference-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
    ),
    route(
        "msp-document-reference-detail",
        ("DELETE",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
    ),
    route("access-control-catalog", ("GET",), PermissionKey.MEMBERSHIPS_VIEW),
    route(
        "access-collection-list-create",
        ("GET", "POST"),
        PermissionKey.ACCESS_COLLECTIONS_VIEW,
        (PermissionKey.ACCESS_COLLECTIONS_MANAGE,),
    ),
    route(
        "access-collection-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.ACCESS_COLLECTIONS_MANAGE,),
    ),
    route(
        "custom-role-list-create",
        ("GET", "POST"),
        PermissionKey.CUSTOM_ROLES_VIEW,
        (PermissionKey.CUSTOM_ROLES_MANAGE,),
    ),
    route("custom-role-detail", ("PATCH", "DELETE"), mutations=(PermissionKey.CUSTOM_ROLES_MANAGE,)),
    route(
        "scoped-role-assignment-list-create",
        ("GET", "POST"),
        PermissionKey.CUSTOM_ROLES_VIEW,
        (PermissionKey.CUSTOM_ROLES_ASSIGN,),
    ),
    route(
        "scoped-role-assignment-detail",
        ("DELETE",),
        mutations=(PermissionKey.CUSTOM_ROLES_ASSIGN,),
    ),
    route("access-control-members", ("GET",), PermissionKey.MEMBERSHIPS_VIEW),
    route(
        "access-control-member-role",
        ("PATCH",),
        mutations=(PermissionKey.MEMBERSHIPS_ASSIGN_ROLE,),
    ),
    route(
        "access-control-organizations",
        ("GET",),
        PermissionKey.ORGANIZATIONS_MANAGE_ACCESS,
    ),
    route(
        "access-control-organization-detail",
        ("PATCH",),
        mutations=(PermissionKey.ORGANIZATIONS_MANAGE_ACCESS,),
        organization_scoped=True,
    ),
    route(
        "access-control-organization-staff",
        ("POST",),
        None,
        (PermissionKey.ORGANIZATIONS_ASSIGN_STAFF,),
        organization_scoped=True,
    ),
    route(
        "access-control-organization-staff-detail",
        ("DELETE",),
        mutations=(PermissionKey.ORGANIZATIONS_ASSIGN_STAFF,),
        organization_scoped=True,
    ),
    route(
        "invitation-list-create",
        ("GET", "POST"),
        PermissionKey.INVITATIONS_VIEW,
        (PermissionKey.INVITATIONS_CREATE,),
    ),
    route("invitation-revoke", ("POST",), mutations=(PermissionKey.INVITATIONS_REVOKE,)),
    route("invitation-resend", ("POST",), mutations=(PermissionKey.INVITATIONS_RESEND,)),
    route(
        "client-invitation-list-create",
        ("GET", "POST"),
        PermissionKey.INVITATIONS_VIEW,
        (PermissionKey.INVITATIONS_CREATE,),
        organization_scoped=True,
    ),
    route("client-portal-context", ("GET",)),
    route("client-portal-notification-list", ("GET",)),
    route("client-portal-notification-read", ("PATCH",)),
    route("client-portal-notification-preferences", ("GET", "PATCH")),
    route("client-portal-document-list", ("GET",)),
    route("client-portal-document-detail", ("GET",)),
    route("client-portal-document-artifact-download", ("GET",)),
    route("client-portal-documentation-map-list", ("GET",)),
    route("client-portal-documentation-map-download", ("GET",)),
    route("client-portal-invoice-list", ("GET",)),
    route("client-portal-invoice-detail", ("GET",)),
    route("client-portal-invoice-pdf", ("GET",)),
    route("client-portal-invoice-csv", ("GET",)),
    route("notification-list", ("GET",)),
    route("notification-read", ("PATCH",)),
    route("notification-preferences", ("GET", "PATCH")),
    route("notification-delivery-list", ("GET",), PermissionKey.NOTIFICATIONS_MANAGE),
    route("notification-delivery-retry", ("POST",), mutations=(PermissionKey.NOTIFICATIONS_MANAGE,)),
    route(
        "organization-list-create",
        ("GET", "POST"),
        PermissionKey.ORGANIZATIONS_VIEW,
        (PermissionKey.ORGANIZATIONS_CREATE,),
    ),
    route(
        "organization-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.ORGANIZATIONS_VIEW,
        (PermissionKey.ORGANIZATIONS_EDIT, PermissionKey.ORGANIZATIONS_ARCHIVE),
    ),
    route("entity-link-type-catalog", ("GET",), PermissionKey.RELATIONSHIPS_VIEW),
    route("msp-entity-search", ("GET",), PermissionKey.RELATIONSHIPS_VIEW),
    route("msp-workspace-search", ("GET",)),
    route("msp-activity-list", ("GET",), PermissionKey.ACTIVITY_VIEW),
    route(
        "msp-entity-relationship-list-create",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
    ),
    route(
        "msp-entity-relationship-detail",
        ("DELETE",),
        mutations=(PermissionKey.RELATIONSHIPS_ARCHIVE,),
    ),
    route("msp-relationship-graph", ("GET",), PermissionKey.RELATIONSHIPS_VIEW),
    route(
        "msp-relationship-graph-views",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
    ),
    route(
        "msp-relationship-graph-view-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.RELATIONSHIPS_CREATE, PermissionKey.RELATIONSHIPS_ARCHIVE),
    ),
    route(
        "msp-relationship-graph-snapshots",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
    ),
    route(
        "msp-relationship-graph-snapshot-export",
        ("GET",),
        PermissionKey.RELATIONSHIPS_VIEW,
    ),
    route(
        "msp-people-list-create",
        ("GET", "POST"),
        PermissionKey.PEOPLE_VIEW,
        (PermissionKey.PEOPLE_CREATE,),
    ),
    route(
        "msp-person-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.PEOPLE_VIEW,
        (PermissionKey.PEOPLE_EDIT, PermissionKey.PEOPLE_ARCHIVE),
    ),
    route(
        "msp-site-list-create",
        ("GET", "POST"),
        PermissionKey.SITES_VIEW,
        (PermissionKey.SITES_CREATE,),
    ),
    route(
        "msp-site-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.SITES_VIEW,
        (PermissionKey.SITES_EDIT, PermissionKey.SITES_ARCHIVE),
    ),
    route("msp-location-list-create", ("POST",), mutations=(PermissionKey.SITES_CREATE,)),
    route(
        "msp-location-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.SITES_EDIT, PermissionKey.SITES_ARCHIVE),
    ),
    route(
        "msp-custom-field-definition-list-create",
        ("GET", "POST"),
        PermissionKey.CUSTOM_FIELDS_VIEW,
        (PermissionKey.CUSTOM_FIELDS_MANAGE,),
    ),
    route(
        "msp-custom-field-definition-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CUSTOM_FIELDS_MANAGE,),
    ),
    route("msp-entity-custom-field-list", ("GET",), PermissionKey.CUSTOM_FIELDS_VIEW),
    route(
        "msp-entity-custom-field-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CUSTOM_FIELDS_EDIT_VALUES,),
    ),
    route("msp-recycle-bin", ("GET",), PermissionKey.RECYCLE_BIN_VIEW),
    route("msp-recycle-bin-restore", ("POST",), mutations=(PermissionKey.RECYCLE_BIN_RESTORE,)),
    route("workspace-msp", ("GET",), PermissionKey.WORKSPACES_VIEW),
    route("workspace-organization-search", ("GET",), PermissionKey.ORGANIZATIONS_VIEW),
    route("workspace-organization", ("GET",), PermissionKey.WORKSPACES_VIEW, organization_scoped=True),
    route(
        "organization-catalog-product-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-product-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-publication-choices",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-catalog-product-document-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-product-document-detail",
        ("DELETE",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-model-list-create",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-model-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-specification-definition-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-catalog-specification-definition-version-create",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-list-create",
        ("GET", "POST"),
        PermissionKey.INVOICES_VIEW,
        (PermissionKey.INVOICES_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-origin-choices",
        ("GET",),
        PermissionKey.INVOICES_EDIT,
        organization_scoped=True,
    ),
    route(
        "msp-invoice-settings",
        ("GET", "PUT"),
        PermissionKey.INVOICES_ISSUE,
        (PermissionKey.INVOICES_ISSUE,),
    ),
    route(
        "organization-invoice-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.INVOICES_VIEW,
        (PermissionKey.INVOICES_EDIT, PermissionKey.INVOICES_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-line-list-create",
        ("POST",),
        mutations=(PermissionKey.INVOICES_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-issue",
        ("POST",),
        mutations=(PermissionKey.INVOICES_ISSUE,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-pdf",
        ("GET",),
        PermissionKey.INVOICES_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-invoice-csv",
        ("GET",),
        PermissionKey.INVOICES_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-invoice-accounting-export",
        ("GET",),
        PermissionKey.INVOICES_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-invoice-event-create",
        ("POST",),
        mutations=(PermissionKey.INVOICES_ISSUE,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-deliver",
        ("POST",),
        mutations=(PermissionKey.INVOICES_ISSUE,),
        organization_scoped=True,
    ),
    route(
        "organization-invoice-line-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.INVOICES_EDIT, PermissionKey.INVOICES_EDIT),
        organization_scoped=True,
    ),
    route(
        "msp-service-rate-list-create",
        ("GET", "POST"),
        PermissionKey.INVOICES_VIEW,
        (PermissionKey.INVOICES_EDIT,),
    ),
    route(
        "msp-service-rate-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.INVOICES_EDIT, PermissionKey.INVOICES_EDIT),
    ),
    route("msp-asset-list-create", ("GET", "POST"), PermissionKey.ASSETS_VIEW, (PermissionKey.ASSETS_EDIT,)),
    route("msp-asset-bulk", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-asset-csv-template", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-asset-csv-export", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-asset-csv-preview", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-asset-csv-apply", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-asset-model-choices", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-asset-detail", ("GET",), PermissionKey.ASSETS_VIEW),
    route(
        "msp-asset-mac-addresses",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
    ),
    route("msp-asset-mac-address-detail", ("PATCH",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-networks", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-detail", ("PATCH",), mutations=(PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-choices", ("GET",), PermissionKey.NETWORKS_VIEW),
    route("msp-network-search", ("GET",), PermissionKey.NETWORKS_VIEW),
    route("msp-network-export", ("GET",), PermissionKey.NETWORKS_VIEW),
    route(
        "msp-netbox-reference-list-create",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
    ),
    route("msp-netbox-reference-detail", ("DELETE",), mutations=(PermissionKey.NETWORKS_EDIT,)),
    route("msp-netbox-reference-choices", ("GET",), PermissionKey.NETWORKS_VIEW),
    route("msp-netbox-reconcile-preview", ("POST",), PermissionKey.NETWORKS_VIEW),
    route("msp-network-racks", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-rack-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-devices", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route(
        "msp-network-device-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
    ),
    route("msp-network-vrfs", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-vrf-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-vlans", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-vlan-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-subnets", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-subnet-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-interfaces", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route(
        "msp-network-interface-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)
    ),
    route("msp-network-ip-addresses", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route(
        "msp-network-ip-address-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)
    ),
    route("msp-network-mac-addresses", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route(
        "msp-network-mac-address-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)
    ),
    route("msp-network-wireless", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-wireless-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-dns-zones", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-dns-zone-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-dns-records", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route(
        "msp-network-dns-record-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)
    ),
    route("msp-network-circuits", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-circuit-choices", ("GET",), PermissionKey.NETWORKS_VIEW),
    route("msp-network-circuit-detail", ("GET", "PATCH"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-circuit-handoffs", ("GET", "POST"), PermissionKey.NETWORKS_VIEW, (PermissionKey.NETWORKS_EDIT,)),
    route("msp-network-circuit-handoff-detail", ("PATCH",), mutations=(PermissionKey.NETWORKS_EDIT,)),
    route("msp-hardware-detail", ("GET", "PATCH"), PermissionKey.ASSETS_VIEW, (PermissionKey.ASSETS_EDIT,)),
    route("msp-hardware-assignment-choices", ("GET",), PermissionKey.ASSETS_VIEW),
    route(
        "msp-hardware-assignment",
        ("POST", "DELETE"),
        mutations=(PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
    ),
    route("msp-hardware-disposal", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-hardware-lifecycle", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-software-detail", ("PATCH",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-software-license-list-create", ("GET", "POST"), PermissionKey.ASSETS_VIEW, (PermissionKey.ASSETS_EDIT,)),
    route("msp-software-license-choices", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-software-license-detail", ("GET", "PATCH"), PermissionKey.ASSETS_VIEW, (PermissionKey.ASSETS_EDIT,)),
    route("msp-software-license-installation", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-software-license-seat", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route("msp-software-license-seat-detail", ("DELETE",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route(
        "msp-commercial-contract-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
    ),
    route("msp-commercial-contract-provider-choices", ("GET",), PermissionKey.ASSETS_VIEW),
    route(
        "msp-commercial-contract-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
    ),
    route("msp-commercial-contract-cost-list-create", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,)),
    route(
        "msp-commercial-contract-cost-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
    ),
    route("msp-asset-document-detail", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-asset-document-artifact-download", ("GET",), PermissionKey.ASSETS_VIEW),
    route("msp-vendor-list", ("GET",), PermissionKey.ASSETS_VIEW),
    route(
        "organization-client-asset-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-client-asset-bulk",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route("organization-asset-csv-template", ("GET",), PermissionKey.ASSETS_VIEW, organization_scoped=True),
    route("organization-asset-csv-export", ("GET",), PermissionKey.ASSETS_VIEW, organization_scoped=True),
    route(
        "organization-asset-csv-preview", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,), organization_scoped=True
    ),
    route("organization-asset-csv-apply", ("POST",), mutations=(PermissionKey.ASSETS_EDIT,), organization_scoped=True),
    route(
        "organization-client-asset-model-choices",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-client-asset-detail",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-asset-mac-addresses",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-asset-mac-address-detail",
        ("PATCH",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-client-hardware-detail",
        ("GET", "PATCH"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-client-hardware-assignment-choices",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-client-hardware-assignment",
        ("POST", "DELETE"),
        mutations=(PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-client-hardware-disposal",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-client-hardware-lifecycle",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-client-software-detail",
        ("PATCH",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-software-license-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-software-license-choices",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-software-license-detail",
        ("GET", "PATCH"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-software-license-installation",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-software-license-seat",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-software-license-seat-detail",
        ("DELETE",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-commercial-contract-list-create",
        ("GET", "POST"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-commercial-contract-provider-choices",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-commercial-contract-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.ASSETS_VIEW,
        (PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-commercial-contract-cost-list-create",
        ("POST",),
        mutations=(PermissionKey.ASSETS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-commercial-contract-cost-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.ASSETS_EDIT, PermissionKey.ASSETS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-client-asset-document-detail",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-client-asset-document-artifact-download",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-client-vendor-list",
        ("GET",),
        PermissionKey.ASSETS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-credential-reference-list-create",
        ("GET", "POST"),
        PermissionKey.CREDENTIAL_REFERENCES_VIEW,
        (PermissionKey.CREDENTIAL_REFERENCES_MANAGE,),
        organization_scoped=True,
    ),
    route("organization-network-choices", ("GET",), PermissionKey.NETWORKS_VIEW, organization_scoped=True),
    route(
        "organization-networks",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-detail",
        ("PATCH",),
        mutations=(PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route("organization-network-search", ("GET",), PermissionKey.NETWORKS_VIEW, organization_scoped=True),
    route("organization-network-export", ("GET",), PermissionKey.NETWORKS_VIEW, organization_scoped=True),
    route(
        "organization-netbox-reference-list-create",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-netbox-reference-detail",
        ("DELETE",),
        mutations=(PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-netbox-reference-choices",
        ("GET",),
        PermissionKey.NETWORKS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-netbox-reconcile-preview",
        ("POST",),
        PermissionKey.NETWORKS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-network-racks",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-rack-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-devices",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-device-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-vrfs",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-vrf-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-vlans",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-vlan-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-subnets",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-subnet-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-interfaces",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-interface-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-ip-addresses",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-ip-address-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-mac-addresses",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-mac-address-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-wireless",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-wireless-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-dns-zones",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-dns-zone-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-dns-records",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-dns-record-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-circuits",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-circuit-choices",
        ("GET",),
        PermissionKey.NETWORKS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-network-circuit-detail",
        ("GET", "PATCH"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-circuit-handoffs",
        ("GET", "POST"),
        PermissionKey.NETWORKS_VIEW,
        (PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-network-circuit-handoff-detail",
        ("PATCH",),
        mutations=(PermissionKey.NETWORKS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-credential-reference-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CREDENTIAL_REFERENCES_MANAGE, PermissionKey.CREDENTIAL_REFERENCES_MANAGE),
        organization_scoped=True,
    ),
    route(
        "organization-credential-reference-open",
        ("GET",),
        PermissionKey.CREDENTIAL_REFERENCES_OPEN,
        organization_scoped=True,
    ),
    route(
        "organization-people-list-create",
        ("GET", "POST"),
        PermissionKey.PEOPLE_VIEW,
        (PermissionKey.PEOPLE_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-document-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-taxonomy-list",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-taxonomy-local-term-create",
        ("POST",),
        mutations=(PermissionKey.CUSTOM_FIELDS_MANAGE,),
        organization_scoped=True,
    ),
    route("organization-document-search", ("GET",), PermissionKey.DOCUMENTS_VIEW, organization_scoped=True),
    route(
        "organization-document-operations-choices",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-operations",
        ("PUT",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-review-request",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-review-decision",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_APPROVE,),
        organization_scoped=True,
    ),
    route(
        "organization-document-file-backed-create",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-template-instantiate",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-template-library",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-template-rollout-preview",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-template-rollout-apply",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-import",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-export",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-remote-source",
        ("GET", "PUT"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-key-binding-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-key-binding-detail",
        ("DELETE",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-keys",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-key-bindings",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-remote-observations",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-remote-observation-apply",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-attachment-list-create",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-primary-file",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-attachment-detail",
        ("DELETE",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-attachment-download",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_PUBLISH,),
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-detail",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-approve",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_APPROVE,),
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-withdraw",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_WITHDRAW,),
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-markdown",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-export",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-manifest",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-publication-artifact-download",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-detail",
        ("GET", "PUT", "DELETE"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route("organization-document-preflight", ("GET",), PermissionKey.DOCUMENTS_VIEW, organization_scoped=True),
    route(
        "organization-document-topic-conversion",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-restructure",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_EDIT,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-revision-list",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-revision-detail",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-placement-list-create",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-placement-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-placement-reuse",
        ("GET", "PUT"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-placement-detach",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-document-mention-search",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-document-block-library",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-person-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.PEOPLE_VIEW,
        (PermissionKey.PEOPLE_EDIT, PermissionKey.PEOPLE_ARCHIVE),
        organization_scoped=True,
    ),
    route(
        "organization-site-list-create",
        ("GET", "POST"),
        PermissionKey.SITES_VIEW,
        (PermissionKey.SITES_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-site-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.SITES_VIEW,
        (PermissionKey.SITES_EDIT, PermissionKey.SITES_ARCHIVE),
        organization_scoped=True,
    ),
    route(
        "organization-location-list-create",
        ("POST",),
        mutations=(PermissionKey.SITES_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-location-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.SITES_EDIT, PermissionKey.SITES_ARCHIVE),
        organization_scoped=True,
    ),
    route(
        "organization-custom-field-definition-list-create",
        ("GET", "POST"),
        PermissionKey.CUSTOM_FIELDS_VIEW,
        (PermissionKey.CUSTOM_FIELDS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-custom-field-definition-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CUSTOM_FIELDS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-entity-custom-field-list",
        ("GET",),
        PermissionKey.CUSTOM_FIELDS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-entity-custom-field-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.CUSTOM_FIELDS_EDIT_VALUES,),
        organization_scoped=True,
    ),
    route(
        "organization-entity-search",
        ("GET",),
        PermissionKey.RELATIONSHIPS_VIEW,
        organization_scoped=True,
    ),
    route("organization-workspace-search", ("GET",), organization_scoped=True),
    route(
        "organization-entity-relationship-list-create",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-entity-relationship-detail",
        ("DELETE",),
        mutations=(PermissionKey.RELATIONSHIPS_ARCHIVE,),
        organization_scoped=True,
    ),
    route(
        "organization-relationship-graph",
        ("GET",),
        PermissionKey.RELATIONSHIPS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-relationship-graph-views",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-relationship-graph-view-detail",
        ("PATCH", "DELETE"),
        mutations=(PermissionKey.RELATIONSHIPS_CREATE, PermissionKey.RELATIONSHIPS_ARCHIVE),
        organization_scoped=True,
    ),
    route(
        "organization-relationship-graph-snapshots",
        ("GET", "POST"),
        PermissionKey.RELATIONSHIPS_VIEW,
        (PermissionKey.RELATIONSHIPS_CREATE,),
        organization_scoped=True,
    ),
    route(
        "organization-relationship-graph-snapshot-export",
        ("GET",),
        PermissionKey.RELATIONSHIPS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-recycle-bin",
        ("GET",),
        PermissionKey.RECYCLE_BIN_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-recycle-bin-restore",
        ("POST",),
        mutations=(PermissionKey.RECYCLE_BIN_RESTORE,),
        organization_scoped=True,
    ),
    route(
        "organization-webhook-endpoint-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-webhook-endpoint-detail",
        ("PATCH",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-webhook-endpoint-rotate",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-webhook-delivery-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-webhook-delivery-retry",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-provider-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-halopsa-ticket-summary-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-integration-connection-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-connection-detail",
        ("PATCH",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-connection-rotate",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-job-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-job-cancel",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-integration-log-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-integration-observation-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-integration-conflict-list",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-integration-conflict-resolve",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-git-export-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-git-export-download",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-import-list-create",
        ("GET", "POST"),
        PermissionKey.INTEGRATIONS_VIEW,
        (PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-import-template",
        ("GET",),
        PermissionKey.INTEGRATIONS_VIEW,
        organization_scoped=True,
    ),
    route("organization-import-detail", ("GET",), PermissionKey.INTEGRATIONS_VIEW, organization_scoped=True),
    route("organization-import-row-list", ("GET",), PermissionKey.INTEGRATIONS_VIEW, organization_scoped=True),
    route(
        "organization-import-apply",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route(
        "organization-import-cancel",
        ("POST",),
        mutations=(PermissionKey.INTEGRATIONS_MANAGE,),
        organization_scoped=True,
    ),
    route("organization-import-report", ("GET",), PermissionKey.INTEGRATIONS_VIEW, organization_scoped=True),
    route(
        "organization-documentation-map-list-create",
        ("GET", "POST"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-choices",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-detail",
        ("GET", "PUT", "DELETE"),
        PermissionKey.DOCUMENTS_VIEW,
        (PermissionKey.DOCUMENTS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-review",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_APPROVE,),
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-preview",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-baselines",
        ("POST",),
        mutations=(PermissionKey.DOCUMENTS_PUBLISH,),
        organization_scoped=True,
    ),
    route(
        "organization-documentation-map-baseline-download",
        ("GET",),
        PermissionKey.DOCUMENTS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-compliance-framework-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-framework-detail",
        ("GET",),
        PermissionKey.COMPLIANCE_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-compliance-catalog-revision-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-catalog-revision-detail",
        ("GET",),
        PermissionKey.COMPLIANCE_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-compliance-assignment-list",
        ("GET",),
        PermissionKey.COMPLIANCE_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-compliance-assignment-review",
        ("POST",),
        mutations=(PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-evidence-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-data-flows",
        ("GET", "POST"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-data-flow-choices",
        ("GET",),
        PermissionKey.DATA_FLOWS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-data-flow-detail",
        ("GET", "PATCH", "DELETE"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT, PermissionKey.DATA_FLOWS_EDIT),
        organization_scoped=True,
    ),
    route(
        "organization-data-flow-revisions",
        ("GET",),
        PermissionKey.DATA_FLOWS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-data-flow-snapshots",
        ("GET", "POST"),
        PermissionKey.DATA_FLOWS_VIEW,
        (PermissionKey.DATA_FLOWS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-data-flow-snapshot-export",
        ("GET",),
        PermissionKey.DATA_FLOWS_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-compliance-evidence-review",
        ("POST",),
        mutations=(PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-assignment-evidence-link",
        ("POST",),
        mutations=(PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-risk-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-risk-review",
        ("POST",),
        mutations=(PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-compliance-bundle-list-create",
        ("GET", "POST"),
        PermissionKey.COMPLIANCE_VIEW,
        (PermissionKey.COMPLIANCE_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-reminder-list-create",
        ("GET", "POST"),
        PermissionKey.DEADLINES_VIEW,
        (PermissionKey.DEADLINES_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-reminder-calendar",
        ("GET",),
        PermissionKey.DEADLINES_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-activity-list",
        ("GET",),
        PermissionKey.ACTIVITY_VIEW,
        organization_scoped=True,
    ),
    route(
        "organization-domain-list-create",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
    route("organization-domain-review", ("POST",), mutations=(PermissionKey.DOMAINS_EDIT,), organization_scoped=True),
    route(
        "organization-domain-monitoring",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-certificate-endpoint-list-create",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-certificate-monitoring",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-hostname-list-create",
        ("GET", "POST"),
        PermissionKey.DOMAINS_VIEW,
        (PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
    route(
        "organization-domain-observation-create",
        ("POST",),
        mutations=(PermissionKey.DOMAINS_EDIT,),
        organization_scoped=True,
    ),
)


PUBLIC_API_ROUTE_NAMES = frozenset(
    {
        "api-root",
        "api-docs",
        "schema",
        "health-live",
        "health-ready",
        "bootstrap-status",
        "bootstrap-owner",
        "auth-providers",
        "invitation-accept",
        "inbound-webhook",
    }
)
