RUNTIME_ROLE = "tekdocs_runtime"

ORGANIZATION_SCOPED_TABLES = (
    "core_entity",
    "core_site",
    "core_location",
    "core_customfielddefinition",
    "core_personassociation",
    "core_document",
    "core_block",
    "core_blockrevision",
    "core_documentplacement",
    "core_documentationlistingreference",
    "core_documentattachment",
    "core_documentpublication",
    "core_documentpublicationartifact",
    "core_documentpublicationcontrolevent",
    "core_credentialreference",
    "core_catalogproduct",
    "core_catalogmodel",
    "core_catalogspecificationdefinition",
    "core_catalogspecificationdefinitionversion",
    "core_catalogmodelrevision",
    "core_catalogproductdocument",
    "core_clientasset",
    "core_clientassetdocumentprovenance",
    "core_clienthardwareasset",
    "core_clientassetlifecycleevent",
    "core_clientsoftwareinstallation",
    "core_softwarelicense",
    "core_softwarelicenseinstallation",
    "core_softwarelicenseseat",
    "core_softwarelicenseevent",
    "core_commercialcontract",
    "core_contractcost",
    "core_networkrack",
    "core_networkdevice",
    "core_networkvrf",
    "core_networkvlan",
    "core_networksubnet",
    "core_networkinterface",
    "core_networkipaddress",
    "core_networkmacaddress",
    "core_wirelessnetwork",
    "core_dnszone",
    "core_dnsrecord",
    "core_networkcircuit",
    "core_networkcircuithandoff",
    "core_netboxreference",
)

TENANT_SCOPED_TABLES = (
    "core_organization",
    "core_organizationclassification",
    "core_customfielddefinitionversion",
    "core_person",
    "core_entitylink",
    "core_auditevent",
    "core_outboxevent",
    "core_outboxdeliveryreceipt",
    "core_inboxnotification",
    "core_notificationpreference",
    "core_notificationemaildelivery",
    "core_webhookoutbounddelivery",
    "core_webhookinboundreceipt",
)

RLS_TABLES = ORGANIZATION_SCOPED_TABLES + TENANT_SCOPED_TABLES
