# Generated by Django 5.2.17 on 2026-08-07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_membership(apps, schema_editor):  # type: ignore[no-untyped-def]
    installation_state = apps.get_model("core", "InstallationState")
    tenant_membership = apps.get_model("accounts", "TenantMembership")
    state = installation_state.objects.filter(pk=1, tenant__isnull=False, owner__isnull=False).first()
    if state is not None:
        tenant_membership.objects.get_or_create(tenant_id=state.tenant_id, user_id=state.owner_id)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation"),
        ("core", "0002_installationstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "user"), name="unique_tenant_membership")
                ],
            },
        ),
        migrations.RunPython(create_owner_membership, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="pending") & ~models.Q(token_digest="")
                    | ~models.Q(state="pending") & models.Q(token_digest="")
                ),
                name="invitation_token_presence_matches_pending_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="accepted", accepted_at__isnull=False, accepted_by__isnull=False)
                    | ~models.Q(state="accepted")
                    & models.Q(accepted_at__isnull=True, accepted_by__isnull=True)
                ),
                name="invitation_acceptance_fields_match_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(state="revoked", revoked_at__isnull=False)
                    | ~models.Q(state="revoked") & models.Q(revoked_at__isnull=True)
                ),
                name="invitation_revocation_time_matches_state",
            ),
        ),
    ]
