# Generated by Django 5.2.17 on 2026-08-08 23:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

POSTGRES_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION tekdocs_validate_custom_role()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND (
        NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
        OR NEW.scope IS DISTINCT FROM OLD.scope
        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
    ) THEN
        RAISE EXCEPTION 'custom role ownership and scope are immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_custom_role_permission()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.permission NOT IN (
        'workspaces.view', 'organizations.view', 'organizations.create', 'organizations.edit',
        'organizations.archive', 'people.view', 'people.create', 'people.edit', 'people.archive',
        'sites.view', 'sites.create', 'sites.edit', 'sites.archive', 'custom_fields.view',
        'custom_fields.manage', 'custom_fields.edit_values', 'relationships.view',
        'relationships.create', 'relationships.archive', 'documents.view', 'documents.edit',
        'documents.publish', 'assets.view', 'assets.edit', 'networks.view', 'networks.edit',
        'compliance.view', 'compliance.edit', 'integrations.view'
    ) OR NOT EXISTS (
        SELECT 1 FROM accounts_customrole role
        WHERE role.id = NEW.role_id AND role.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'invalid custom role permission' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'custom role permission identity is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_scoped_role_assignment()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE role_scope varchar(16);
BEGIN
    SELECT scope INTO role_scope FROM accounts_customrole
      WHERE id = NEW.role_id AND tenant_id = NEW.tenant_id AND archived_at IS NULL;
    IF role_scope IS NULL OR NOT EXISTS (
        SELECT 1 FROM accounts_tenantmembership membership
        WHERE membership.id = NEW.membership_id AND membership.tenant_id = NEW.tenant_id
    ) OR EXISTS (
        SELECT 1
        FROM accounts_tenantmembership membership
        JOIN core_installationstate installation
          ON installation.tenant_id = membership.tenant_id
         AND installation.owner_id = membership.user_id
        WHERE membership.id = NEW.membership_id
    ) OR (NEW.organization_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_organization organization
        WHERE organization.id = NEW.organization_id AND organization.tenant_id = NEW.tenant_id
    )) OR (role_scope = 'tenant' AND NEW.organization_id IS NOT NULL)
       OR (role_scope = 'organization' AND NEW.organization_id IS NULL) THEN
        RAISE EXCEPTION 'invalid scoped role assignment' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'scoped role assignment identity is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER accounts_custom_role_guard BEFORE UPDATE ON accounts_customrole
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_custom_role();
CREATE TRIGGER accounts_custom_role_permission_guard BEFORE INSERT OR UPDATE ON accounts_customrolepermission
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_custom_role_permission();
CREATE TRIGGER accounts_scoped_role_assignment_guard BEFORE INSERT OR UPDATE ON accounts_scopedroleassignment
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_scoped_role_assignment();
"""

POSTGRES_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS accounts_scoped_role_assignment_guard ON accounts_scopedroleassignment;
DROP TRIGGER IF EXISTS accounts_custom_role_permission_guard ON accounts_customrolepermission;
DROP TRIGGER IF EXISTS accounts_custom_role_guard ON accounts_customrole;
DROP FUNCTION IF EXISTS tekdocs_validate_scoped_role_assignment();
DROP FUNCTION IF EXISTS tekdocs_validate_custom_role_permission();
DROP FUNCTION IF EXISTS tekdocs_validate_custom_role();
"""


def install_postgres_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRES_GUARD_SQL)


def remove_postgres_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRES_GUARD_REVERSE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_organization_access_assignment"),
        ("core", "0016_organization_access_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("name_key", models.CharField(editable=False, max_length=80)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "scope",
                    models.CharField(choices=[("tenant", "Tenant"), ("organization", "Organization")], max_length=16),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_custom_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="custom_roles", to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ("name_key", "id"),
            },
        ),
        migrations.CreateModel(
            name="CustomRolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("permission", models.CharField(max_length=80)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permission_rows",
                        to="accounts.customrole",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_role_permissions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("permission", "id"),
            },
        ),
        migrations.CreateModel(
            name="ScopedRoleAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_scoped_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_role_assignments",
                        to="accounts.tenantmembership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_role_assignments",
                        to="core.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.customrole",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_role_assignments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="customrole",
            index=models.Index(fields=["tenant", "scope", "archived_at"], name="accounts_role_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="customrole",
            constraint=models.UniqueConstraint(
                fields=("tenant", "scope", "name_key"), name="unique_custom_role_name_scope"
            ),
        ),
        migrations.AddIndex(
            model_name="customrolepermission",
            index=models.Index(fields=["tenant", "permission", "role"], name="accounts_role_perm_idx"),
        ),
        migrations.AddConstraint(
            model_name="customrolepermission",
            constraint=models.UniqueConstraint(fields=("role", "permission"), name="unique_custom_role_permission"),
        ),
        migrations.AddIndex(
            model_name="scopedroleassignment",
            index=models.Index(fields=["tenant", "membership", "organization"], name="accounts_scoped_role_idx"),
        ),
        migrations.AddConstraint(
            model_name="scopedroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("membership", "role"),
                name="unique_tenant_role_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopedroleassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("membership", "role", "organization"),
                name="unique_organization_role_assignment",
            ),
        ),
        migrations.RunPython(install_postgres_guards, remove_postgres_guards),
    ]
