# Generated by Django 5.2.17 on 2026-08-09 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customrole_customrolepermission_scopedroleassignment_and_more'),
        ('core', '0017_entity_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('name_key', models.CharField(editable=False, max_length=80)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AccessCollectionOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.RemoveIndex(
            model_name='scopedroleassignment',
            name='accounts_scoped_role_idx',
        ),
        migrations.AlterField(
            model_name='customrole',
            name='scope',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('organization', 'Organization'), ('collection', 'Collection')], max_length=16),
        ),
        migrations.AddField(
            model_name='accesscollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_access_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscollection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_collections', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='scopedroleassignment',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_role_assignments', to='accounts.accesscollection'),
        ),
        migrations.AddIndex(
            model_name='scopedroleassignment',
            index=models.Index(fields=['tenant', 'membership', 'organization', 'collection'], name='accounts_scoped_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='scopedroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', False)), fields=('membership', 'role', 'collection'), name='unique_collection_role_assignment'),
        ),
        migrations.RemoveConstraint(
            model_name='scopedroleassignment',
            name='unique_tenant_role_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='scopedroleassignment',
            name='unique_organization_role_assignment',
        ),
        migrations.AddConstraint(
            model_name='scopedroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', True), ('organization__isnull', True)), fields=('membership', 'role'), name='unique_tenant_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='scopedroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('collection__isnull', True), ('organization__isnull', False)), fields=('membership', 'role', 'organization'), name='unique_organization_role_assignment'),
        ),
        migrations.AddField(
            model_name='accesscollectionorganization',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_edges', to='accounts.accesscollection'),
        ),
        migrations.AddField(
            model_name='accesscollectionorganization',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_access_collection_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscollectionorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_collection_edges', to='core.organization'),
        ),
        migrations.AddField(
            model_name='accesscollectionorganization',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_collection_organizations', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='accesscollection',
            index=models.Index(fields=['tenant', 'archived_at'], name='accounts_collection_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesscollection',
            constraint=models.UniqueConstraint(fields=('tenant', 'name_key'), name='unique_access_collection_name'),
        ),
        migrations.AddIndex(
            model_name='accesscollectionorganization',
            index=models.Index(fields=['tenant', 'organization', 'collection'], name='accounts_collection_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesscollectionorganization',
            constraint=models.UniqueConstraint(fields=('collection', 'organization'), name='unique_access_collection_organization'),
        ),
    ]
