# Generated by Django 5.2.17 on 2026-08-12 06:21

import uuid
from importlib import import_module

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PREVIOUS_GUARD_SQL = import_module("apps.accounts.migrations.0016_client_portal_scope_guards").CLIENT_PORTAL_GUARD_SQL

API_TOKEN_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION tekdocs_validate_service_account()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.is_service_account AND (
        NEW.is_staff OR NEW.is_superuser OR NEW.password NOT LIKE '!%%'
    ) THEN
        RAISE EXCEPTION 'service accounts cannot use interactive authentication' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.is_service_account IS DISTINCT FROM OLD.is_service_account THEN
        RAISE EXCEPTION 'service account classification is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_tenant_membership()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.organization_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_organization organization
        JOIN core_entity entity ON entity.id = organization.entity_id AND entity.archived_at IS NULL
        JOIN core_organizationclassification classification
          ON classification.organization_id = organization.id AND classification.kind = 'client'
        WHERE organization.id = NEW.organization_id AND organization.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'client membership organization must be an active tenant client' USING ERRCODE = '23514';
    END IF;
    IF (NEW.role IN ('client_administrator', 'client_user')) IS DISTINCT FROM (NEW.organization_id IS NOT NULL) THEN
        RAISE EXCEPTION 'membership role does not match organization scope' USING ERRCODE = '23514';
    END IF;
    IF EXISTS (SELECT 1 FROM accounts_user WHERE id = NEW.user_id AND is_service_account) AND (
        NEW.role <> 'read_only' OR NEW.organization_id IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'service account membership must remain tenant read-only' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND (
        NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
        OR NEW.user_id IS DISTINCT FROM OLD.user_id
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
    ) THEN
        RAISE EXCEPTION 'tenant membership identity is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_api_token()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM core_installationstate state
        WHERE state.id = 1 AND state.tenant_id = NEW.tenant_id AND state.owner_id = NEW.created_by_id
    ) AND NOT EXISTS (
        SELECT 1 FROM accounts_tenantmembership membership
        WHERE membership.tenant_id = NEW.tenant_id AND membership.user_id = NEW.created_by_id
    ) THEN
        RAISE EXCEPTION 'API token creator must belong to its tenant' USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM core_installationstate state
        WHERE state.id = 1 AND state.tenant_id = NEW.tenant_id AND state.owner_id = NEW.subject_id
    ) AND NOT EXISTS (
        SELECT 1 FROM accounts_tenantmembership membership
        WHERE membership.tenant_id = NEW.tenant_id AND membership.user_id = NEW.subject_id
    ) THEN
        RAISE EXCEPTION 'API token subject must belong to its tenant' USING ERRCODE = '23514';
    END IF;
    IF NEW.organization_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM core_organization organization
        JOIN core_entity entity ON entity.id = organization.entity_id AND entity.archived_at IS NULL
        WHERE organization.id = NEW.organization_id AND organization.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'API token organization must be active in its tenant' USING ERRCODE = '23514';
    END IF;
    IF NEW.kind = 'personal' AND (
        NEW.subject_id <> NEW.created_by_id
        OR EXISTS (SELECT 1 FROM accounts_user WHERE id = NEW.subject_id AND is_service_account)
    ) THEN
        RAISE EXCEPTION 'personal token subject must be its human creator' USING ERRCODE = '23514';
    END IF;
    IF NEW.kind = 'service' AND NOT EXISTS (
        SELECT 1 FROM accounts_user user_record
        JOIN accounts_tenantmembership membership ON membership.user_id = user_record.id
        WHERE user_record.id = NEW.subject_id AND user_record.is_service_account
          AND membership.tenant_id = NEW.tenant_id AND membership.role = 'read_only'
          AND membership.organization_id IS NULL
    ) THEN
        RAISE EXCEPTION 'service token subject must be a read-only service account' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND (
        NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
        OR NEW.kind IS DISTINCT FROM OLD.kind
        OR NEW.subject_id IS DISTINCT FROM OLD.subject_id
        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
        OR NEW.workspace_scope IS DISTINCT FROM OLD.workspace_scope
        OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
        OR NEW.created_at IS DISTINCT FROM OLD.created_at
        OR (OLD.permissions_locked_at IS NOT NULL AND NEW.permissions_locked_at IS DISTINCT FROM OLD.permissions_locked_at)
        OR NEW.generation < OLD.generation
        OR (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at)
        OR (
            (
                NEW.prefix IS DISTINCT FROM OLD.prefix
                OR NEW.secret_hash IS DISTINCT FROM OLD.secret_hash
                OR NEW.expires_at > OLD.expires_at
            )
            AND NEW.generation <= OLD.generation
        )
    ) THEN
        RAISE EXCEPTION 'API token authority and lifecycle cannot be broadened' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION tekdocs_validate_api_token_permission()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'API token permissions are retained' USING ERRCODE = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM accounts_apitoken token
        WHERE token.id = NEW.token_id AND token.tenant_id = NEW.tenant_id
          AND (TG_OP <> 'INSERT' OR token.permissions_locked_at IS NULL)
    ) THEN
        RAISE EXCEPTION 'API token permission must share token tenant' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'API token permissions are immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS accounts_service_account_guard ON accounts_user;
CREATE TRIGGER accounts_service_account_guard
BEFORE INSERT OR UPDATE ON accounts_user
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_service_account();

DROP TRIGGER IF EXISTS accounts_api_token_guard ON accounts_apitoken;
CREATE TRIGGER accounts_api_token_guard
BEFORE INSERT OR UPDATE ON accounts_apitoken
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_api_token();

DROP TRIGGER IF EXISTS accounts_api_token_permission_guard ON accounts_apitokenpermission;
CREATE TRIGGER accounts_api_token_permission_guard
BEFORE INSERT OR UPDATE OR DELETE ON accounts_apitokenpermission
FOR EACH ROW EXECUTE FUNCTION tekdocs_validate_api_token_permission();
"""

API_TOKEN_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS accounts_api_token_permission_guard ON accounts_apitokenpermission;
DROP TRIGGER IF EXISTS accounts_api_token_guard ON accounts_apitoken;
DROP TRIGGER IF EXISTS accounts_service_account_guard ON accounts_user;
DROP FUNCTION IF EXISTS tekdocs_validate_api_token_permission();
DROP FUNCTION IF EXISTS tekdocs_validate_api_token();
DROP FUNCTION IF EXISTS tekdocs_validate_service_account();
"""


def install_api_token_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(PREVIOUS_GUARD_SQL)
        schema_editor.execute(API_TOKEN_GUARD_SQL)


def restore_previous_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(API_TOKEN_GUARD_REVERSE_SQL)
        schema_editor.execute(PREVIOUS_GUARD_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_client_portal_scope_guards'),
        ('core', '0075_network_record_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('service', 'Service')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('workspace_scope', models.CharField(choices=[('msp', 'MSP Workspace'), ('organization', 'Organization Workspace')], max_length=16)),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('secret_hash', models.CharField(max_length=256)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('permissions_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_tokens', to='core.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_tokens', to='core.tenant')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='APITokenPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=80)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_token_permissions', to='core.tenant')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_rows', to='accounts.apitoken')),
            ],
            options={
                'ordering': ('permission', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['tenant', 'subject', 'revoked_at'], name='accounts_token_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='apitoken',
            index=models.Index(fields=['tenant', 'kind', 'revoked_at'], name='accounts_token_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='apitoken',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('workspace_scope', 'msp')), models.Q(('organization__isnull', False), ('workspace_scope', 'organization')), _connector='OR'), name='api_token_workspace_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='apitoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='api_token_expires'),
        ),
        migrations.AddConstraint(
            model_name='apitokenpermission',
            constraint=models.UniqueConstraint(fields=('token', 'permission'), name='unique_api_token_permission'),
        ),
        migrations.RunPython(install_api_token_guards, restore_previous_guards),
    ]
