import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import type { Locator, Page } from '@playwright/test'

const columns = ['name', 'model', 'status', 'assignment', 'site', 'warranty']
async function fixtures(page: Page) {
  let preferences = { columns, available_columns: columns, default_columns: columns, page_size: 25 }
  const assets = Array.from({ length: 131 }, (_, index) => ({
    id: `asset-${index + 1}`, name: `Asset ${String(index + 1).padStart(3, '0')}${index === 0 ? ` ${'LongIdentifier'.repeat(15)}` : ''}`,
    kind: 'hardware', model_name: 'Business switch', model_number: 'SW-24', supplier_name: 'Synthetic supplier', product_name: 'Switch',
    model_revision: 1, specification_version: 1, provenance_checksum: 'a'.repeat(64), specifications: { ports: 24 }, documents: [], mac_addresses: [], software_installation: null,
    hardware: { serial_number: `SERIAL-${index + 1}`, asset_tag: '', lifecycle_state: 'in_service', acquired_on: null, acquisition_method: '', acquisition_reference: '', warranty_provider: '', warranty_starts_on: null, warranty_ends_on: '2030-01-01', warranty_reference: '', assignment: { person_name: 'Technician', site_name: 'Main office', location_name: null, person_id: null, site_id: null, location_id: null, assigned_at: null }, disposed_on: null, disposal_method: '', disposal_reason: '' },
  }))
  await page.route('**/api/v1/bootstrap/status', (route) => route.fulfill({ json: { bootstrap_required: false } }))
  await page.route('**/_allauth/browser/v1/auth/session', (route) => route.fulfill({ json: { meta: { is_authenticated: true } } }))
  await page.route('**/api/v1/auth/context', (route) => route.fulfill({ json: { user: { id: 'owner', email: 'layout@example.invalid', display_name: 'Layout owner' }, tenant: { id: 'installation', name: 'Synthetic MSP' }, role: 'owner', permissions: ['assets.view', 'assets.edit'], surface: 'msp', organization: null, mfa_enrollment_required: false } }))
  await page.route('**/collection-preferences/assets', (route) => {
    if (route.request().method() === 'PUT') preferences = { ...preferences, ...route.request().postDataJSON() as { columns: string[]; page_size: number } }
    if (route.request().method() === 'DELETE') preferences = { columns, available_columns: columns, default_columns: columns, page_size: 25 }
    return route.fulfill({ json: preferences })
  })
  await page.route('**/assets/collection?*', (route) => {
    const params = new URL(route.request().url()).searchParams
    const size = Number(params.get('page_size') ?? 25), pageNumber = Number(params.get('page') ?? 1)
    let found = assets.filter((asset) => `${asset.name} ${asset.hardware.serial_number}`.includes(params.get('search') ?? ''))
    if (params.get('kind') === 'software') found = []
    if (params.get('site')) found = found.filter((asset) => asset.id === 'asset-131')
    if (params.get('status')) found = found.filter((asset) => asset.hardware.lifecycle_state === params.get('status'))
    if (params.get('ordering')?.startsWith('-')) found = [...found].reverse()
    return route.fulfill({ json: { results: found.slice((pageNumber - 1) * size, pageNumber * size).map((asset) => ({ id: asset.id, name: asset.name, kind: asset.kind, model_name: asset.model_name, model_number: asset.model_number, status: asset.hardware.lifecycle_state, assignment: 'Technician', site: 'Main office', warranty_ends_on: '2030-01-01' })), count: found.length, page: pageNumber, page_size: size, has_more: pageNumber * size < found.length, can_manage: true, can_view_relationships: false, can_create_relationships: false, can_archive_relationships: false } })
  })
  await page.route(/\/assets\/asset-\d+$/, (route) => {
    const asset = assets.find((item) => route.request().url().endsWith(`/${item.id}`))
    return route.fulfill(asset ? { json: asset } : { status: 404, json: {} })
  })
  await page.route(/\/assets\/asset-\d+\/hardware$/, (route) => {
    const asset = assets.find((item) => route.request().url().includes(`/${item.id}/hardware`))!
    Object.assign(asset.hardware, route.request().postDataJSON() as object)
    return route.fulfill({ json: asset.hardware })
  })
  await page.route('**/assets/*/hardware/assignment-choices', (route) => route.fulfill({ json: {
    people: [{ id: 'person-2', name: 'Morgan' }], sites: [{ id: 'site-2', name: 'Branch' }], locations: [{ id: 'location-2', name: 'Office', site_id: 'site-2' }],
  } }))
  await page.route('**/assets/*/hardware/assignment', (route) => {
    const asset = assets.find((item) => route.request().url().includes(`/${item.id}/hardware`))!
    Object.assign(asset.hardware.assignment, route.request().postDataJSON(), { person_name: 'Morgan', site_name: 'Branch', location_name: 'Office' })
    return route.fulfill({ json: asset.hardware })
  })
  await page.route('**/assets/site-choices?*', (route) => {
    const query = new URL(route.request().url()).searchParams
    const sites = Array.from({ length: 31 }, (_, index) => ({ id: `site-${index + 1}`, name: `Site ${String(index + 1).padStart(3, '0')}${index === 30 ? ` ${'RemoteIdentifier'.repeat(20)}` : ''}` }))
    const matching = sites.filter((site) => site.name.includes(query.get('search') ?? ''))
    const pageNumber = Number(query.get('page') ?? 1)
    return route.fulfill({ json: { results: matching.slice((pageNumber - 1) * 25, pageNumber * 25), selected: sites.find((site) => site.id === query.get('selected')) ?? null, count: matching.length, page: pageNumber, page_size: 25, has_more: pageNumber * 25 < matching.length } })
  })
  return assets
}

for (const width of [320, 390, 768, 1024, 1280, 1440]) {
  test(`Assets list, preview and record fit ${width}px`, async ({ page }) => {
    const assets = await fixtures(page)
    await page.setViewportSize({ width, height: 600 })
    const details: string[] = []
    page.on('request', (request) => { if (/\/assets\/asset-\d+$/.test(request.url())) details.push(request.url()) })
    await page.goto('/assets')
    await expect(page.getByText('131 assets', { exact: true })).toBeVisible()
    expect(details).toHaveLength(0)
    if (process.env.LAYOUT_SCREENSHOT_DIR && test.info().project.name === 'chromium') await page.screenshot({ path: `${process.env.LAYOUT_SCREENSHOT_DIR}/assets-${width}.png`, fullPage: false })
    await page.getByRole('button', { name: 'Columns', exact: true }).click()
    await expect(page.getByRole('checkbox', { name: 'Name', exact: true })).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(page.getByRole('button', { name: assets[0].name, exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: assets[0].name, exact: true }).click()
    const drawer = page.getByRole('dialog', { name: assets[0].name })
    await expect(drawer).toBeVisible()
    expect(details).toHaveLength(1)
    await expect(drawer.getByRole('heading', { level: 2, name: assets[0].name })).toBeFocused()
    expect(await page.locator('body').evaluate((element) => element.style.overflow)).toBe('hidden')
    expect((await new AxeBuilder({ page }).include('.collection-drawer').analyze()).violations).toEqual([])
    expect(await drawer.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    if (process.env.LAYOUT_SCREENSHOT_DIR && test.info().project.name === 'chromium') await page.screenshot({ path: `${process.env.LAYOUT_SCREENSHOT_DIR}/preview-${width}.png` })
    if (width < 768) await drawer.getByRole('combobox', { name: 'Sections', exact: true }).selectOption('specifications')
    else await drawer.getByRole('link', { name: 'Specifications', exact: true }).click()
    await expect(page).toHaveURL(/preview=asset-1.*section=specifications/)
    await expect(drawer.getByRole('heading', { name: 'Saved specifications' })).toBeVisible()
    await page.reload()
    await expect(drawer.getByRole('heading', { name: 'Saved specifications' })).toBeVisible()
    expect(await drawer.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await dismissDrawer(page, drawer)
    await expect(drawer).toHaveCount(0)
    await expect(page).not.toHaveURL(/preview=|section=/)
    await page.getByRole('button', { name: assets[0].name, exact: true }).click()
    await expect(drawer).toBeVisible()
    await expect(drawer.getByRole('heading', { level: 2, name: assets[0].name })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(drawer).toHaveCount(0)
    await expect(page.getByRole('button', { name: assets[0].name, exact: true })).toBeFocused()
    await expect(page.getByRole('link', { name: 'Open record', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: assets[0].name, exact: true }).click()
    await drawer.getByRole('link', { name: 'Open in full page' }).click()
    await expect(drawer).toHaveCount(0)
    await expect(page).toHaveURL(/record=asset-1/)
    await expect(page.getByRole('heading', { level: 1, name: assets[0].name })).toBeVisible()
    if (width < 768) await page.getByRole('combobox', { name: 'Sections', exact: true }).selectOption('specifications')
    else await page.getByRole('link', { name: 'Specifications', exact: true }).click()
    await expect(page).toHaveURL(/section=specifications/)
    await expect(page.getByRole('heading', { name: assets[0].name, exact: true })).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width < 768) await page.getByRole('combobox', { name: 'Sections', exact: true }).selectOption('network')
    else await page.getByRole('link', { name: 'Network', exact: true }).click()
    await expect(page).toHaveURL(/section=network/)
    await page.goBack()
    await expect(page).toHaveURL(/section=specifications/)
    await page.goForward()
    await expect(page).toHaveURL(/section=network/)
    await expect(page.getByRole('heading', { name: assets[0].name, exact: true })).toBeFocused()
    await page.reload()
    await expect(page.getByRole('heading', { name: 'MAC addresses' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('link', { name: 'Back to assets' }).click()
    await expect(page.getByText('131 assets', { exact: true })).toBeVisible()
  })
}

test('Assets searches beyond page one, clears page selection, and persists columns', async ({ page }) => {
  await fixtures(page)
  await page.goto('/assets')
  await page.getByLabel('Select this page', { exact: true }).check()
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Search assets' }).fill('SERIAL-131')
  await page.locator('.collection-search').getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Asset 131', exact: true })).toBeVisible()
  await expect(page).not.toHaveURL(/page=2/)
  await page.getByRole('button', { name: 'Columns', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Warranty', exact: true }).uncheck()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('columnheader', { name: 'Warranty' })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Asset 131', exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Warranty' })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Rows per page' }).selectOption('50')
  await expect(page).toHaveURL(/page_size=50/)
  await page.getByRole('button', { name: 'Columns', exact: true }).click()
  await page.getByRole('button', { name: 'Reset to defaults' }).click()
  await expect(page).not.toHaveURL(/page_size=/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('columnheader', { name: 'Warranty' })).toBeVisible()
})

test('preview preserves a dirty status when closing is canceled', async ({ page }) => {
  await fixtures(page)
  await page.goto('/assets')
  await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Asset 002' })
  await drawer.getByRole('button', { name: 'Edit details' }).click()
  await drawer.getByRole('combobox', { name: 'Lifecycle state' }).selectOption('repair')
  await dismissDrawer(page, drawer)
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(drawer.getByRole('combobox', { name: 'Lifecycle state' })).toHaveValue('repair')
  await drawer.getByRole('button', { name: 'Save details' }).click()
  await expect(drawer.getByRole('button', { name: 'Edit details' })).toBeVisible()
  await dismissDrawer(page, drawer)
  await expect(drawer).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Asset 002' })).toContainText('repair')
})

test('a status update explains a record leaving the active filter and restores focus', async ({ page }) => {
  await fixtures(page)
  await page.goto('/assets?status=in_service')
  await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Asset 002' })
  await drawer.getByRole('button', { name: 'Edit details' }).click()
  await drawer.getByRole('combobox', { name: 'Lifecycle state' }).selectOption('repair')
  await drawer.getByRole('button', { name: 'Save details' }).click()
  await expect(drawer.getByRole('button', { name: 'Edit details' })).toBeVisible()
  await dismissDrawer(page, drawer)
  await expect(drawer).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('no longer appears on this page')
  await expect(page.getByRole('heading', { name: 'Assets', exact: true })).toBeFocused()
})

test('closing during a pending status save keeps the preview protected', async ({ page }) => {
  await fixtures(page)
  let release = () => {}
  const pending = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/assets/asset-2/hardware', async (route) => { await pending; await route.fallback() })
  await page.goto('/assets')
  await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Asset 002' })
  await drawer.getByRole('button', { name: 'Edit details' }).click()
  await drawer.getByRole('combobox', { name: 'Lifecycle state' }).selectOption('repair')
  await drawer.getByRole('button', { name: 'Save details' }).click()
  await expect(drawer.getByRole('combobox', { name: 'Lifecycle state' })).toBeDisabled()
  await dismissDrawer(page, drawer)
  await expect(page.getByRole('button', { name: 'Discard changes' })).toBeDisabled()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  release()
  await expect(drawer.getByRole('button', { name: 'Edit details' })).toBeVisible()
  await dismissDrawer(page, drawer)
  await expect(drawer).toHaveCount(0)
})

test('touch preview and 200 percent CSS zoom retain usable actions', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 600 }, hasTouch: true })
  try {
    const page = await context.newPage()
    await fixtures(page)
    await page.goto('/assets')
    await page.getByRole('button', { name: 'Asset 002', exact: true }).tap()
    await expect(page.getByRole('dialog', { name: 'Asset 002' })).toBeVisible()
    await page.getByRole('link', { name: 'Back to assets', exact: true }).tap()
    await page.setViewportSize({ width: 1280, height: 600 })
    await page.evaluate(() => { document.documentElement.style.zoom = '2' })
    await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
    const drawer = page.getByRole('dialog', { name: 'Asset 002' })
    await expect(drawer.getByRole('heading', { name: 'Asset 002', exact: true })).toBeVisible()
    expect(await drawer.evaluate((element) => { const bounds = element.getBoundingClientRect(); return element.scrollWidth <= element.clientWidth && bounds.bottom <= innerHeight + 1 && bounds.right <= innerWidth + 1 })).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  } finally { await context.close() }
})


for (const width of [320, 390, 768, 1024, 1280, 1440]) {
  test(`preview assignment fits ${width}px and preserves choices through canceled close`, async ({ page }) => {
    await fixtures(page)
    await page.setViewportSize({ width, height: 600 })
    await page.goto('/assets')
    await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
    const drawer = page.getByRole('dialog', { name: 'Asset 002' })
    await drawer.getByRole('button', { name: 'Assign hardware' }).click()
    await drawer.getByLabel('Person', { exact: true }).selectOption('person-2')
    await drawer.getByLabel('Location', { exact: true }).selectOption('location-2')
    await expect(drawer.getByLabel('Site', { exact: true })).toHaveValue('site-2')
    await dismissDrawer(page, drawer)
    await page.getByRole('button', { name: 'Keep editing' }).click()
    await expect(drawer.getByLabel('Location', { exact: true })).toHaveValue('location-2')
    expect(await drawer.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    const accessibility = await new AxeBuilder({ page }).include('.collection-drawer').analyze()
    expect(accessibility.violations).toEqual([])
    await drawer.getByRole('button', { name: 'Save assignment' }).click()
    await expect(drawer.getByRole('button', { name: 'Edit details' })).toBeVisible()
    await expect(drawer.getByRole('definition').filter({ hasText: 'Morgan' })).toBeVisible()
    await dismissDrawer(page, drawer)
    await expect(drawer).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Asset 002', exact: true })).toBeFocused()
  })
}


for (const width of [320, 390, 768, 1024, 1280, 1440]) {
  test(`site filter fits ${width}px and finds off-page sites`, async ({ page }) => {
    await fixtures(page)
    await page.setViewportSize({ width, height: 600 })
    await page.goto('/assets')
    await page.getByRole('checkbox', { name: 'Select Asset 002', exact: true }).check()
    await page.getByRole('button', { name: 'Filters', exact: true }).click()
    const filters = page.getByRole('dialog', { name: 'Filters', exact: true })
    await filters.locator('summary').filter({ hasText: /^Site/ }).click()
    await filters.getByRole('button', { name: 'Next' }).click()
    await expect(filters.getByRole('radio', { name: 'Site 031' })).toBeVisible()
    await filters.getByLabel('Search sites', { exact: true }).fill('031')
    await filters.getByRole('button', { name: 'Search', exact: true }).click()
    await filters.getByRole('radio', { name: 'Site 031' }).click()
    await expect(filters.getByRole('radio', { name: 'Site 031' })).toBeChecked()
    await expect(page).toHaveURL(/site=site-31/)
    await expect(page.getByRole('checkbox', { name: 'Select Asset 131', exact: true })).not.toBeChecked()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Remove site' })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('button', { name: 'Remove site' })).toContainText('Site 031')
    await page.getByRole('button', { name: 'Remove site' }).click()
    await expect(page).not.toHaveURL(/site=/)
    await expect(page.getByRole('button', { name: 'Asset 002', exact: true })).toBeVisible()
  })
}

for (const width of [320, 390, 768, 1024, 1280, 1440]) {
  test(`software history loads on demand and pages at ${width}px`, async ({ page }) => {
    const assets = await fixtures(page)
    await page.route('**/assets/asset-1', (route) => route.fulfill({ json: { ...assets[0], kind: 'software', hardware: null, software_installation: { status: 'installed', installed_version: '7.4.1', site_name: null } } }))
    const reads: string[] = []
    await page.route('**/api/v1/activity?*', (route) => {
      reads.push(route.request().url())
      const query = new URL(route.request().url()).searchParams
      expect(query.get('entity_id')).toBe('asset-1')
      expect(query.get('page_size')).toBe('25')
      const pageNumber = Number(query.get('page'))
      return route.fulfill({ json: { results: Array.from({ length: pageNumber === 1 ? 25 : 6 }, (_, index) => ({ id: `event-${pageNumber}-${index}`, action: pageNumber === 1 ? 'asset.software.updated' : 'asset.created_from_catalog', actor_name: `Technician ${'LongName'.repeat(30)}`, occurred_at: '2026-09-12T12:00:00Z' })), count: 31, page: pageNumber, page_size: 25, has_more: pageNumber === 1, actions: [] } })
    })
    await page.setViewportSize({ width, height: 600 })
    await page.goto('/assets?record=asset-1')
    await expect(page.getByRole('heading', { name: assets[0].name })).toBeVisible()
    expect(reads).toHaveLength(0)
    if (width < 768) await page.getByRole('combobox', { name: 'Sections', exact: true }).selectOption('history')
    else await page.getByRole('link', { name: 'History', exact: true }).click()
    await expect(page.getByText('Installation updated', { exact: true })).toHaveCount(25)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect((await new AxeBuilder({ page }).include('.asset-record').analyze()).violations).toEqual([])
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(page).toHaveURL(/history_page=2/)
    await expect(page.getByText('Created from catalog', { exact: true })).toHaveCount(6)
    await expect(page.getByRole('heading', { name: 'History', exact: true })).toBeFocused()
    await expect(page.getByRole('heading', { name: 'History', exact: true })).toBeInViewport()
    await page.reload()
    await expect(page.getByText('Created from catalog', { exact: true })).toHaveCount(6)
    await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
    await page.goBack()
    await expect(page.getByText('Installation updated', { exact: true })).toHaveCount(25)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('drawer guards section and full-page navigation and preserves the selected section', async ({ page }) => {
  await fixtures(page)
  await page.goto('/assets?preview=asset-2')
  const drawer = page.getByRole('dialog', { name: 'Asset 002' })
  await drawer.getByRole('button', { name: 'Edit details' }).click()
  await drawer.getByLabel('Serial number').fill('UNSAVED-SERIAL')
  await drawer.getByRole('link', { name: 'Specifications', exact: true }).click()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(drawer.getByLabel('Serial number')).toHaveValue('UNSAVED-SERIAL')
  await drawer.getByRole('link', { name: 'Open in full page' }).click()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(drawer.getByLabel('Serial number')).toHaveValue('UNSAVED-SERIAL')
  await drawer.getByRole('link', { name: 'Specifications', exact: true }).click()
  await page.getByRole('button', { name: 'Discard changes' }).click()
  await expect(drawer.getByRole('heading', { name: 'Saved specifications' })).toBeVisible()
  await drawer.getByRole('link', { name: 'Network', exact: true }).click()
  await page.goBack()
  await expect(drawer.getByRole('heading', { name: 'Saved specifications' })).toBeVisible()
  await page.goForward()
  await expect(drawer.getByRole('heading', { name: 'MAC addresses' })).toBeVisible()
  await expect(drawer.getByRole('link', { name: 'Open in full page' })).toHaveAttribute('href', '/assets?record=asset-2&section=network')
  await drawer.getByRole('link', { name: 'Open in full page' }).click()
  await expect(drawer).toHaveCount(0)
  await expect(page).toHaveURL(/record=asset-2.*section=network/)
  await expect(page.getByRole('heading', { name: 'MAC addresses' })).toBeVisible()
})

async function dismissDrawer(page: Page, drawer: Locator) {
  const bounds = await drawer.boundingBox()
  if (!bounds) throw new Error('Drawer is not visible')
  if (bounds.x > 0) await page.mouse.click(bounds.x / 2, bounds.y + 20)
  else await drawer.getByRole('link', { name: 'Back to assets', exact: true }).click()
}

test('drawer dismisses only gestures outside, without activating the underlying page', async ({ page }) => {
  await fixtures(page)
  await page.goto('/assets')
  await page.getByRole('button', { name: 'Asset 002', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: 'Asset 002' })
  await expect(drawer.getByRole('heading', { level: 2, name: 'Asset 002' })).toBeFocused()
  await expect(drawer.getByRole('button', { name: 'Close', exact: true })).toHaveCount(0)
  await drawer.getByRole('heading', { level: 2, name: 'Asset 002' }).click()
  await expect(drawer).toBeVisible()
  const bounds = (await drawer.boundingBox())!
  await page.mouse.move(bounds.x + 20, bounds.y + 20)
  await page.mouse.down()
  await page.mouse.move(bounds.x / 2, bounds.y + 20)
  await page.mouse.up()
  await expect(drawer).toBeVisible()
  await dismissDrawer(page, drawer)
  await expect(drawer).toHaveCount(0)
  await expect(page).toHaveURL(/\/assets$/)
  await expect(page.getByRole('button', { name: 'Asset 002', exact: true })).toBeFocused()
})
