import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
const organizationId = crypto.randomUUID(), documentId = crypto.randomUUID(), blockId = crypto.randomUUID(), revisionId = crypto.randomUUID()
const placement = { id: crypto.randomUUID(), block_id: blockId, block_name: 'Network guidance', block_kind: 'rich_text', parent_id: null, position: 0, depth: 0, resolution_mode: 'live', audience_profile: 'shared', pinned_revision_id: null, resolved_revision_id: revisionId, resolved_revision_number: 1, resolved_checksum: 'abc', resolved_markdown: 'Reviewed guidance', resolved_html: '<p>Reviewed guidance</p>', is_primary: true }
const record = { id: documentId, title: 'Network baseline', owner_kind: 'msp', owner_organization_id: null, owner_organization_name: null, is_reference: false, category: 'guide', is_template: true, library_visible: true, markdown: 'Reviewed guidance', block_id: blockId, current_revision_id: revisionId, revision_number: 1, checksum: 'abc', resolved_markdown: 'Reviewed guidance', placements: [placement, { ...placement, id: crypto.randomUUID(), block_id: crypto.randomUUID(), block_name: 'Shared instructions', is_primary: false, position: 1 }], placement_count: 2, attachments: [], attachment_count: 0, primary_file: null, primary_file_versions: [], publications: [], publication_count: 0, created_at: '2026-09-01T00:00:00Z', updated_at: '2026-09-01T00:00:00Z' }
async function setup(page: Page, baseURL?: string) {
  await page.context().addCookies([{ name: 'csrftoken', value: crypto.randomUUID().replaceAll('-', ''), url: baseURL! }])
  await page.route('**/api/v1/bootstrap/status', (r) => r.fulfill({ json: { bootstrap_required: false } }))
  await page.route('**/_allauth/browser/v1/auth/session', (r) => r.fulfill({ json: { meta: { is_authenticated: true } } }))
  await page.route('**/api/v1/auth/context', (r) => r.fulfill({ json: { user: { id: crypto.randomUUID(), email: 'owner@example.invalid', display_name: 'Owner' }, tenant: { id: crypto.randomUUID(), name: 'Example MSP' }, role: 'owner', permissions: ['documents.view', 'documents.edit'] } }))
  await page.route(`**/api/v1/workspaces/organizations/${organizationId}`, (r) => r.fulfill({ json: { kind: 'organization', id: organizationId, name: 'Example client', classifications: ['client'], capabilities: ['overview', 'documentation'], organization: null } }))
  await page.route('**/api/v1/documents/topic-schemas', (r) => r.fulfill({ json: { topics: [] } }))
  await page.route(`**/api/v1/workspaces/organizations/${organizationId}/documents**`, (r) => {
    const url = new URL(r.request().url())
    if (url.pathname.endsWith('/template-library')) return r.fulfill({ json: { results: [record], count: 26, page: Number(url.searchParams.get('page') ?? 1), page_size: 25, has_more: url.searchParams.get('page') !== '2' } })
    if (url.pathname.endsWith('/from-template')) return r.fulfill({ status: 403, json: { detail: 'Permission denied.' } })
    if (url.pathname.endsWith('/block-library')) return r.fulfill({ json: { results: [{ id: blockId, name: 'Reusable guidance', kind: 'rich_text', markdown: 'Reviewed content for insertion', revision_id: revisionId, revision_number: 1, source_document_id: crypto.randomUUID(), source_document_title: 'MSP standard', owner_kind: 'msp', owner_organization_id: null }], count: 21, page: Number(url.searchParams.get('page')), page_size: 20, has_more: url.searchParams.get('page') === '1' } })
    if (url.pathname.endsWith('/template-rollouts/preview')) return r.fulfill({ json: { enrollment_id: 'enrollment', applied_revision_id: revisionId, current_revision: 1, available_revision: 2, up_to_date: false, added: [{ source_block_id: blockId, name: 'New section' }], changed: [], removed: [], conflicts: [{ source_block_id: blockId, name: 'New section', reason: 'New template blocks with managed attachments require document re-instantiation.' }] } })
    if (url.pathname.endsWith('/operations/choices')) return r.fulfill({ json: [] })
    if (url.pathname.endsWith(`/${documentId}`)) return r.fulfill({ json: { ...record, is_template: false, template_enrollment_id: 'enrollment' } })
    return r.fulfill({ json: { results: [{ ...record, is_template: false, template_enrollment_id: 'enrollment' }], count: 1, page: 1, page_size: 25, has_more: false } })
  })
}
for (const width of [320, 390, 768, 1024, 1280, 1440]) {
  test(`template and reusable-content workflows at ${width}px`, async ({ page, baseURL }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await setup(page, baseURL)
    await page.goto(`/workspaces/organizations/${organizationId}/documentation?doc_library=templates`)
    await expect(page.getByLabel('Search templates')).toBeVisible()
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(page.getByText('Page 2', { exact: true })).toBeVisible()
    await page.getByLabel('Search templates').fill('Network')
    await expect(page.getByText('Page 1', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Use template' }).click()
    await expect(page.getByRole('heading', { name: 'Create from Network baseline' })).toBeFocused()
    await page.getByLabel('Document title').fill('Client network draft')
    await page.getByLabel('Shared instructions').selectOption('live')
    await page.getByText('Preview content', { exact: true }).first().click()
    await page.getByRole('button', { name: 'Create document', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Your choices are preserved')
    await expect(page.getByLabel('Shared instructions')).toHaveValue('live')
    await page.getByRole('button', { name: 'Documents', exact: true }).click()
    await page.getByRole('button', { name: 'Keep editing' }).click()
    await expect(page.getByLabel('Document title')).toHaveValue('Client network draft')
    expect((await new AxeBuilder({ page }).include('.client-template-library').withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
    if (testInfo.project.name === 'chromium' && [320, 1440].includes(width)) await page.screenshot({ path: `../artifacts/template-library-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Documents', exact: true }).click()
    await page.getByRole('button', { name: 'Discard changes' }).click()
    await page.getByRole('button', { name: 'Network baseline' }).click()
    await page.getByRole('button', { name: 'Add content here' }).last().click()
    await page.getByRole('button', { name: 'Existing content' }).click()
    await expect(page.getByText('Reusable guidance', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Next', exact: true }).click()
    await expect(page.getByText('Page 2', { exact: true })).toBeVisible()
    await page.getByText('Preview content', { exact: true }).click()
    await expect(page.getByText('Reviewed content for insertion')).toBeVisible()
    expect((await new AxeBuilder({ page }).include('.block-library').withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
    await page.getByRole('button', { name: 'Document settings' }).click()
    await page.getByRole('button', { name: 'Check template updates' }).click()
    await expect(page.getByRole('heading', { name: 'Changes need review' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Apply update' })).toBeDisabled()
    expect((await new AxeBuilder({ page }).include('.template-rollout').withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
  })
}
