import { randomBytes, randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import * as OTPAuth from 'otpauth'
import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

async function invitationTokenFromMailpit(page: Page) {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    const messagesResponse = await page.request.get('http://mailpit:8025/api/v1/messages')
    expect(messagesResponse.ok()).toBe(true)
    const messages = await messagesResponse.json() as { messages?: Array<{ ID?: string }> }
    const messageId = messages.messages?.[0]?.ID
    if (messageId) {
      const messageResponse = await page.request.get(`http://mailpit:8025/api/v1/message/${messageId}`)
      expect(messageResponse.ok()).toBe(true)
      const match = JSON.stringify(await messageResponse.json()).match(/#token=([A-Za-z0-9_-]+)/)
      if (match) return match[1]
    }
    await page.waitForTimeout(250)
  }
  throw new Error('The staff invitation did not arrive in Mailpit.')
}

test('real owner creates and enters a PostgreSQL-backed organization workspace', async ({ browser, page }) => {
  test.setTimeout(120_000)
  const deploymentToken = process.env.TEKDOCS_E2E_BOOTSTRAP_TOKEN
  if (!deploymentToken) throw new Error('The isolated live test requires TEKDOCS_E2E_BOOTSTRAP_TOKEN.')

  const suffix = randomUUID()
  const email = `workspace-owner-${suffix}@example.invalid`
  const password = `${randomBytes(24).toString('base64url')}Aa7!`

  await page.goto('/')
  await page.getByLabel('Deployment token').fill(deploymentToken)
  await page.getByLabel('MSP name').fill('Live Workspace MSP')
  await page.getByLabel('Your name').fill('Live Workspace Owner')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Confirm password').fill(password)
  await page.getByRole('button', { name: 'Create workspace' }).click()
  const bootstrapAlert = page.getByRole('alert')
  await Promise.race([
    page.getByRole('heading', { name: 'Overview' }).waitFor(),
    bootstrapAlert.waitFor(),
  ])
  if (await bootstrapAlert.isVisible()) {
    throw new Error(`Owner bootstrap failed in the live stack: ${await bootstrapAlert.textContent()}`)
  }
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()

  await page.goto('/settings')
  await page.getByRole('button', { name: 'Set up authenticator' }).click()
  const currentPassword = page.getByLabel('Current password')
  const setupAddressDisclosure = page.getByText('Show setup address')
  await Promise.race([currentPassword.waitFor(), setupAddressDisclosure.waitFor()])
  if (await currentPassword.isVisible()) {
    await currentPassword.fill(password)
    await page.getByRole('button', { name: 'Confirm change' }).click()
  }
  await setupAddressDisclosure.click()
  const setupAddress = await page.locator('.mfa-manual-setup details code').textContent()
  if (!setupAddress) throw new Error('Authenticator setup address was unavailable.')
  const totp = OTPAuth.URI.parse(setupAddress)
  if (!(totp instanceof OTPAuth.TOTP)) throw new Error('Authenticator setup did not return a TOTP address.')
  const secondsIntoWindow = Math.floor(Date.now() / 1000) % totp.period
  if (secondsIntoWindow >= totp.period - 5) {
    await page.waitForTimeout((totp.period - secondsIntoWindow + 1) * 1000)
  }
  await page.getByLabel('Authentication code').fill(totp.generate())
  await page.getByRole('button', { name: 'Enable two-factor authentication' }).click()
  await page.getByRole('button', { name: 'I saved these codes' }).click()

  await page.goto('/organizations')
  await page.getByRole('button', { name: 'New organization' }).click()
  await page.getByLabel('Display name').fill('Live Acme Client')
  await page.getByLabel(/Legal name/).fill('Live Acme Client, LLC')
  await page.getByLabel(/Website/).fill('https://live-acme.example.com')
  await page.getByRole('checkbox', { name: 'Vendor' }).check()
  await page.getByRole('button', { name: 'Save organization' }).click()
  await expect(page.getByRole('status')).toHaveText('Organization added.')

  const clientLink = page.getByRole('link', { name: 'Live Acme Client' })
  const clientHref = await clientLink.getAttribute('href')
  const clientId = clientHref?.match(/organizations\/([0-9a-f-]+)/)?.[1]
  if (!clientId) throw new Error('The created client did not expose its stable organization identifier.')

  const staffEmail = `live-technician-${suffix}@example.invalid`
  const csrfCookie = (await page.context().cookies()).find((cookie) => cookie.name === 'csrftoken')
  if (!csrfCookie) throw new Error('The owner session did not expose a CSRF cookie.')
  const invitationResponse = await page.request.post('/api/v1/invitations', {
    data: { email: staffEmail },
    headers: { 'X-CSRFToken': csrfCookie.value },
  })
  expect(invitationResponse.status()).toBe(201)
  const invitationToken = await invitationTokenFromMailpit(page)

  const staffContext = await browser.newContext()
  const staffPage = await staffContext.newPage()
  const staffPassword = `${randomBytes(24).toString('base64url')}Bb8!`
  await staffPage.goto(`/auth/invitations/accept#token=${invitationToken}`)
  await staffPage.getByLabel('Your name').fill('Live Assigned Technician')
  await staffPage.getByLabel('Password', { exact: true }).fill(staffPassword)
  await staffPage.getByLabel('Confirm password').fill(staffPassword)
  await staffPage.getByRole('button', { name: 'Activate account' }).click()
  await expect(staffPage.getByRole('heading', { name: 'Overview' })).toBeVisible()

  await page.getByRole('button', { name: /Account menu for Live Workspace Owner/ }).click()
  await page.getByRole('menuitem', { name: 'Access control' }).click()
  await expect(page.getByRole('heading', { name: 'Access control' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Staff member for Live Acme Client' }).selectOption({ label: 'Live Assigned Technician · Read-only' })
  await page.getByRole('button', { name: 'Review assignment' }).click()
  await expect(page.getByRole('alertdialog')).toContainText('Their MSP role still determines what they can do')
  await page.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByRole('status')).toContainText('Live Assigned Technician was assigned to Live Acme Client')
  await page.getByRole('combobox', { name: 'Access mode for Live Acme Client' }).selectOption('assigned_only')
  await page.getByRole('table', { name: 'Organization access modes' }).getByRole('button', { name: 'Review change' }).click()
  await expect(page.getByRole('alertdialog')).toContainText('The owner retains break-glass access')
  await page.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByRole('status')).toContainText("Live Acme Client's access mode was updated")

  const assignedWorkspace = await staffPage.request.get(`/api/v1/workspaces/organizations/${clientId}`)
  expect(assignedWorkspace.status()).toBe(200)
  await staffPage.goto(clientHref)
  await expect(staffPage.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()

  await page.goto('/organizations')

  await page.goto(clientHref)
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/overview$/)
  await expect(page.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()
  await expect(page.getByText('Live Acme Client, LLC')).toBeVisible()
  await expect(
    page.getByRole('main').getByText('Client · Vendor workspace', { exact: true }),
  ).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()

  await page.getByRole('link', { name: 'Return to MSP organizations' }).click()
  await page.getByRole('button', { name: 'New organization' }).click()
  await page.getByLabel('Display name').fill('Live Northwind Vendor')
  await page.getByRole('checkbox', { name: 'Client' }).uncheck()
  await page.getByRole('checkbox', { name: 'Vendor' }).check()
  await page.getByRole('button', { name: 'Save organization' }).click()
  await expect(page.getByRole('status')).toHaveText('Organization added.')
  await page.getByRole('link', { name: 'Live Acme Client' }).click()
  await page.getByRole('button', { name: 'Add relationship' }).click()
  await page.getByLabel('Relationship type').selectOption('supplied_by')
  await page.getByRole('searchbox', { name: 'Related organization' }).fill('Northwind')
  await page.getByRole('radio', { name: /Live Northwind Vendor/ }).check()
  await page.getByRole('button', { name: 'Add supplied by' }).click()
  await expect(page.getByText('Relationship added.')).toBeVisible()
  await expect(page.getByText('Supplied by')).toBeVisible()
  await page.getByRole('link', { name: 'Live Northwind Vendor' }).click()
  await expect(page.getByText('Supplies')).toBeVisible()
  await expect(page.getByText('Backlink')).toBeVisible()
  await page.getByRole('link', { name: 'Products' }).click()
  await page.getByRole('tab', { name: 'Specification sets' }).click()
  await page.getByRole('button', { name: 'New specification set' }).click()
  await page.getByLabel('Name').fill('Managed switch')
  await page.getByLabel('Key').fill('port_count')
  await page.getByLabel('Label').fill('Port count')
  await page.locator('.specification-row select').selectOption('integer')
  await page.getByLabel('Required').check()
  await page.getByRole('button', { name: 'Create specification set' }).click()
  await expect(page.getByText('Managed switch', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Products and models' }).click()
  await page.getByRole('button', { name: 'New product' }).click()
  await page.getByLabel('Name').fill('Live EdgeSwitch')
  await page.getByLabel('Description').fill('Live supplier catalog regression')
  await page.getByRole('button', { name: 'Create product' }).click()
  await expect(page.getByRole('heading', { name: 'Live EdgeSwitch' })).toBeVisible()
  await page.getByRole('button', { name: 'Add model' }).first().click()
  await page.getByLabel('Model name').fill('Live EdgeSwitch 24')
  await page.getByLabel('Model number or SKU').fill('LIVE-ES-24')
  await page.getByLabel('Port count *').fill('24')
  await page.getByLabel('Revision notes').fill('Live initial specification')
  await page.getByRole('button', { name: 'Add model' }).last().click()
  await expect(page.getByText('LIVE-ES-24 · active · revision 1')).toBeVisible()
  await page.getByRole('button', { name: 'Revise' }).click()
  await page.getByLabel('Revision notes').fill(' reviewed')
  await page.getByRole('button', { name: 'Create revision' }).click()
  await expect(page.getByText('LIVE-ES-24 · active · revision 2')).toBeVisible()
  await page.getByRole('tab', { name: 'Specification sets' }).click()
  await page.getByRole('button', { name: 'New specification set' }).click()
  await page.getByLabel('Name').fill('Endpoint software')
  await page.getByLabel('Product type').selectOption('software')
  await page.getByLabel('Key').fill('platform')
  await page.getByLabel('Label').fill('Supported platform')
  await page.getByLabel('Required').check()
  await page.getByRole('button', { name: 'Create specification set' }).click()
  await page.getByRole('tab', { name: 'Products and models' }).click()
  await page.getByRole('button', { name: 'New product' }).click()
  await page.getByLabel('Name').fill('Live Secure Agent')
  await page.locator('.catalog-editor').getByRole('combobox').selectOption('software')
  await page.getByLabel('Description').fill('Live software licensing regression')
  await page.getByRole('button', { name: 'Create product' }).click()
  await expect(page.getByRole('heading', { name: 'Live Secure Agent' })).toBeVisible()
  await page.getByRole('button', { name: 'Add model' }).first().click()
  await page.getByLabel('Model name').fill('Live Secure Agent Business')
  await page.getByLabel('Model number or SKU').fill('LIVE-SEC-BIZ')
  await page.getByLabel('Supported platform *').fill('macOS')
  await page.getByLabel('Revision notes').fill('Initial software release')
  await page.getByRole('button', { name: 'Add model' }).last().click()
  await expect(page.getByText('LIVE-SEC-BIZ · active · revision 1')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /Live Secure Agent.*software/ }).click()
  await expect(page.getByText('LIVE-SEC-BIZ · active · revision 1')).toBeVisible()
  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live EdgeSwitch installation guide')
  await page.locator('.document-edit-heading').getByLabel('Category').selectOption('guide')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Installation\n\nRetained supplier instructions.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('button', { name: 'Publish STATIC' }).click()
  await page.getByLabel('Publication reason').fill('Approved live product guide')
  await page.getByLabel('Audience').selectOption('client_visible')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Publish immutable version' }).click()
  await expect(page.getByText('Signature verified', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close publication' }).click()
  await page.getByRole('link', { name: 'Products' }).click()
  await page.getByRole('button', { name: 'Add publication' }).click()
  await page.getByLabel('STATIC publication').selectOption({ label: 'Live EdgeSwitch installation guide' })
  await page.getByLabel('Applies to').selectOption({ label: 'Live EdgeSwitch 24' })
  await page.getByRole('button', { name: 'Associate' }).click()
  await expect(page.getByText('Model: Live EdgeSwitch 24 · guide')).toBeVisible()
  await page.goto(clientHref)
  await page.getByRole('link', { name: 'Assets' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-ES-24')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live EdgeSwitch · Live EdgeSwitch 24 (LIVE-ES-24)' })
  await page.getByLabel('Asset name (optional)').fill('Live core switch')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live core switch' })).toBeVisible()
  await page.getByRole('button', { name: /Live EdgeSwitch installation guide/ }).click()
  await expect(page.getByText('Retained supplier instructions.')).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-SEC-BIZ')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live Secure Agent · Live Secure Agent Business (LIVE-SEC-BIZ)' })
  await page.getByLabel('Asset name (optional)').fill('Live endpoint protection')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live endpoint protection' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit installation' }).click()
  await page.getByLabel('Status').selectOption('installed')
  await page.getByLabel('Installed version').fill('7.4.1')
  await page.getByLabel('Installed on').fill('2026-08-10')
  await page.getByLabel('Last verified').fill('2026-08-10')
  await page.getByRole('button', { name: 'Save installation' }).click()
  await expect(page.getByText('7.4.1', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Vendors' }).click()
  await expect(page.getByText('Live Northwind Vendor', { exact: true })).toBeVisible()
  await expect(page.getByText('2 assets', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Current workspace: Live Acme Client/ }).click()
  await page.getByRole('textbox', { name: 'Find a client' }).fill('Live Acme')
  await expect(page.getByRole('button', { name: 'Live Acme Client. Client · Vendor' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to Live Workspace MSP. MSP workspace' }).click()
  await expect(page).toHaveURL((url) => url.pathname === '/vendors')
  await page.getByRole('button', { name: /Current workspace: Live Workspace MSP/ }).click()
  await page.getByRole('textbox', { name: 'Find an organization' }).fill('Live Acme')
  await page.getByRole('button', { name: 'Live Acme Client. Client · Vendor' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/vendors$/)

  await page.getByRole('link', { name: 'Custom fields' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/custom_fields$/)
  await page.getByRole('button', { name: /New field/ }).click()
  await page.getByLabel('Label').fill('Support tier')
  await page.getByLabel('Stable key').fill('support_tier')
  await page.getByLabel('Field type').selectOption('choice')
  await page.getByLabel(/Choices/).fill('Standard\nPriority')
  await page.getByRole('button', { name: 'Add field' }).click()
  await expect(page.getByText('Support tier', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Sites' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/sites$/)
  await page.getByRole('button', { name: 'New site' }).click()
  await page.getByLabel('Site name').fill('Live Main Campus')
  await page.getByLabel(/Code/).fill('MAIN')
  await page.getByLabel('Address', { exact: true }).fill('100 Main Street')
  await page.getByLabel('City').fill('Madison')
  await page.getByLabel('State or region').fill('WI')
  await page.getByLabel('Postal code').fill('53703')
  await page.getByLabel(/Country code/).fill('US')
  await page.getByLabel(/Timezone/).fill('America/Chicago')
  await page.getByRole('button', { name: 'Save site' }).click()
  await expect(page.getByText('Site added.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add location to Live Main Campus' }).click()
  await page.getByLabel('Name').fill('Building A')
  await page.getByLabel('Type').selectOption('building')
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByText('Location added.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add location to Live Main Campus' }).click()
  await page.getByLabel('Name').fill('Office 214')
  await page.getByLabel('Type').selectOption('office')
  await page.getByLabel('Parent').selectOption({ label: 'Building A (Building)' })
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByText('Location added.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Office 214', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Custom fields for site Live Main Campus' }).click()
  await page.getByLabel('Support tier').selectOption('Priority')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByLabel('Support tier')).toHaveValue('Priority')

  await page.getByRole('link', { name: 'Networks' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/networks$/)
  await page.getByRole('button', { name: 'Racks' }).click()
  await page.getByRole('button', { name: 'Add rack' }).click()
  await page.getByLabel('Name').fill('Live Core Rack')
  await page.getByLabel('Site').selectOption({ label: 'Live Main Campus' })
  await page.getByLabel('Location').selectOption({ label: 'Building A' })
  await page.getByLabel('Rack units').fill('42')
  await page.getByRole('button', { name: 'Save rack' }).click()
  await expect(page.getByRole('cell', { name: 'Live Core Rack', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Devices' }).click()
  await page.getByRole('button', { name: 'Add device' }).click()
  await page.getByLabel('Name').fill('Live Core Switch')
  await page.getByLabel('Role').selectOption('switch')
  await page.getByLabel('Rack').selectOption({ label: 'Live Core Rack' })
  await page.getByLabel('Starting unit').fill('20')
  await page.getByLabel('Height (U)').fill('2')
  await page.getByRole('button', { name: 'Save device' }).click()
  await expect(page.getByRole('button', { name: 'Live Core Switch' })).toBeVisible()
  await expect(page.getByRole('cell', { name: /Live Core Rack · U20–21/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Live Core Switch' })).toBeVisible()

  await page.getByRole('button', { name: 'Subnets' }).click()
  await page.getByRole('button', { name: 'Add subnet' }).click()
  await page.getByLabel('Name').fill('Live management LAN')
  await page.getByLabel(/^CIDR/).fill('192.0.2.0/24')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByRole('cell', { name: '192.0.2.0/24', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Interfaces' }).click()
  await page.getByRole('button', { name: 'Add interface' }).click()
  await page.getByLabel('Name').fill('ethernet1')
  await page.getByLabel('Device').selectOption({ label: 'Live Core Switch' })
  await page.getByRole('button', { name: 'Save interface' }).click()
  await expect(page.getByRole('cell', { name: 'ethernet1', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'IP addresses' }).click()
  await page.getByRole('button', { name: 'Add IP address' }).click()
  await page.getByLabel('IP address').fill('192.0.2.10')
  await page.getByLabel('Subnet').selectOption({ label: 'Live management LAN · 192.0.2.0/24' })
  await page.getByLabel('Interface').selectOption({ label: 'Live Core Switch · ethernet1' })
  await page.getByLabel('DNS name').fill('switch.live.example.invalid')
  await page.getByRole('button', { name: 'Save IP address' }).click()
  await expect(page.getByRole('cell', { name: '192.0.2.10', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'MAC addresses' }).click()
  await page.getByRole('button', { name: 'Add MAC address' }).click()
  await page.getByLabel('MAC address').fill('02:00:00:00:00:10')
  await page.getByLabel('Interface').selectOption({ label: 'Live Core Switch · ethernet1' })
  await page.getByRole('button', { name: 'Save MAC address' }).click()
  await expect(page.getByRole('cell', { name: '02:00:00:00:00:10', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'IP addresses' }).click()
  await expect(page.getByRole('cell', { name: '192.0.2.10', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Wireless' }).click()
  await page.getByRole('button', { name: 'Add wireless network' }).click()
  await page.getByRole('textbox', { name: 'SSID', exact: true }).fill('Live Staff')
  await page.getByLabel('Site').selectOption({ label: 'Live Main Campus' })
  await page.getByLabel('Subnet').selectOption({ label: '192.0.2.0/24' })
  await page.getByLabel('Client isolation').check()
  await page.getByRole('button', { name: 'Save wireless network' }).click()
  await expect(page.getByRole('cell', { name: 'Live Staff', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'DNS' }).click()
  await page.getByRole('button', { name: 'Add zone' }).click()
  await page.getByLabel('Canonical zone name').fill('live.example.invalid')
  await page.getByRole('button', { name: 'Save zone' }).click()
  await page.getByRole('button', { name: 'Add record' }).click()
  await page.getByLabel('Owner name').fill('switch.live.example.invalid')
  await page.getByLabel('Linked IP inventory').selectOption({ label: '192.0.2.10' })
  await page.getByRole('button', { name: 'Save DNS record' }).click()
  await expect(page.getByRole('row').filter({ hasText: 'switch.live.example.invalid' })).toContainText('192.0.2.10')
  await page.reload()
  await page.getByRole('button', { name: 'DNS' }).click()
  await expect(page.getByText('192.0.2.10', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'People' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/people$/)
  await page.getByRole('button', { name: 'New person' }).click()
  await page.getByLabel('Full name').fill('Live Morgan Ellis')
  await page.getByLabel(/Preferred name/).fill('Morgan')
  await page.getByRole('combobox', { name: 'Relationship', exact: true }).selectOption('contact')
  await page.getByLabel(/Role/).fill('Office Manager')
  await page.getByLabel(/Responsibility/).fill('Office operations and vendor coordination')
  await page.getByLabel(/Structured site/).selectOption({ label: 'Live Main Campus' })
  await page.getByLabel(/Structured location/).selectOption({ label: 'Office 214' })
  await page.getByLabel(/Phone/).fill('+1 555 010 0299')
  await page.getByLabel(/Email/).fill('live-morgan@example.invalid')
  await page.getByRole('button', { name: 'Save person' }).click()
  await expect(page.getByText('Person added.', { exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Live Main Campus', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Office 214', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Choose visible columns' }).click()
  await page.getByRole('checkbox', { name: 'Responsibility' }).check()
  await expect(page.getByRole('cell', { name: 'Office operations and vendor coordination' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search all person fields' }).fill('vendor coordination')
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Assets' }).click()
  await expect(page.getByRole('heading', { name: 'Hardware lifecycle' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit details' }).click()
  await page.getByLabel('Serial number').fill('LIVE-SN-100')
  await page.getByLabel('Asset tag').fill('LIVE-SW-100')
  await page.getByLabel('Lifecycle state').selectOption('in_service')
  await page.getByLabel('Acquired on').fill('2026-08-01')
  await page.getByLabel('Acquisition method').selectOption('purchase')
  await page.getByLabel('Warranty provider').fill('Live Northwind Vendor')
  await page.getByLabel('Warranty ends').fill('2029-08-01')
  await page.getByRole('button', { name: 'Save details' }).click()
  await expect(page.getByText('LIVE-SN-100', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Assign' }).click()
  await page.getByLabel('Person').selectOption({ label: 'Live Morgan Ellis' })
  await page.getByLabel('Site').selectOption({ label: 'Live Main Campus' })
  await page.getByLabel('Location').selectOption({ label: 'Office 214' })
  await page.getByRole('button', { name: 'Save assignment' }).click()
  await expect(page.getByRole('definition').filter({ hasText: 'Live Morgan Ellis · Office 214 · Live Main Campus' })).toBeVisible()

  await page.getByRole('link', { name: 'Licenses' }).click()
  await page.getByRole('button', { name: 'New license' }).click()
  await page.getByLabel('License name').fill('Live Secure Agent subscription')
  await page.getByLabel('Initial software installation').selectOption({ label: 'Live endpoint protection · Live Secure Agent' })
  await page.getByLabel('Seat limit').fill('5')
  await page.getByLabel('Starts on').fill('2026-08-10')
  await page.getByLabel('Renews on').fill('2027-08-10')
  await page.getByLabel('Reference').fill('LIVE-AGR-100')
  await page.getByRole('button', { name: 'Create license' }).click()
  await expect(page.getByRole('heading', { name: 'Live Secure Agent subscription' })).toBeVisible()
  await page.getByRole('button', { name: 'Assign seat' }).click()
  await page.getByLabel('Person').selectOption({ label: 'Live Morgan Ellis' })
  await page.getByLabel('Installation').selectOption({ label: 'Live endpoint protection' })
  await page.getByRole('button', { name: 'Assign seat' }).click()
  await expect(page.getByText('Seat 1', { exact: true })).toBeVisible()
  await expect(page.getByText('Live Morgan Ellis · Live endpoint protection', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit license' }).click()
  await page.getByLabel('Renews on').fill('2027-09-10')
  await page.getByRole('button', { name: 'Save license' }).click()
  await expect(page.getByRole('definition').filter({ hasText: '2027-09-10 · auto-renew' })).toBeVisible()

  await page.getByRole('link', { name: 'Services' }).click()
  await page.getByRole('button', { name: 'New contract' }).click()
  await page.getByLabel('Contract name').fill('Live managed services agreement')
  await page.getByLabel('Provider').selectOption({ label: 'Live Northwind Vendor' })
  await page.getByLabel('Status').selectOption('active')
  await page.getByLabel('Starts on').fill('2026-08-10')
  await page.getByLabel('Renews on').fill('2027-08-10')
  await page.getByLabel('Renewal notice days').fill('45')
  await page.getByLabel('Reference').fill('LIVE-MSA-200')
  await page.getByLabel('Description').fill('Managed endpoint and network support')
  await page.getByLabel('Auto-renew').check()
  await page.getByRole('button', { name: 'Save contract' }).click()
  await expect(page.getByRole('heading', { name: 'Live managed services agreement' })).toBeVisible()
  await page.getByRole('button', { name: 'Add cost' }).click()
  await page.getByLabel('Cost label').fill('Managed service base')
  await page.getByLabel('Amount').fill('875.50')
  await page.getByLabel('Quantity').fill('1')
  await page.getByLabel('Reference').fill('LIVE-PRIVATE-RATE')
  await page.getByRole('dialog').getByRole('button', { name: 'Add cost' }).click()
  await expect(page.getByText(/USD 875.50/)).toBeVisible()

  await page.getByRole('link', { name: 'Networks' }).click()
  await page.getByRole('button', { name: 'Circuits' }).click()
  await page.getByRole('button', { name: 'Add circuit' }).click()
  const circuitForm = page.locator('form').filter({ has: page.getByRole('heading', { name: 'Add circuit' }) })
  await circuitForm.getByLabel('Name').fill('Live headquarters DIA')
  await circuitForm.getByLabel('Provider').selectOption({ label: 'Live Northwind Vendor' })
  await circuitForm.getByLabel('Contract').selectOption({ label: 'Live managed services agreement' })
  await circuitForm.getByLabel('Service identifier').fill('LIVE-DIA-1000')
  await circuitForm.getByLabel('Download Mbps').fill('1000')
  await circuitForm.getByLabel('Upload Mbps').fill('1000')
  await circuitForm.getByLabel('Service starts').fill('2026-08-10')
  await circuitForm.getByLabel('Review on').fill('2027-06-15')
  await circuitForm.getByRole('button', { name: 'Save circuit' }).click()
  await expect(page.getByRole('button', { name: 'Live headquarters DIA', exact: true })).toBeVisible()
  await expect(page.getByText('Live managed services agreement', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add handoff' }).click()
  const handoffForm = page.locator('form').filter({ has: page.getByRole('heading', { name: /Add handoff to Live headquarters DIA/ }) })
  await handoffForm.getByLabel('Name').fill('Live carrier demarc')
  await handoffForm.getByLabel('Connector').fill('LC')
  await handoffForm.getByLabel('Provider handoff reference').fill('LIVE-DEMARC-1')
  await handoffForm.getByLabel('Site').selectOption({ label: 'Live Main Campus' })
  await handoffForm.getByLabel('Device').selectOption({ label: 'Live Core Switch' })
  await handoffForm.getByLabel('Interface').selectOption({ label: 'ethernet1' })
  await handoffForm.getByRole('button', { name: 'Save handoff' }).click()
  await expect(page.getByText('Live carrier demarc', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Circuits' }).click()
  await expect(page.getByText('2027-06-15 · Review circuit', { exact: true })).toBeVisible()
  await expect(page.getByText(/A side · fiber · LC · ethernet1/)).toBeVisible()
  await page.getByRole('button', { name: 'NetBox' }).click()
  await expect(page.getByText('No NetBox identities match this workspace and search.')).toBeVisible()
  await page.getByRole('button', { name: 'Link record' }).click()
  await page.getByLabel('TekDocs record').selectOption({ label: 'Live Core Rack · Rack' })
  await page.getByLabel('NetBox numeric ID').fill('4107')
  await page.getByRole('button', { name: 'Link identity' }).click()
  await expect(page.getByRole('table', { name: 'NetBox object identities for this workspace' }).getByRole('cell', { name: '4107' })).toBeVisible()
  await page.getByRole('button', { name: 'All records' }).click()
  await page.getByRole('searchbox', { name: 'Search network inventory' }).fill('192.0.2.10')
  await expect(page.getByRole('cell', { name: '192.0.2.10', exact: true })).toBeVisible()
  const exportHref = await page.getByRole('link', { name: 'Export CSV' }).getAttribute('href')
  expect(exportHref).toMatch(/\/api\/v1\/workspaces\/organizations\/[0-9a-f-]+\/networks\/export$/)
  const exportResponse = await page.request.get(exportHref ?? '')
  expect(exportResponse.ok()).toBe(true)
  expect(exportResponse.headers()['content-type']).toContain('text/csv')
  expect(await exportResponse.text()).toContain('tekdocs.networks.v1')

  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live Acme onboarding')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Acme onboarding\n\nClient-owned canonical Markdown.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 1.')
  await page.reload()
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Acme onboarding\n\nRevision two is retained.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')
  await page.getByRole('button', { name: 'Revision history' }).click()
  await expect(page.getByRole('button', { name: /Revision 2.*Current/ })).toBeVisible()
  await page.getByRole('button', { name: /Revision 1/ }).click()
  await expect(page.locator('.revision-diff pre')).toContainText('# Acme onboarding')

  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live incident template')
  await page.locator('.document-edit-heading').getByLabel('Category').selectOption('procedure')
  await page.getByRole('checkbox', { name: 'Reusable template' }).check()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Incident response\n\nFollow the approved checklist.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 1.')
  await page.getByLabel('Attachment file').setInputFiles({
    name: 'incident-checklist.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Confirm scope\nPreserve evidence\n'),
  })
  await expect(page.getByRole('status')).toHaveText('incident-checklist.txt attached.')
  await page.getByRole('button', { name: 'Insert link' }).click()
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')
  await page.getByRole('button', { name: 'Use template' }).click()
  await expect(page.getByRole('status')).toHaveText('Independent document created from the template.')
  await expect(page.getByLabel('Document title')).toHaveValue('New from Live incident template')
  await expect(page.getByRole('checkbox', { name: 'Reusable template' })).not.toBeChecked()
  await expect(page.locator('.document-attachments').getByRole('link', { name: /incident-checklist\.txt/ })).toBeVisible()
  const exportPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Export Markdown' }).click()
  const exported = await exportPromise
  const exportedPath = await exported.path()
  if (!exportedPath) throw new Error('The Markdown export did not produce a local download.')
  const exportedMarkdown = await readFile(exportedPath, 'utf8')
  expect(exportedMarkdown).toContain('# Incident response')
  expect(exportedMarkdown).toMatch(/tekdocs:\/\/attachment\/[0-9a-f-]{36}/)

  await page.getByLabel('Markdown file to import').setInputFiles({
    name: 'live-import.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# Imported runbook\n\nCanonical UTF-8 Markdown.\n'),
  })
  await expect(page.getByRole('status')).toHaveText('Markdown imported as a new document.')
  await expect(page.getByLabel('Document title')).toHaveValue('live-import')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await expect(page.getByRole('textbox', { name: 'Markdown source' })).toHaveValue('# Imported runbook\n\nCanonical UTF-8 Markdown.\n')

  await page.getByRole('button', { name: /Current workspace: Live Acme Client/ }).click()
  await page.getByRole('button', { name: 'Back to Live Workspace MSP. MSP workspace' }).click()
  await page.getByRole('link', { name: 'Assets' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-ES-24')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live EdgeSwitch · Live EdgeSwitch 24 (LIVE-ES-24)' })
  await page.getByLabel('Asset name (optional)').fill('Live MSP core switch')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live MSP core switch' })).toBeVisible()
  await expect(page.getByText('Live core switch', { exact: true })).not.toBeVisible()
  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live shared response')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('One MSP-owned block.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('searchbox', { name: 'Find client organization' }).fill('Live Acme')
  await page.getByRole('button', { name: /Live Acme Client/ }).click()
  await expect(page.getByRole('status')).toHaveText('Reference added to Live Acme Client.')
  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await expect(page.getByRole('button', { name: /Live shared response.*MSP reference/ })).toBeVisible()
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await page.getByLabel('Document block').selectOption({ label: 'Live shared response — MSP reference' })
  await page.getByRole('button', { name: 'Add block' }).click()
  await expect(page.getByRole('status')).toHaveText('Live shared response added as a live block.')
  await expect(page.getByText(/Live · revision 1/)).toBeVisible()
  await page.getByRole('button', { name: 'Review reuse' }).nth(1).click()
  await expect(page.getByRole('heading', { name: 'Reuse impact' })).toBeVisible()
  await expect(page.getByText(/3 live audiences will update/)).toBeVisible()
  await page.getByRole('button', { name: 'Close reuse impact' }).click()
  await page.getByRole('searchbox', { name: 'Reference an entity' }).fill('Live Main Campus')
  await page.getByRole('button', { name: /Live Main Campus.*site.*Live Acme Client/ }).click()
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 3.')
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('One MSP-owned block.')

  await page.goto('/documentation')
  await page.getByRole('button', { name: 'Live shared response' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('MSP-owned block revision two.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('heading', { name: 'Reuse impact' })).toBeVisible()
  await page.getByRole('button', { name: 'Approve impact and save' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')

  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await expect(page.getByText(/Live · revision 2/)).toBeVisible()
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('MSP-owned block revision two.')
  await page.getByRole('button', { name: 'Pin revision' }).click()
  await expect(page.getByRole('status')).toHaveText('Block pinned to its current revision.')
  await page.getByRole('button', { name: 'Review reuse' }).nth(1).click()
  await expect(page.getByText(/1 pinned audience will stay unchanged/)).toBeVisible()
  await page.getByRole('button', { name: 'Detach into this workspace' }).click()
  await expect(page.getByRole('status')).toHaveText('Block detached as an independent copy in this workspace.')

  await page.goto('/documentation')
  await page.getByRole('button', { name: 'Live shared response' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('MSP-owned block revision three.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('button', { name: 'Approve impact and save' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 3.')

  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await expect(page.getByText(/Live · revision 1/)).toBeVisible()
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('MSP-owned block revision two.')
  await expect(page.locator('.resolved-markdown pre')).not.toContainText('revision three')

  await page.getByRole('button', { name: 'Publish STATIC' }).click()
  await page.getByLabel('Publication reason').fill('Live publication regression')
  await page.getByLabel('Audience').selectOption('client_visible')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Publish immutable version' }).click()
  await expect(page.getByRole('status')).toHaveText('Immutable STATIC publication and retained artifacts created.')
  await expect(page.getByRole('heading', { name: 'Live Acme onboarding' })).toBeVisible()
  await expect(page.getByText('Signature verified', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download PDF' })).toBeVisible()
  await expect(page.locator('.publication-integrity code').first()).toContainText(/^SHA-256 [0-9a-f]{64}$/)
  await page.getByRole('button', { name: 'Close publication' }).click()
  await expect(page.getByRole('button', { name: /Live Acme onboarding.*1 STATIC/ })).toBeVisible()

  const privateLink = 'https://start.1password.com/open/i?a=aaaaaaaaaaaaaaaaaaaaaaaaaa&v=vvvvvvvvvvvvvvvvvvvvvvvvvv&i=iiiiiiiiiiiiiiiiiiiiiiiiii&h=example.1password.com'
  await page.goto(`/workspaces/organizations/${clientId}/credentials`)
  await page.getByRole('button', { name: 'New reference' }).click()
  await page.getByLabel('Title', { exact: true }).fill('Live firewall administrator')
  await page.getByPlaceholder('https://start.1password.com/open/i?…').fill(privateLink)
  await page.getByRole('button', { name: 'Save reference' }).click()
  const providerHandoff = page.getByRole('link', { name: /Open in 1Password/ })
  await expect(providerHandoff).toBeVisible()
  const handoffHref = await providerHandoff.getAttribute('href')
  if (!handoffHref) throw new Error('The saved reference did not expose its same-origin handoff route.')
  expect(handoffHref).toMatch(new RegExp(`/api/v1/workspaces/organizations/${clientId}/credential-references/[0-9a-f-]+/open$`))
  const handoffResponse = await page.request.get(handoffHref, { maxRedirects: 0 })
  expect(handoffResponse.status()).toBe(302)
  expect(handoffResponse.headers().location).toBe(privateLink)
  await expect(page.locator('body')).not.toContainText(privateLink)
  await staffContext.close()
})
