import { randomBytes, randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import * as OTPAuth from 'otpauth'
import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

async function invitationTokenFromMailpit(page: Page, recipient: string) {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    const messagesResponse = await page.request.get('http://mailpit:8025/api/v1/messages')
    expect(messagesResponse.ok()).toBe(true)
    const messages = await messagesResponse.json() as { messages?: Array<{ ID?: string }> }
    for (const message of messages.messages ?? []) {
      const messageId = message.ID
      if (!messageId) continue
      const messageResponse = await page.request.get(`http://mailpit:8025/api/v1/message/${messageId}`)
      expect(messageResponse.ok()).toBe(true)
      const serialized = JSON.stringify(await messageResponse.json())
      if (!serialized.includes(recipient)) continue
      const match = serialized.match(/#token=([A-Za-z0-9_-]+)/)
      if (match) return match[1]
    }
    await page.waitForTimeout(250)
  }
  throw new Error(`The invitation for ${recipient} did not arrive in Mailpit.`)
}

async function enrollTotp(page: Page, password: string) {
  await page.goto('/settings')
  await page.getByRole('button', { name: 'Set up authenticator' }).click()
  const currentPassword = page.getByLabel('Current password')
  const setupAddressDisclosure = page.getByText('Show setup address')
  await Promise.race([currentPassword.waitFor(), setupAddressDisclosure.waitFor()])
  if (await currentPassword.isVisible()) {
    await currentPassword.fill(password)
    await page.getByRole('button', { name: 'Confirm change' }).click()
  }
  await setupAddressDisclosure.click()
  const setupAddress = await page.locator('.mfa-manual-setup details code').textContent()
  if (!setupAddress) throw new Error('Authenticator setup address was unavailable.')
  const totp = OTPAuth.URI.parse(setupAddress)
  if (!(totp instanceof OTPAuth.TOTP)) throw new Error('Authenticator setup did not return a TOTP address.')
  const enterCurrentCode = async () => {
    const secondsIntoWindow = Math.floor(Date.now() / 1000) % totp.period
    if (secondsIntoWindow >= totp.period - 5) {
      await page.waitForTimeout((totp.period - secondsIntoWindow + 1) * 1000)
    }
    await page.getByLabel('Authentication code').fill(totp.generate())
    await page.getByRole('button', { name: 'Enable two-factor authentication' }).click()
  }
  await enterCurrentCode()
  const savedCodes = page.getByRole('button', { name: 'I saved these codes' })
  await Promise.race([savedCodes.waitFor(), currentPassword.waitFor()])
  if (await currentPassword.isVisible()) {
    await currentPassword.fill(password)
    await page.getByRole('button', { name: 'Confirm change' }).click()
    await enterCurrentCode()
  }
  await savedCodes.click()
}

test('real owner creates and enters a PostgreSQL-backed organization workspace', async ({ browser, page }) => {
  test.setTimeout(300_000)
  page.setDefaultTimeout(15_000)
  const deploymentToken = process.env.TEKDOCS_E2E_BOOTSTRAP_TOKEN
  if (!deploymentToken) throw new Error('The isolated live test requires TEKDOCS_E2E_BOOTSTRAP_TOKEN.')

  const suffix = randomUUID()
  const email = `workspace-owner-${suffix}@example.invalid`
  const password = `${randomBytes(24).toString('base64url')}Aa7!`

  await page.goto('/')
  await page.getByLabel('Deployment token').fill(deploymentToken)
  await page.getByLabel('MSP name').fill('Live Workspace MSP')
  await page.getByLabel('Your name').fill('Live Workspace Owner')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Confirm password').fill(password)
  await page.getByRole('button', { name: 'Create workspace' }).click()
  const bootstrapAlert = page.getByRole('alert')
  await Promise.race([
    page.getByRole('heading', { name: 'Overview' }).waitFor(),
    bootstrapAlert.waitFor(),
  ])
  if (await bootstrapAlert.isVisible()) {
    throw new Error(`Owner bootstrap failed in the live stack: ${await bootstrapAlert.textContent()}`)
  }
  await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()

  await enrollTotp(page, password)

  await page.goto('/organizations')
  await page.getByRole('button', { name: 'New organization' }).click()
  await page.getByLabel('Display name').fill('Live Acme Client')
  await page.getByLabel(/Legal name/).fill('Live Acme Client, LLC')
  await page.getByLabel(/Website/).fill('https://live-acme.example.com')
  await page.getByRole('checkbox', { name: 'Vendor' }).check()
  await page.getByRole('button', { name: 'Save organization' }).click()
  await expect(page.getByRole('status')).toHaveText('Organization added.')

  const clientLink = page.getByRole('link', { name: 'Live Acme Client' })
  const clientHref = await clientLink.getAttribute('href')
  const clientId = clientHref?.match(/organizations\/([0-9a-f-]+)/)?.[1]
  if (!clientId) throw new Error('The created client did not expose its stable organization identifier.')

  const staffEmail = `live-technician-${suffix}@example.invalid`
  const csrfCookie = (await page.context().cookies()).find((cookie) => cookie.name === 'csrftoken')
  if (!csrfCookie) throw new Error('The owner session did not expose a CSRF cookie.')
  const invitationResponse = await page.request.post('/api/v1/invitations', {
    data: { email: staffEmail },
    headers: { 'X-CSRFToken': csrfCookie.value },
  })
  expect(invitationResponse.status()).toBe(201)
  const invitationToken = await invitationTokenFromMailpit(page, staffEmail)

  const staffContext = await browser.newContext()
  const staffPage = await staffContext.newPage()
  staffPage.setDefaultTimeout(15_000)
  const staffPassword = `${randomBytes(24).toString('base64url')}Bb8!`
  await staffPage.goto(`/auth/invitations/accept#token=${invitationToken}`)
  await staffPage.getByLabel('Your name').fill('Live Assigned Technician')
  await staffPage.getByLabel('Password', { exact: true }).fill(staffPassword)
  await staffPage.getByLabel('Confirm password').fill(staffPassword)
  await staffPage.getByRole('button', { name: 'Activate account' }).click()
  await expect(staffPage.getByRole('heading', { name: 'Overview' })).toBeVisible()

  await page.getByRole('button', { name: /Account menu for Live Workspace Owner/ }).click()
  await page.getByRole('menuitem', { name: 'Access control' }).click()
  await expect(page.getByRole('heading', { name: 'Access control' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Staff member for Live Acme Client' }).selectOption({ label: 'Live Assigned Technician · Read-only' })
  await page.getByRole('button', { name: 'Review assignment' }).click()
  await expect(page.getByRole('alertdialog')).toContainText('Their MSP role still determines what they can do')
  await page.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByRole('status')).toContainText('Live Assigned Technician was assigned to Live Acme Client')
  await page.getByRole('combobox', { name: 'Access mode for Live Acme Client' }).selectOption('assigned_only')
  await page.getByRole('table', { name: 'Organization access modes' }).getByRole('button', { name: 'Review change' }).click()
  await expect(page.getByRole('alertdialog')).toContainText('The owner retains break-glass access')
  await page.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByRole('status')).toContainText("Live Acme Client's access mode was updated")

  const technicianRow = page.getByRole('table', { name: 'MSP members' }).getByRole('row').filter({ hasText: 'Live Assigned Technician' })
  await technicianRow.getByRole('combobox', { name: 'Role for Live Assigned Technician' }).selectOption('administrator')
  await technicianRow.getByRole('button', { name: 'Review change' }).click()
  await expect(page.getByRole('alertdialog')).toContainText('Change Live Assigned Technician from Read-only to Administrator')
  await page.getByRole('button', { name: 'Confirm change' }).click()
  await expect(page.getByRole('status')).toContainText("Live Assigned Technician's role was updated")
  await enrollTotp(staffPage, staffPassword)

  const assignedWorkspace = await staffPage.request.get(`/api/v1/workspaces/organizations/${clientId}`)
  expect(assignedWorkspace.status()).toBe(200)
  await staffPage.goto(clientHref)
  await expect(staffPage.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()

  await page.goto('/organizations')

  await page.goto(clientHref)
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/overview$/)
  await expect(page.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()
  await expect(page.getByText('Live Acme Client, LLC')).toBeVisible()
  await expect(
    page.getByRole('main').getByText('Client · Vendor workspace', { exact: true }),
  ).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Live Acme Client' })).toBeVisible()

  await page.getByRole('link', { name: 'Return to MSP organizations' }).click()
  await page.getByRole('button', { name: 'New organization' }).click()
  await page.getByLabel('Display name').fill('Live Northwind Vendor')
  await page.getByRole('checkbox', { name: 'Client' }).uncheck()
  await page.getByRole('checkbox', { name: 'Vendor' }).check()
  await page.getByRole('button', { name: 'Save organization' }).click()
  await expect(page.getByRole('status')).toHaveText('Organization added.')
  const vendorHref = await page.getByRole('link', { name: 'Live Northwind Vendor' }).getAttribute('href')
  if (!vendorHref) throw new Error('The created vendor did not expose its workspace route.')
  await page.getByRole('link', { name: 'Live Acme Client' }).click()
  await page.getByRole('button', { name: 'Add relationship' }).click()
  await page.getByLabel('Relationship type').selectOption('supplied_by')
  await page.getByRole('searchbox', { name: 'Related organization' }).fill('Northwind')
  await page.getByRole('radio', { name: /Live Northwind Vendor/ }).check()
  await page.getByRole('button', { name: 'Add supplied by' }).click()
  await expect(page.getByText('Relationship added.')).toBeVisible()
  await expect(page.getByText('Supplied by')).toBeVisible()
  await page.getByRole('link', { name: 'Live Northwind Vendor' }).click()
  await expect(page.getByText('Supplies')).toBeVisible()
  await expect(page.getByText('Backlink')).toBeVisible()
  await page.getByRole('link', { name: 'Products' }).click()
  await page.getByRole('tab', { name: 'Specification sets' }).click()
  await page.getByRole('button', { name: 'New specification set' }).click()
  await page.getByLabel('Name').fill('Managed switch')
  await page.getByLabel('Key').fill('port_count')
  await page.getByLabel('Label').fill('Port count')
  await page.locator('.specification-row select').selectOption('integer')
  await page.getByLabel('Required').check()
  await page.getByRole('button', { name: 'Create specification set' }).click()
  await expect(page.getByText('Managed switch', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Products and models' }).click()
  await page.getByRole('button', { name: 'New product' }).click()
  await page.getByLabel('Name').fill('Live EdgeSwitch')
  await page.getByLabel('Description').fill('Live supplier catalog regression')
  await page.getByRole('button', { name: 'Create product' }).click()
  await expect(page.getByRole('heading', { name: 'Live EdgeSwitch' })).toBeVisible()
  await page.getByRole('button', { name: 'Add model' }).first().click()
  await page.getByLabel('Model name').fill('Live EdgeSwitch 24')
  await page.getByLabel('Model number or SKU').fill('LIVE-ES-24')
  await page.getByLabel('Port count *').fill('24')
  await page.getByLabel('Revision notes').fill('Live initial specification')
  await page.getByRole('button', { name: 'Add model' }).last().click()
  await expect(page.getByText('LIVE-ES-24 · active · revision 1')).toBeVisible()
  await page.getByRole('button', { name: 'Revise' }).click()
  await page.getByLabel('Revision notes').fill(' reviewed')
  await page.getByRole('button', { name: 'Create revision' }).click()
  await expect(page.getByText('LIVE-ES-24 · active · revision 2')).toBeVisible()
  await page.getByRole('tab', { name: 'Specification sets' }).click()
  await page.getByRole('button', { name: 'New specification set' }).click()
  await page.getByLabel('Name').fill('Endpoint software')
  await page.getByLabel('Product type').selectOption('software')
  await page.getByLabel('Key').fill('platform')
  await page.getByLabel('Label').fill('Supported platform')
  await page.getByLabel('Required').check()
  await page.getByRole('button', { name: 'Create specification set' }).click()
  await page.getByRole('tab', { name: 'Products and models' }).click()
  await page.getByRole('button', { name: 'New product' }).click()
  await page.getByLabel('Name').fill('Live Secure Agent')
  await page.locator('.catalog-editor').getByRole('combobox').selectOption('software')
  await page.getByLabel('Description').fill('Live software licensing regression')
  await page.getByRole('button', { name: 'Create product' }).click()
  await expect(page.getByRole('heading', { name: 'Live Secure Agent' })).toBeVisible()
  await page.getByRole('button', { name: 'Add model' }).first().click()
  await page.getByLabel('Model name').fill('Live Secure Agent Business')
  await page.getByLabel('Model number or SKU').fill('LIVE-SEC-BIZ')
  await page.getByLabel('Supported platform *').fill('macOS')
  await page.getByLabel('Revision notes').fill('Initial software release')
  await page.getByRole('button', { name: 'Add model' }).last().click()
  await expect(page.getByText('LIVE-SEC-BIZ · active · revision 1')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /Live Secure Agent.*software/ }).click()
  await expect(page.getByText('LIVE-SEC-BIZ · active · revision 1')).toBeVisible()
  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live EdgeSwitch installation guide')
  await page.locator('.document-edit-heading').getByLabel('Category').selectOption('guide')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Installation\n\nRetained supplier instructions.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('button', { name: 'Publish STATIC' }).click()
  await page.getByLabel('Publication reason').fill('Approved live product guide')
  await page.getByLabel('Audience').selectOption('client_visible')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Publish immutable version' }).click()
  await expect(page.getByRole('status')).toHaveText('STATIC snapshot submitted. A different authorized user must approve client portal availability.')
  await expect(page.getByText('Signature verified', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close publication' }).click()
  await staffPage.goto(vendorHref.replace(/\/overview$/, '/documentation'))
  await staffPage.locator('.static-publication-list').getByRole('button', { name: /Live EdgeSwitch installation guide/ }).click()
  await staffPage.getByRole('button', { name: 'Approve publication' }).click()
  await staffPage.getByLabel('Decision reason').fill('Independent supplier-document approval')
  staffPage.once('dialog', (dialog) => dialog.accept())
  await staffPage.getByRole('button', { name: 'Record approval' }).click()
  await expect(staffPage.getByRole('status')).toHaveText('Publication approved for its intended audience.')
  await page.getByRole('link', { name: 'Products' }).click()
  await page.getByRole('button', { name: 'Add publication' }).click()
  await page.getByLabel('STATIC publication').selectOption({ label: 'Live EdgeSwitch installation guide' })
  await page.getByLabel('Applies to').selectOption({ label: 'Live EdgeSwitch 24' })
  await page.getByRole('button', { name: 'Associate' }).click()
  await expect(page.getByText('Model: Live EdgeSwitch 24 · guide')).toBeVisible()
  await page.goto(clientHref)
  await page.getByRole('link', { name: 'Assets' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-ES-24')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live EdgeSwitch · Live EdgeSwitch 24 (LIVE-ES-24)' })
  await page.getByLabel('Asset name (optional)').fill('Live core switch')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live core switch' })).toBeVisible()
  await page.getByRole('button', { name: /Live EdgeSwitch installation guide/ }).click()
  await expect(page.getByText('Retained supplier instructions.')).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-SEC-BIZ')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live Secure Agent · Live Secure Agent Business (LIVE-SEC-BIZ)' })
  await page.getByLabel('Asset name (optional)').fill('Live endpoint protection')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live endpoint protection' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit installation' }).click()
  await page.getByLabel('Status').selectOption('installed')
  await page.getByLabel('Installed version').fill('7.4.1')
  await page.getByLabel('Installed on').fill('2026-08-10')
  await page.getByLabel('Last verified').fill('2026-08-10')
  await page.getByRole('button', { name: 'Save installation' }).click()
  await expect(page.getByText('7.4.1', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Vendors' }).click()
  await expect(page.getByText('Live Northwind Vendor', { exact: true })).toBeVisible()
  await expect(page.getByText('2 assets', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Current workspace: Live Acme Client/ }).click()
  await page.getByRole('textbox', { name: 'Find a client' }).fill('Live Acme')
  await expect(page.getByRole('button', { name: 'Live Acme Client. Client · Vendor' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to Live Workspace MSP. MSP workspace' }).click()
  await expect(page).toHaveURL((url) => url.pathname === '/vendors')
  await page.getByRole('button', { name: /Current workspace: Live Workspace MSP/ }).click()
  await page.getByRole('textbox', { name: 'Find an organization' }).fill('Live Acme')
  await page.getByRole('button', { name: 'Live Acme Client. Client · Vendor' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/vendors$/)

  await page.getByRole('link', { name: 'Custom fields' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/custom_fields$/)
  await page.getByRole('button', { name: /New field/ }).click()
  await page.getByLabel('Label').fill('Support tier')
  await page.getByLabel('Stable key').fill('support_tier')
  await page.getByLabel('Field type').selectOption('choice')
  await page.getByLabel(/Choices/).fill('Standard\nPriority')
  await page.getByRole('button', { name: 'Add field' }).click()
  await expect(page.getByText('Support tier', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Sites' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/sites$/)
  await page.getByRole('button', { name: 'New site' }).click()
  await page.getByLabel('Site name').fill('Live Main Campus')
  await page.getByLabel(/Code/).fill('MAIN')
  await page.getByLabel('Address', { exact: true }).fill('100 Main Street')
  await page.getByLabel('City').fill('Madison')
  await page.getByLabel('State or region').fill('WI')
  await page.getByLabel('Postal code').fill('53703')
  await page.getByLabel(/Country code/).fill('US')
  await page.getByLabel(/Timezone/).fill('America/Chicago')
  await page.getByRole('button', { name: 'Save site' }).click()
  await expect(page.getByText('Site added.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add location to Live Main Campus' }).click()
  await page.getByLabel('Name').fill('Building A')
  await page.getByLabel('Type').selectOption('building')
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByText('Location added.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add location to Live Main Campus' }).click()
  await page.getByLabel('Name').fill('Office 214')
  await page.getByLabel('Type').selectOption('office')
  await page.getByLabel('Parent').selectOption({ label: 'Building A (Building)' })
  await page.getByRole('button', { name: 'Save location' }).click()
  await expect(page.getByText('Location added.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Office 214', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Custom fields for site Live Main Campus' }).click()
  await page.getByLabel('Support tier').selectOption('Priority')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByLabel('Support tier')).toHaveValue('Priority')

  await page.getByRole('link', { name: 'Networks' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/networks$/)
  await page.getByRole('button', { name: 'New network' }).click()
  await page.getByLabel('Name').fill('Live management LAN')
  await page.getByLabel('Location').selectOption({ label: 'Live Main Campus · Building A' })
  await page.getByLabel('VLAN').fill('20')
  await page.getByLabel(/^Network \(CIDR\)/).fill('192.0.2.0/24')
  await page.getByLabel('Primary DNS').fill('9.9.9.9')
  await page.getByLabel('Secondary DNS').fill('1.1.1.1')
  await page.getByLabel('Description').fill('Core management network')
  await page.getByRole('button', { name: 'Save network' }).click()
  const networkRow = page.getByRole('row').filter({ hasText: 'Live management LAN' })
  await expect(networkRow).toContainText('192.0.2.0/24')
  await expect(networkRow).toContainText('192.0.2.1–192.0.2.254')
  await expect(networkRow).toContainText('192.0.2.1')
  await expect(networkRow).toContainText('9.9.9.9, 1.1.1.1')
  await page.reload()
  await page.getByLabel('Search networks').fill('management')
  await expect(page.getByRole('row').filter({ hasText: 'Live management LAN' })).toBeVisible()

  await page.getByRole('link', { name: 'People' }).click()
  await expect(page).toHaveURL(/\/workspaces\/organizations\/[0-9a-f-]+\/people$/)
  await page.getByRole('button', { name: 'New person' }).click()
  await page.getByLabel('Full name').fill('Live Morgan Ellis')
  await page.getByLabel(/Preferred name/).fill('Morgan')
  await page.getByRole('combobox', { name: 'Relationship', exact: true }).selectOption('contact')
  await page.getByLabel(/Role/).fill('Office Manager')
  await page.getByLabel(/Responsibility/).fill('Office operations and vendor coordination')
  await page.getByLabel(/Structured site/).selectOption({ label: 'Live Main Campus' })
  await page.getByLabel(/Structured location/).selectOption({ label: 'Office 214' })
  await page.getByLabel(/Phone/).fill('+1 555 010 0299')
  await page.getByLabel(/Email/).fill('live-morgan@example.invalid')
  await page.getByRole('button', { name: 'Save person' }).click()
  await expect(page.getByText('Person added.', { exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Live Main Campus', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Office 214', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Choose visible columns' }).click()
  await page.getByRole('checkbox', { name: 'Responsibility' }).check()
  await expect(page.getByRole('cell', { name: 'Office operations and vendor coordination' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search all person fields' }).fill('vendor coordination')
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('cell', { name: 'Live Morgan Ellis', exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Assets' }).click()
  await expect(page.getByRole('heading', { name: 'Hardware lifecycle' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit details' }).click()
  await page.getByLabel('Serial number').fill('LIVE-SN-100')
  await page.getByLabel('Asset tag').fill('LIVE-SW-100')
  await page.getByLabel('Lifecycle state').selectOption('in_service')
  await page.getByLabel('Acquired on').fill('2026-08-01')
  await page.getByLabel('Acquisition method').selectOption('purchase')
  await page.getByLabel('Warranty provider').fill('Live Northwind Vendor')
  await page.getByLabel('Warranty ends').fill('2029-08-01')
  await page.getByRole('button', { name: 'Save details' }).click()
  await expect(page.getByText('LIVE-SN-100', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Assign' }).click()
  await page.getByLabel('Person').selectOption({ label: 'Live Morgan Ellis' })
  await page.getByLabel('Site').selectOption({ label: 'Live Main Campus' })
  await page.getByLabel('Location').selectOption({ label: 'Office 214' })
  await page.getByRole('button', { name: 'Save assignment' }).click()
  await expect(page.getByRole('definition').filter({ hasText: 'Live Morgan Ellis · Office 214 · Live Main Campus' })).toBeVisible()
  await page.getByRole('button', { name: 'Add address' }).click()
  const macAddresses = page.getByRole('region', { name: 'MAC addresses' })
  await macAddresses.getByRole('textbox', { name: 'MAC address' }).fill('02:00:00:00:00:10')
  await macAddresses.getByLabel('Description').fill('Ethernet')
  await macAddresses.getByRole('button', { name: 'Save address' }).click()
  await expect(page.getByText('02:00:00:00:00:10', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Licenses' }).click()
  await page.getByRole('button', { name: 'New license' }).click()
  await page.getByLabel('License name').fill('Live Secure Agent subscription')
  await page.getByLabel('Initial software installation').selectOption({ label: 'Live endpoint protection · Live Secure Agent' })
  await page.getByLabel('Seat limit').fill('5')
  await page.getByLabel('Starts on').fill('2026-08-10')
  await page.getByLabel('Renews on').fill('2027-08-10')
  await page.getByLabel('Reference').fill('LIVE-AGR-100')
  await page.getByRole('button', { name: 'Create license' }).click()
  await expect(page.getByRole('heading', { name: 'Live Secure Agent subscription' })).toBeVisible()
  await page.getByRole('button', { name: 'Assign seat' }).click()
  await page.getByLabel('Person').selectOption({ label: 'Live Morgan Ellis' })
  await page.getByLabel('Installation').selectOption({ label: 'Live endpoint protection' })
  await page.getByRole('button', { name: 'Assign seat' }).click()
  await expect(page.getByText('Seat 1', { exact: true })).toBeVisible()
  await expect(page.getByText('Live Morgan Ellis · Live endpoint protection', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit license' }).click()
  await page.getByLabel('Renews on').fill('2027-09-10')
  await page.getByRole('button', { name: 'Save license' }).click()
  await expect(page.getByRole('definition').filter({ hasText: '2027-09-10 · auto-renew' })).toBeVisible()

  await page.getByRole('link', { name: 'Services' }).click()
  await page.getByRole('button', { name: 'New contract' }).click()
  await page.getByLabel('Contract name').fill('Live managed services agreement')
  await page.getByLabel('Provider').selectOption({ label: 'Live Northwind Vendor' })
  await page.getByLabel('Status').selectOption('active')
  await page.getByLabel('Starts on').fill('2026-08-10')
  await page.getByLabel('Renews on').fill('2027-08-10')
  await page.getByLabel('Renewal notice days').fill('45')
  await page.getByLabel('Reference').fill('LIVE-MSA-200')
  await page.getByLabel('Description').fill('Managed endpoint and network support')
  await page.getByLabel('Auto-renew').check()
  await page.getByRole('button', { name: 'Save contract' }).click()
  await expect(page.getByRole('heading', { name: 'Live managed services agreement' })).toBeVisible()
  await page.getByRole('button', { name: 'Add cost' }).click()
  await page.getByLabel('Cost label').fill('Managed service base')
  await page.getByLabel('Amount').fill('875.50')
  await page.getByLabel('Quantity').fill('1')
  await page.getByLabel('Reference').fill('LIVE-PRIVATE-RATE')
  await page.getByRole('dialog').getByRole('button', { name: 'Add cost' }).click()
  await expect(page.getByText(/USD 875.50/)).toBeVisible()

  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live Acme onboarding')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Acme onboarding\n\nClient-owned canonical Markdown.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 1.')
  await page.reload()
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Acme onboarding\n\nRevision two is retained.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')
  await page.getByRole('button', { name: 'Revision history' }).click()
  await expect(page.getByRole('button', { name: /Revision 2.*Current/ })).toBeVisible()
  await page.getByRole('button', { name: /Revision 1/ }).click()
  await expect(page.locator('.revision-diff pre')).toContainText('# Acme onboarding')

  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live incident template')
  await page.locator('.document-edit-heading').getByLabel('Category').selectOption('procedure')
  await page.getByRole('checkbox', { name: 'Reusable template' }).check()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('# Incident response\n\nFollow the approved checklist.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 1.')
  await page.getByLabel('Attachment file').setInputFiles({
    name: 'incident-checklist.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Confirm scope\nPreserve evidence\n'),
  })
  await expect(page.getByRole('status')).toHaveText('incident-checklist.txt attached.')
  await page.getByRole('button', { name: 'Insert link' }).click()
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')
  await page.getByRole('button', { name: 'Use template' }).click()
  await expect(page.getByRole('status')).toHaveText('Independent document created from the template.')
  await expect(page.getByLabel('Document title')).toHaveValue('New from Live incident template')
  await expect(page.getByRole('checkbox', { name: 'Reusable template' })).not.toBeChecked()
  await expect(page.locator('.document-attachments').getByRole('link', { name: /incident-checklist\.txt/ })).toBeVisible()
  const exportPromise = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Export Markdown' }).click()
  const exported = await exportPromise
  const exportedPath = await exported.path()
  if (!exportedPath) throw new Error('The Markdown export did not produce a local download.')
  const exportedMarkdown = await readFile(exportedPath, 'utf8')
  expect(exportedMarkdown).toContain('# Incident response')
  expect(exportedMarkdown).toMatch(/tekdocs:\/\/attachment\/[0-9a-f-]{36}/)

  await page.getByLabel('Markdown file to import').setInputFiles({
    name: 'live-import.md',
    mimeType: 'text/markdown',
    buffer: Buffer.from('# Imported runbook\n\nCanonical UTF-8 Markdown.\n'),
  })
  await expect(page.getByRole('status')).toHaveText('Markdown imported as a new document.')
  await expect(page.getByLabel('Document title')).toHaveValue('live-import')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await expect(page.getByRole('textbox', { name: 'Markdown source' })).toHaveValue('# Imported runbook\n\nCanonical UTF-8 Markdown.\n')

  await page.getByRole('button', { name: /Current workspace: Live Acme Client/ }).click()
  await page.getByRole('button', { name: 'Back to Live Workspace MSP. MSP workspace' }).click()
  await page.getByRole('link', { name: 'Assets' }).click()
  await page.getByRole('button', { name: 'New asset' }).click()
  await page.getByLabel('Find a supplier model').fill('LIVE-ES-24')
  await page.locator('.inventory-create select').selectOption({ label: 'Live Northwind Vendor · Live EdgeSwitch · Live EdgeSwitch 24 (LIVE-ES-24)' })
  await page.getByLabel('Asset name (optional)').fill('Live MSP core switch')
  await page.getByRole('button', { name: 'Create asset' }).click()
  await expect(page.getByRole('heading', { name: 'Live MSP core switch' })).toBeVisible()
  await expect(page.getByText('Live core switch', { exact: true })).not.toBeVisible()
  await page.getByRole('link', { name: 'Documentation' }).click()
  await page.getByRole('button', { name: 'New document' }).click()
  await page.getByLabel('Document title').fill('Live shared response')
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('One MSP-owned block.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('searchbox', { name: 'Find client organization' }).fill('Live Acme')
  await page.getByRole('button', { name: /Live Acme Client/ }).click()
  await expect(page.getByRole('status')).toHaveText('Reference added to Live Acme Client.')
  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await expect(page.getByRole('button', { name: /Live shared response.*MSP reference/ })).toBeVisible()
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await page.getByLabel('Document block').selectOption({ label: 'Live shared response — MSP reference' })
  await page.getByRole('button', { name: 'Add block' }).click()
  await expect(page.getByRole('status')).toHaveText('Live shared response added as a live block.')
  await expect(page.getByText(/Live · revision 1/)).toBeVisible()
  await page.getByRole('button', { name: 'Review reuse' }).nth(1).click()
  await expect(page.getByRole('heading', { name: 'Reuse impact' })).toBeVisible()
  await expect(page.getByText(/3 live audiences will update/)).toBeVisible()
  await page.getByRole('button', { name: 'Close reuse impact' }).click()
  await page.getByRole('searchbox', { name: 'Reference an entity' }).fill('Live Main Campus')
  await page.getByRole('button', { name: /Live Main Campus.*site.*Live Acme Client/ }).click()
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 3.')
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('One MSP-owned block.')

  await page.goto('/documentation')
  await page.getByRole('button', { name: 'Live shared response' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('MSP-owned block revision two.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('heading', { name: 'Reuse impact' })).toBeVisible()
  await page.getByRole('button', { name: 'Approve impact and save' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 2.')

  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await expect(page.getByText(/Live · revision 2/)).toBeVisible()
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('MSP-owned block revision two.')
  await page.getByRole('button', { name: 'Pin revision' }).click()
  await expect(page.getByRole('status')).toHaveText('Block pinned to its current revision.')
  await page.getByRole('button', { name: 'Review reuse' }).nth(1).click()
  await expect(page.getByText(/1 pinned audience will stay unchanged/)).toBeVisible()
  await page.getByRole('button', { name: 'Detach into this workspace' }).click()
  await expect(page.getByRole('status')).toHaveText('Block detached as an independent copy in this workspace.')

  await page.goto('/documentation')
  await page.getByRole('button', { name: 'Live shared response' }).click()
  await page.getByRole('tab', { name: 'Markdown' }).click()
  await page.getByRole('textbox', { name: 'Markdown source' }).fill('MSP-owned block revision three.')
  await page.getByRole('button', { name: 'Save document' }).click()
  await page.getByRole('button', { name: 'Approve impact and save' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 3.')

  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await page.getByRole('button', { name: 'Live Acme onboarding' }).click()
  await expect(page.getByText(/Live · revision 1/)).toBeVisible()
  await page.getByText('View assembled Markdown').click()
  await expect(page.locator('.resolved-markdown pre')).toContainText('MSP-owned block revision two.')
  await expect(page.locator('.resolved-markdown pre')).not.toContainText('revision three')

  // Entity mentions are deliberately permission-aware. The site created earlier is
  // MSP-private by default, so remove that exercised mention before producing the
  // client-visible publication that the independent approver will authorize.
  await page.getByRole('tab', { name: 'Markdown' }).click()
  const clientDraft = page.getByRole('textbox', { name: 'Markdown source' })
  await clientDraft.fill((await clientDraft.inputValue()).replace(/\n?\[[^\]]+\]\(tekdocs:\/\/entity\/[0-9a-f-]{36}\)\n?/gi, '\n'))
  await page.getByRole('button', { name: 'Save document' }).click()
  await expect(page.getByRole('status')).toHaveText('Document saved as revision 4.')

  await page.getByRole('button', { name: 'Publish STATIC' }).click()
  await page.getByLabel('Publication reason').fill('Live publication regression')
  await page.getByLabel('Audience').selectOption('client_visible')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Publish immutable version' }).click()
  await expect(page.getByRole('status')).toHaveText('STATIC snapshot submitted. A different authorized user must approve client portal availability.')
  await expect(page.getByRole('heading', { name: 'Live Acme onboarding' })).toBeVisible()
  await expect(page.getByText('Signature verified', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download PDF' })).toBeVisible()
  await expect(page.locator('.publication-integrity code').first()).toContainText(/^SHA-256 [0-9a-f]{64}$/)
  await page.getByRole('button', { name: 'Close publication' }).click()
  await expect(page.getByRole('button', { name: /Live Acme onboarding.*1 STATIC/ })).toBeVisible()

  const portalEmail = `live-client-${suffix}@example.invalid`
  const currentCsrf = (await page.context().cookies()).find((cookie) => cookie.name === 'csrftoken')
  if (!currentCsrf) throw new Error('The owner session lost its CSRF cookie before client invitation.')
  const clientInvitation = await page.request.post(`/api/v1/workspaces/organizations/${clientId}/client-invitations`, {
    data: { email: portalEmail },
    headers: { 'X-CSRFToken': currentCsrf.value },
  })
  expect(clientInvitation.status()).toBe(201)
  const portalInvitationToken = await invitationTokenFromMailpit(page, portalEmail)
  const portalContext = await browser.newContext()
  const portalPage = await portalContext.newPage()
  portalPage.setDefaultTimeout(15_000)
  const portalPassword = `${randomBytes(24).toString('base64url')}Cc9!`
  await portalPage.goto(`/auth/invitations/accept#token=${portalInvitationToken}`)
  await portalPage.getByLabel('Your name').fill('Live Client Reader')
  await portalPage.getByLabel('Password', { exact: true }).fill(portalPassword)
  await portalPage.getByLabel('Confirm password').fill(portalPassword)
  await portalPage.getByRole('button', { name: 'Activate account' }).click()
  await expect(portalPage.getByRole('heading', { name: 'Published documentation' })).toBeVisible()
  await expect(portalPage.getByText('No documentation has been published to your organization.')).toBeVisible()
  await expect(portalPage.getByRole('link', { name: 'Organizations' })).not.toBeVisible()

  await staffPage.goto(`/workspaces/organizations/${clientId}/documentation`)
  await staffPage.locator('.static-publication-list').getByRole('button', { name: /Live Acme onboarding/ }).click()
  await staffPage.getByRole('button', { name: 'Approve publication' }).click()
  await staffPage.getByLabel('Decision reason').fill('Independent live-stack approval')
  staffPage.once('dialog', (dialog) => dialog.accept())
  await staffPage.getByRole('button', { name: 'Record approval' }).click()
  await expect(staffPage.getByRole('status')).toHaveText('Publication approved for its intended audience.')

  await portalPage.reload()
  await expect(portalPage.getByRole('button', { name: /Live Acme onboarding/ })).toBeVisible()
  await portalPage.getByRole('button', { name: /Live Acme onboarding/ }).click()
  await expect(portalPage.getByRole('heading', { name: 'Live Acme onboarding' })).toBeVisible()
  await expect(portalPage.getByText('Client visible', { exact: true })).toBeVisible()
  await expect(portalPage.getByRole('link', { name: 'live-acme-onboarding-static.pdf' })).toBeVisible()

  await expect.poll(async () => {
    const response = await portalPage.request.get('/api/v1/portal/notifications')
    if (!response.ok()) return []
    return ((await response.json()) as { results: Array<{ title: string }> }).results.map((item) => item.title)
  }, { timeout: 75_000 }).toEqual(expect.arrayContaining(['Portal access ready', 'Documentation published']))
  await portalPage.getByRole('button', { name: /Notifications/ }).click()
  await expect(portalPage.getByRole('dialog', { name: 'Notifications' })).toContainText('Documentation published')
  await portalPage.getByRole('button', { name: 'Email preferences' }).click()
  await portalPage.getByLabel('Delivery schedule').selectOption('daily')
  await portalPage.getByLabel('Use quiet hours').check()
  await portalPage.getByRole('button', { name: 'Save preferences' }).click()
  await expect(portalPage.getByRole('status')).toHaveText('Email preferences saved.')

  await page.goto(`/workspaces/organizations/${clientId}/documentation`)
  await page.locator('.static-publication-list').getByRole('button', { name: /Live Acme onboarding/ }).click()
  await page.getByRole('button', { name: 'Withdraw publication' }).click()
  await page.getByLabel('Decision reason').fill('Live withdrawal regression')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Record withdrawal' }).click()
  await expect(page.getByRole('status')).toHaveText('Publication withdrawn from audience availability; retained evidence remains accessible to authorized MSP staff.')
  await expect(page.getByRole('region', { name: 'Publication history' }).getByText('withdrawn', { exact: true })).toBeVisible()
  await portalPage.reload()
  await expect(portalPage.getByText('No documentation has been published to your organization.')).toBeVisible()
  await expect(portalPage.getByText('Live Acme onboarding')).not.toBeVisible()

  await page.goto(`/workspaces/organizations/${clientId}/compliance`)
  await page.getByRole('button', { name: 'New framework' }).click()
  await page.getByLabel('Framework name').fill('Live monitoring baseline')
  await page.getByLabel('Version label').fill('2026.1')
  await page.getByLabel('Version description').fill('Live composed certification evidence.')
  await page.getByLabel('Identifier').fill('MON-1')
  await page.getByLabel('Title').fill('Review managed domains')
  await page.getByLabel('Description (Markdown)').fill('Retain scoped domain and certificate evidence.')
  await page.getByRole('button', { name: 'Create framework' }).click()
  await expect(page.getByRole('heading', { name: 'Live monitoring baseline' })).toBeVisible()
  await page.getByRole('button', { name: 'Review control' }).click()
  const controlReview = page.locator('.compliance-assignment-form')
  await controlReview.getByLabel('Applicability').selectOption('applicable')
  await controlReview.locator('select').nth(1).selectOption('implemented')
  await controlReview.getByLabel('Decision').fill('Live monitoring control reviewed')
  await controlReview.getByRole('button', { name: 'Save review' }).click()
  await expect(page.getByText('applicable · implemented')).toBeVisible()
  await page.getByRole('button', { name: 'Create signed bundle' }).click()
  await expect(page.getByText('Verified', { exact: true })).toBeVisible()

  await page.goto(`/workspaces/organizations/${clientId}/domains`)
  await page.getByRole('button', { name: 'Add domain' }).click()
  await page.getByLabel('Domain name').fill('live-acme.example')
  await page.getByLabel('Expires on').fill('2027-08-13')
  await page.getByRole('button', { name: 'Save domain' }).click()
  await expect(page.getByText('live-acme.example', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Details' }).click()
  await expect(page.getByRole('heading', { name: 'Monitoring details' })).toBeVisible()
  await page.getByRole('button', { name: 'Add endpoint' }).click()
  await page.getByRole('button', { name: 'Save endpoint' }).click()
  await expect(page.getByRole('cell', { name: 'HTTPS' })).toBeVisible()

  const privateLink = 'https://start.1password.com/open/i?a=aaaaaaaaaaaaaaaaaaaaaaaaaa&v=vvvvvvvvvvvvvvvvvvvvvvvvvv&i=iiiiiiiiiiiiiiiiiiiiiiiiii&h=example.1password.com'
  await page.goto(`/workspaces/organizations/${clientId}/credentials`)
  await page.getByRole('button', { name: 'New reference' }).click()
  await page.getByLabel('Title', { exact: true }).fill('Live firewall administrator')
  await page.getByPlaceholder('https://start.1password.com/open/i?…').fill(privateLink)
  await page.getByRole('button', { name: 'Save reference' }).click()
  const providerHandoff = page.getByRole('link', { name: /Open in 1Password/ })
  await expect(providerHandoff).toBeVisible()
  const handoffHref = await providerHandoff.getAttribute('href')
  if (!handoffHref) throw new Error('The saved reference did not expose its same-origin handoff route.')
  expect(handoffHref).toMatch(new RegExp(`/api/v1/workspaces/organizations/${clientId}/credential-references/[0-9a-f-]+/open$`))
  const handoffResponse = await page.request.get(handoffHref, { maxRedirects: 0 })
  expect(handoffResponse.status()).toBe(302)
  expect(handoffResponse.headers().location).toBe(privateLink)
  await expect(page.locator('body')).not.toContainText(privateLink)
  await portalContext.close()
  await staffContext.close()
})
